In [1]:
import numpy as np
import pandas as pd

In [2]:
# load datasets
datasets = {}
years = range(2016, 2023)
for year in years:
    print(f"EIE {year} Loading...")
    if int(year) >= 2019:
        file_name = f'Odata{year}File.csv'
    else:
        file_name = f'OpenData{year}.csv'
    try:           
        dataset = pd.read_csv(f"../../zno/{year}/{file_name}", sep=";", encoding='utf-8')
    except:
        dataset = pd.read_csv(f"../../zno/{year}/{file_name}", sep=";", encoding='Windows 1251')
    datasets.update({year:dataset})
    print("success")

EIE 2016 Loading...
success
EIE 2017 Loading...
success
EIE 2018 Loading...

/var/folders/cz/wq9d8j_11fx3b8pjjbk7z8br0000gn/T/ipykernel_85301/3686568105.py:11: DtypeWarning: Columns (119) have mixed types. Specify dtype option on import or set low_memory=False.
  dataset = pd.read_csv(f"../../zno/{year}/{file_name}", sep=";", encoding='utf-8')

success
EIE 2019 Loading...

/var/folders/cz/wq9d8j_11fx3b8pjjbk7z8br0000gn/T/ipykernel_85301/3686568105.py:13: DtypeWarning: Columns (100,116,117,118,120,122,123,124,125) have mixed types. Specify dtype option on import or set low_memory=False.
  dataset = pd.read_csv(f"../../zno/{year}/{file_name}", sep=";", encoding='Windows 1251')

success
EIE 2020 Loading...

/var/folders/cz/wq9d8j_11fx3b8pjjbk7z8br0000gn/T/ipykernel_85301/3686568105.py:13: DtypeWarning: Columns (96,97,98,100,102,103,104,105,116,117,118,120,122,123,124,125) have mixed types. Specify dtype option on import or set low_memory=False.
  dataset = pd.read_csv(f"../../zno/{year}/{file_name}", sep=";", encoding='Windows 1251')

success
EIE 2021 Loading...

/var/folders/cz/wq9d8j_11fx3b8pjjbk7z8br0000gn/T/ipykernel_85301/3686568105.py:11: DtypeWarning: Columns (117,118,119,121,123,124,125,126,137,138,139,141,143,144,145,146) have mixed types. Specify dtype option on import or set low_memory=False.
  dataset = pd.read_csv(f"../../zno/{year}/{file_name}", sep=";", encoding='utf-8')

success
EIE 2022 Loading...
success

In [3]:
for year, dataset in datasets.items():
    #lowercase all columns and add year as attribute
    dataset.columns = [col.lower() for col in dataset.columns]

In [4]:
for year, dataset in datasets.items():
    print([col for col in dataset.columns if col.startswith('eo')])

['eoname', 'eotypename', 'eoregname', 'eoareaname', 'eotername', 'eoparent']
['eoname', 'eotypename', 'eoregname', 'eoareaname', 'eotername', 'eoparent']
['eoname', 'eotypename', 'eoregname', 'eoareaname', 'eotername', 'eoparent']
['eoname', 'eotypename', 'eoregname', 'eoareaname', 'eotername', 'eoparent']
['eoname', 'eotypename', 'eoregname', 'eoareaname', 'eotername', 'eoparent']
['eoname', 'eotypename', 'eoregname', 'eoareaname', 'eotername', 'eoparent']
['eoname', 'eotypename', 'eoregname', 'eoareaname', 'eotername', 'eoparent']

In [5]:
schools_edrpou = pd.DataFrame(columns=['eoname', 'eoregname', 'eoareaname', 'eotername'])

In [6]:
for year, dataset in datasets.items():
    schools_edrpou = pd.concat([schools_edrpou, dataset.loc[:, ['eoname', 'eoregname', 'eoareaname', 'eotername']]], ignore_index=True)

schools_edrpou

,eoname,eoregname,eoareaname,eotername
0,"Терпіннівський колегіум ""Джерело"" Мелітопольсь...",Запорізька область,Мелітопольський район,с.Терпіння
1,Красилівська загальноосвітня школа I-III ступе...,Хмельницька область,Красилівський район,м.Красилів
2,NaN,NaN,NaN,NaN
3,Чернівецька спеціалізована школа І-ІІІ ступені...,Чернівецька область,м.Чернівці,Шевченківський район міста
4,NaN,NaN,NaN,NaN
...,...,...,...,...
2201113,Заболотцівський ліцей Литовезької сільської ра...,Волинська область,Володимирський район,с.Заболотці
2201114,Заболотцівський ліцей Литовезької сільської ра...,Волинська область,Володимирський район,с.Заболотці
2201115,Заболотцівський ліцей Литовезької сільської ра...,Волинська область,Володимирський район,с.Заболотці
2201116,Заболотцівський ліцей Литовезької сільської ра...,Волинська область,Володимирський район,с.Заболотці
2201117,Павлівська загальноосвітня школа I-III ступені...,Херсонська область,Каховський район,с.Павлівка (Присиваська)

In [7]:
schools_edrpou.drop_duplicates(inplace=True)
# when paricipant graduated in the previous years the corresponding information about school
# (everything with 'eo') is NaN
#we drop these rows
schools_edrpou.dropna(how = 'all', inplace=True)
schools_edrpou.reset_index(drop=True, inplace=True)
schools_edrpou

,eoname,eoregname,eoareaname,eotername
0,"Терпіннівський колегіум ""Джерело"" Мелітопольсь...",Запорізька область,Мелітопольський район,с.Терпіння
1,Красилівська загальноосвітня школа I-III ступе...,Хмельницька область,Красилівський район,м.Красилів
2,Чернівецька спеціалізована школа І-ІІІ ступені...,Чернівецька область,м.Чернівці,Шевченківський район міста
3,Загальноосвітня школа I-III ступенів № 6 Дружк...,Донецька область,Донецька область,м.Дружківка
4,Тернопільська спеціалізована школа І-ІІІ ступе...,Тернопільська область,Тернопільська область,м.Тернопіль
...,...,...,...,...
34380,Гульський ліцей Стриївської сільської ради Нов...,Житомирська область,Новоград-Волинський район,с.Гульськ
34381,Киківський ліцей Стриївської сільської ради Но...,Житомирська область,Новоград-Волинський район,с.Кикова
34382,Литовезький ліцей імені Володимира Якобчука Во...,Волинська область,Володимирський район,с.Литовеж
34383,Заболотцівський ліцей Литовезької сільської ра...,Волинська область,Володимирський район,с.Заболотці
34384,Павлівська загальноосвітня школа I-III ступені...,Херсонська область,Каховський район,с.Павлівка (Присиваська)

In [8]:
locations = pd.read_csv('./location_data/locations.csv', encoding='utf-8', dtype=str)
locations

,regname,areaname,tername,KOATUU_2020,KATOTTG_2023
0,Запорізька область,Мелітопольський район,с.Терпіння,2323085101,UA23080270010078454
1,Хмельницька область,Красилівський район,м.Красилів,6822710100,UA68040210010032567
2,Дніпропетровська область,Петропавлівський район,с.Дмитрівка,1223881501,UA12140170040016918
3,Чернівецька область,м.Чернівці,Шевченківський район міста,7310100000,UA73060610010033137
4,Миколаївська область,Врадіївський район,с.Кумарі,4822383001,UA48080050190079797
...,...,...,...,...,...
28878,Інші країни,м.Гронінген,м.Гронінген,0017010000,OC17010000000000000
28879,Інші країни,м.Люксембург,м.Люксембург,0015010000,OC15010000000000000
28880,Інші країни,м.Марібор,м.Марібор,0023010000,OC23010000000000000
28881,Інші країни,м.Сакраменто,м.Сакраменто,0024020000,OC24020000000000000
28882,Інші країни,м.Едмонтон,м.Едмонтон,0012010000,OC12010000000000000

In [9]:
schools_edrpou = schools_edrpou.merge(locations[['KOATUU_2020']], left_on=[schools_edrpou['eoregname'],schools_edrpou['eoareaname'], schools_edrpou['eotername']], right_on=[locations['regname'],locations['areaname'], locations['tername']], how='left')
schools_edrpou = schools_edrpou.drop(columns = ['key_0', 'key_1', 'key_2'], axis=1)
schools_edrpou.head()

,eoname,eoregname,eoareaname,eotername,KOATUU_2020
0,"Терпіннівський колегіум ""Джерело"" Мелітопольсь...",Запорізька область,Мелітопольський район,с.Терпіння,2323085101
1,Красилівська загальноосвітня школа I-III ступе...,Хмельницька область,Красилівський район,м.Красилів,6822710100
2,Чернівецька спеціалізована школа І-ІІІ ступені...,Чернівецька область,м.Чернівці,Шевченківський район міста,7310100000
3,Загальноосвітня школа I-III ступенів № 6 Дружк...,Донецька область,Донецька область,м.Дружківка,1411700000
4,Тернопільська спеціалізована школа І-ІІІ ступе...,Тернопільська область,Тернопільська область,м.Тернопіль,6110100000

In [10]:
schools_edrpou_id= schools_edrpou[['eoname', 'KOATUU_2020']]
schools_edrpou_id.drop_duplicates(inplace=True)
schools_edrpou_id.reset_index(drop=True, inplace=True)
schools_edrpou_id

/var/folders/cz/wq9d8j_11fx3b8pjjbk7z8br0000gn/T/ipykernel_85301/3377070480.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  schools_edrpou_id.drop_duplicates(inplace=True)

                                                  eoname KOATUU_2020
0      Терпіннівський колегіум "Джерело" Мелітопольсь...  2323085101
1      Красилівська загальноосвітня школа I-III ступе...  6822710100
2      Чернівецька спеціалізована школа І-ІІІ ступені...  7310100000
3      Загальноосвітня школа I-III ступенів № 6 Дружк...  1411700000
4      Тернопільська спеціалізована школа І-ІІІ ступе...  6110100000
...                                                  ...         ...
27506  Гульський ліцей Стриївської сільської ради Нов...  1824081001
27507  Киківський ліцей Стриївської сільської ради Но...  1824081801
27508  Литовезький ліцей імені Володимира Якобчука Во...  0721182401
27509  Заболотцівський ліцей Литовезької сільської ра...  0721182403
27510  Павлівська загальноосвітня школа I-III ступені...  6525483001

[27511 rows x 2 columns]

In [2]:
schools_edrpou_id.loc[:,'id'] = schools_edrpou_id['eoname']

abbr = {'КЗ ':'Комунальний заклад ', 'ОНЗ ':'Опорний навчальний заклад ', 'ОЗЗСО ':'Опорний заклад загальної середньої освіти ',
        'ЗЗСО ':'Заклад загальної середньої освіти ', 'ООЗ ':'Опорний освітній заклад ', 'ЗСО ':'Загальної середньої освіти ', 
        'НВК ':'Навчально-виховний комплекс ', 'ЗОШ ':'Загальнооосвітня школа ', 'СЗШ ':'Середня загальноосвітня школа ', 'ТОВ ': 'Товариство з обмеженою відповідальністю '}

for ab in abbr:
    schools_edrpou_id.loc[:,'id'] = schools_edrpou_id['id'].str.replace(ab, abbr[ab])

schools_edrpou_id.loc[:,'id'] = schools_edrpou_id['id'].str.replace('[\s]', '', regex = True)
schools_edrpou_id.loc[schools_edrpou_id['id'].str.endswith('обл'), 'id'] = schools_edrpou_id.loc[schools_edrpou_id['id'].str.endswith('обл'), 'id'] + '.'
schools_edrpou_id.loc[:,'id'] = schools_edrpou_id['id'].str.replace('І', 'I')
schools_edrpou_id.loc[:,'id'] = schools_edrpou_id['id'].str.replace('I-III', '3')
schools_edrpou_id.loc[:,'id'] = schools_edrpou_id['id'].str.replace('I-II', '2')
schools_edrpou_id.loc[:,'id'] = schools_edrpou_id['id'].str.lower()

dct = {'с.':'села', 'ст.':'ступенів', 'ім.':'імені', 'iм.':'імені', 'обл.': 'області', 
       '||||':'3', '|||':'2',
       'i':'', 'і':'', 'ї':'', 'o':'о', 'y':'у', 'p':'р', 'c':'с', 'ґ':'г', 'e':'е', 'a':'а', 'k':'к', 'x': 'х', 
       "'":'', "’":'', ",":'', ".":'', "«":'', "»":'', "–":'', "-":'', "*":"",
       "_x000d_":'', '_x000D_':'', "_":'', "(":'', ")":'', "[":'', "]":'', "}":'', "{":'', 
       "нвк":'навчальновиховнийкомплекс', 'знз': 'загальноосвтнйнавчальнийзаклад', 'зош': 'загальноосвтняшкола', 
       'сзш':'середнязагальноосвтняшкола', 'нн':'н'}

for symb in dct:
    schools_edrpou_id.loc[:,'id'] = schools_edrpou_id['id'].str.replace(symb, dct[symb])

schools_edrpou_id.loc[:,'id'] = schools_edrpou_id['id'].str.replace('"', '', regex = True)

NameError: name 'schools_edrpou_id' is not defined

In [12]:
schools_edrpou_id

,eoname,KOATUU_2020,id
0,"Терпіннівський колегіум ""Джерело"" Мелітопольсь...",2323085101,терпнвськийколегумджереломелтопольськорайонора...
1,Красилівська загальноосвітня школа I-III ступе...,6822710100,красилвськазагальноосвтняшкола3ступенв№3красил...
2,Чернівецька спеціалізована школа І-ІІІ ступені...,7310100000,чернвецькаспецалзованашкола3ступенвфзикоматема...
3,Загальноосвітня школа I-III ступенів № 6 Дружк...,1411700000,загальноосвтняшкола3ступенв№6дружквськомськора...
4,Тернопільська спеціалізована школа І-ІІІ ступе...,6110100000,тернопльськаспецалзованашкола3ступенв№3зпоглиб...
...,...,...,...
27506,Гульський ліцей Стриївської сільської ради Нов...,1824081001,гульськийлцейстривськосльськорадиновоградволин...
27507,Киківський ліцей Стриївської сільської ради Но...,1824081801,киквськийлцейстривськосльськорадиновоградволин...
27508,Литовезький ліцей імені Володимира Якобчука Во...,0721182401,литовезькийлцейменволодимираякобчукаволодимирв...
27509,Заболотцівський ліцей Литовезької сільської ра...,0721182403,заболотцвськийлцейлитовезькосльськорадиволодим...
27510,Павлівська загальноосвітня школа I-III ступені...,6525483001,павлвськазагальноосвтняшкола3ступенвприсиваськ...

In [13]:
schools_data = pd.read_excel('./school_data/Schools_02.08.2023 16-56.xlsx', dtype = str)
schools_data

,Повна назва,Код в ЄДЕБО,ОУО підтвердив дані,Скорочена назва,Код ЄДРПОУ,Статус,Тип закладу,Форма власності,Код КОАТУУ,Регіон,...,Телефон,Факс,Електронна пошта,Веб-сайт,Керівник,Опорний / Філія,Сільський,Гірський,Інтернат,Ліцензовані обсяги
0,«ПРИВАТНИЙ ЗАКЛАД ОСВІТИ «КМДШ» №2 М. КИЇВ» (В...,150646,так,"ПЗО ""КМДШ"" № 2 м. Київ",43031126,ліквідовано,школа,Приватна,8036100000,КИЇВ,...,(0800)330810,NaN,kmds2@kmds.kiev.ua,https://www.creativeschool.com.ua/,Директор Фісунова Лідія Олексіївна,ні,ні,ні,ні,NaN
1,Гімназія № 236 міста Києва,148438,так,Гімназія № 236,22879470,працює,гімназія,Комунальна,8036100000,КИЇВ,...,(044)5264358,(044)5262002,school236@ukr.net,http://school-236.at.ua/,Директор Добровольська Оксана Миколаївна,ні,ні,ні,ні,NaN
2,Гімназія № 87 міста Києва,148421,так,Гімназія № 87,22881515,працює,гімназія,Комунальна,8036100000,КИЇВ,...,"(044)234-50-55, (044)235-60-63",(044)234-50-55,gymnasium87@ukr.net,http://school87.ucoz.net/,Директор Гентош Ольга Анатоліївна,ні,ні,ні,ні,NaN
3,Гімназія №150 міста Києва,148431,так,Гімназія № 150,22879429,працює,гімназія,Комунальна,8036100000,КИЇВ,...,(044)259-31-60,(044)525-30-31,150shkola@ukr.net,http://school150.klasna.com/uk,Директор Гришко Юрій Юрійович,ні,ні,ні,ні,NaN
4,гімназія №179 міста Києва,148440,так,гімназія №179 міста Києва,22879435,працює,гімназія,Комунальна,8036100000,КИЇВ,...,(044)2584242,NaN,gymn179@hotmail.com,http://179.kiev.ua,Директор Бойко Ірина Львівна,ні,ні,ні,ні,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17330,"Яблунівський навчально-виховний комплекс ""Зага...",144723,так,NaN,33329891,ліквідовано,навчально-виховний комплекс (об'єднання),Комунальна,7423886502,Чернігівська область,...,(046)422-43-40,NaN,solovejzanna8@gmail.com,NaN,Директор Новік Ольга Іванівна,ні,так,ні,ні,1
17331,"Ягіднянська філія опорного закладу ""Количівськ...",145351,так,NaN,43195202,ліквідовано,школа,Комунальна,7425582803,Чернігівська область,...,(0462)687733,NaN,yagidneschool@ukr.net,NaN,Завідувач філією Курилець Ніна Михайлівна,Філія,так,ні,ні,NaN
17332,Ядутинська загальноосвітня школа І-ІІІ ступені...,135163,так,Ядутинська ЗОШ І-ІІІ ст.,33365840,працює,школа,Комунальна,7420889601,Чернігівська область,...,(04653)27571,NaN,yaduti@ukr.net,NaN,Шостак Ірина Володимирівна,ні,так,ні,ні,1
17333,Янжулівська філія І-ІІ ступенів Семенівської г...,134967,так,Янжулівська філія І-ІІ ст.,25955585,працює,школа,Комунальна,7424781701,Чернігівська область,...,(046)5924644,NaN,NaN,NaN,Завідувач філією Подоляк Ірина Миколаївна,Філія,так,ні,ні,90
17334,Ярославська філія І-ІІ ступенів Бобровицькогоз...,141845,так,Ярославська філія І-ІІ ступенів Бобровицького ...,24836938,працює,школа,Комунальна,7420688401,Чернігівська область,...,(067)4223332,NaN,yaroslavka.zzso@ukr.net,NaN,Завідувач філією Смага Ольга Миколаївна,ні,так,ні,ні,NaN

In [14]:
schools_data_id = schools_data

In [15]:
schools_data_id['id'] = schools_data_id['Повна назва']

abbr = {'КЗ ':'Комунальний заклад ', 'ОНЗ ':'Опорний навчальний заклад ', 'ОЗЗСО ':'Опорний заклад загальної середньої освіти ',
        'ЗЗСО ':'Заклад загальної середньої освіти ', 'ООЗ ':'Опорний освітній заклад ', 'ЗСО ':'Загальної середньої освіти ', 
        'НВК ':'Навчально-виховний комплекс ', 'ЗОШ ':'Загальнооосвітня школа ', 'СЗШ ':'Середня загальноосвітня школа ', 'ТОВ ': 'Товариство з обмеженою відповідальністю '}

for ab in abbr:
    schools_data_id['id'] = schools_data_id['id'].str.replace(ab, abbr[ab])

schools_data_id['id'] = schools_data_id['id'].str.replace('[\s]', '', regex = True)
schools_data_id.loc[schools_data_id['id'].str.endswith('обл'), 'id'] = schools_data_id.loc[schools_edrpou_id['id'].str.endswith('обл'), 'id'] + '.'
schools_data_id['id'] = schools_data_id['id'].str.replace('І', 'I')
schools_data_id['id'] = schools_data_id['id'].str.replace('I-III', '3')
schools_data_id['id'] = schools_data_id['id'].str.replace('I-II', '2')
schools_data_id['id'] = schools_data_id['id'].str.lower()

dct = {'с.':'села', 'ст.':'ступенів', 'ім.':'імені', 'iм.':'імені', 'обл.': 'області', 
       '||||':'3', '|||':'2',
       'i':'', 'і':'', 'ї':'', 'o':'о', 'y':'у', 'p':'р', 'c':'с', 'ґ':'г', 'e':'е', 'a':'а', 'k':'к', 'x': 'х', 
       "'":'', "’":'', ",":'', ".":'', "«":'', "»":'', "–":'', "-":'', "*":"",
       "_x000d_":'', '_x000D_':'', "_":'', "(":'', ")":'', "[":'', "]":'', "}":'', "{":'', 
       "нвк":'навчальновиховнийкомплекс', 'знз': 'загальноосвтнйнавчальнийзаклад', 'зош': 'загальноосвтняшкола', 
       'сзш':'середнязагальноосвтняшкола', 'нн':'н'}

for symb in dct:
    schools_data_id['id'] = schools_data_id['id'].str.replace(symb, dct[symb])

schools_data_id['id'] = schools_data_id['id'].str.replace('"', '', regex = True)

In [16]:
schools_data_id

,Повна назва,Код в ЄДЕБО,ОУО підтвердив дані,Скорочена назва,Код ЄДРПОУ,Статус,Тип закладу,Форма власності,Код КОАТУУ,Регіон,...,Факс,Електронна пошта,Веб-сайт,Керівник,Опорний / Філія,Сільський,Гірський,Інтернат,Ліцензовані обсяги,id
0,«ПРИВАТНИЙ ЗАКЛАД ОСВІТИ «КМДШ» №2 М. КИЇВ» (В...,150646,так,"ПЗО ""КМДШ"" № 2 м. Київ",43031126,ліквідовано,школа,Приватна,8036100000,КИЇВ,...,NaN,kmds2@kmds.kiev.ua,https://www.creativeschool.com.ua/,Директор Фісунова Лідія Олексіївна,ні,ні,ні,ні,NaN,приватнийзакладосвтикмдш№2мкиввдокремленийстру...
1,Гімназія № 236 міста Києва,148438,так,Гімназія № 236,22879470,працює,гімназія,Комунальна,8036100000,КИЇВ,...,(044)5262002,school236@ukr.net,http://school-236.at.ua/,Директор Добровольська Оксана Миколаївна,ні,ні,ні,ні,NaN,гмназя№236мстакиєва
2,Гімназія № 87 міста Києва,148421,так,Гімназія № 87,22881515,працює,гімназія,Комунальна,8036100000,КИЇВ,...,(044)234-50-55,gymnasium87@ukr.net,http://school87.ucoz.net/,Директор Гентош Ольга Анатоліївна,ні,ні,ні,ні,NaN,гмназя№87мстакиєва
3,Гімназія №150 міста Києва,148431,так,Гімназія № 150,22879429,працює,гімназія,Комунальна,8036100000,КИЇВ,...,(044)525-30-31,150shkola@ukr.net,http://school150.klasna.com/uk,Директор Гришко Юрій Юрійович,ні,ні,ні,ні,NaN,гмназя№150мстакиєва
4,гімназія №179 міста Києва,148440,так,гімназія №179 міста Києва,22879435,працює,гімназія,Комунальна,8036100000,КИЇВ,...,NaN,gymn179@hotmail.com,http://179.kiev.ua,Директор Бойко Ірина Львівна,ні,ні,ні,ні,NaN,гмназя№179мстакиєва
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17330,"Яблунівський навчально-виховний комплекс ""Зага...",144723,так,NaN,33329891,ліквідовано,навчально-виховний комплекс (об'єднання),Комунальна,7423886502,Чернігівська область,...,NaN,solovejzanna8@gmail.com,NaN,Директор Новік Ольга Іванівна,ні,так,ні,ні,1,яблунвськийнавчальновиховнийкомплексзагальноос...
17331,"Ягіднянська філія опорного закладу ""Количівськ...",145351,так,NaN,43195202,ліквідовано,школа,Комунальна,7425582803,Чернігівська область,...,NaN,yagidneschool@ukr.net,NaN,Завідувач філією Курилець Ніна Михайлівна,Філія,так,ні,ні,NaN,ягднянськафляопорногозакладуколичвськазагально...
17332,Ядутинська загальноосвітня школа І-ІІІ ступені...,135163,так,Ядутинська ЗОШ І-ІІІ ст.,33365840,працює,школа,Комунальна,7420889601,Чернігівська область,...,NaN,yaduti@ukr.net,NaN,Шостак Ірина Володимирівна,ні,так,ні,ні,1,ядутинськазагальноосвтняшкола3ступенвборзнянсь...
17333,Янжулівська філія І-ІІ ступенів Семенівської г...,134967,так,Янжулівська філія І-ІІ ст.,25955585,працює,школа,Комунальна,7424781701,Чернігівська область,...,NaN,NaN,NaN,Завідувач філією Подоляк Ірина Миколаївна,Філія,так,ні,ні,90,янжулвськафля2ступенвсеменвськогмназ№2семенвсь...
17334,Ярославська філія І-ІІ ступенів Бобровицькогоз...,141845,так,Ярославська філія І-ІІ ступенів Бобровицького ...,24836938,працює,школа,Комунальна,7420688401,Чернігівська область,...,NaN,yaroslavka.zzso@ukr.net,NaN,Завідувач філією Смага Ольга Миколаївна,ні,так,ні,ні,NaN,ярославськафля2ступенвбобровицькогозакладузага...

In [17]:
schools_ed = schools_edrpou_id.merge(schools_data_id[['Код ЄДРПОУ']], left_on=[schools_edrpou_id['id'],schools_edrpou_id['KOATUU_2020']], right_on=[schools_data_id['id'],schools_data_id['Код КОАТУУ']], how='left')
schools_ed = schools_ed.drop(columns = ['key_0', 'key_1'], axis=1)
schools_ed.head()

,eoname,KOATUU_2020,id,Код ЄДРПОУ
0,"Терпіннівський колегіум ""Джерело"" Мелітопольсь...",2323085101,терпнвськийколегумджереломелтопольськорайонора...,NaN
1,Красилівська загальноосвітня школа I-III ступе...,6822710100,красилвськазагальноосвтняшкола3ступенв№3красил...,NaN
2,Чернівецька спеціалізована школа І-ІІІ ступені...,7310100000,чернвецькаспецалзованашкола3ступенвфзикоматема...,NaN
3,Загальноосвітня школа I-III ступенів № 6 Дружк...,1411700000,загальноосвтняшкола3ступенв№6дружквськомськора...,25705061
4,Тернопільська спеціалізована школа І-ІІІ ступе...,6110100000,тернопльськаспецалзованашкола3ступенв№3зпоглиб...,14040173

In [18]:
schools_ed[schools_ed['Код ЄДРПОУ'].isna()]

,eoname,KOATUU_2020,id,Код ЄДРПОУ
0,"Терпіннівський колегіум ""Джерело"" Мелітопольсь...",2323085101,терпнвськийколегумджереломелтопольськорайонора...,NaN
1,Красилівська загальноосвітня школа I-III ступе...,6822710100,красилвськазагальноосвтняшкола3ступенв№3красил...,NaN
2,Чернівецька спеціалізована школа І-ІІІ ступені...,7310100000,чернвецькаспецалзованашкола3ступенвфзикоматема...,NaN
5,"Тарасівський навчально-виховний комплекс ""Зага...",3523486901,тарасвськийнавчальновиховнийкомплексзагальноос...,NaN
6,Одеська загальноосвітня школа № 14 I-III ступе...,5110137600,одеськазагальноосвтняшкола№143ступенводеськомс...,NaN
...,...,...,...,...
27498,Зорянський заклад загальної середньої освіти і...,1422482708,зорянськийзакладзагальносередньоосвтименгерояр...,NaN
27505,Стратіївський заклад загальної середньої освіт...,0525085301,стратвськийзакладзагальносередньоосвтиольгопль...,NaN
27508,Бібрський опорний ліцей імені Уляни Кравченко ...,4623310300,ббрськийопорнийлцейменуляникравченкоббрськомсь...,NaN
27514,Литовезький ліцей імені Володимира Якобчука Во...,0721182401,литовезькийлцейменволодимираякобчукаволодимирв...,NaN
27515,Заболотцівський ліцей Литовезької сільської ра...,0721182403,заболотцвськийлцейлитовезькосльськорадиволодим...,NaN

In [19]:
schools_ed[schools_ed['Код ЄДРПОУ'].notna()]

,eoname,KOATUU_2020,id,Код ЄДРПОУ
3,Загальноосвітня школа I-III ступенів № 6 Дружк...,1411700000,загальноосвтняшкола3ступенв№6дружквськомськора...,25705061
4,Тернопільська спеціалізована школа І-ІІІ ступе...,6110100000,тернопльськаспецалзованашкола3ступенв№3зпоглиб...,14040173
38,Слов'янський педагогічний ліцей Слов'янської м...,1414100000,словянськийпедагогчнийлцейсловянськомськорадид...,33534376
46,Комунальний заклад «Харківська загальноосвітня...,6310138500,комунальнийзакладхарквськазагальноосвтняшкола3...,25779605
47,Черкаська загальноосвітня школа І-ІІІ ступенів...,7110136400,черкаськазагальноосвтняшкола3ступенв№15черкась...,25660387
...,...,...,...,...
27510,Свірзький ліцей Бібрської міської ради Львівсь...,4623386401,сврзькийлцейббрськомськорадильввськогорайонуль...,22368930
27511,Суслівський ліцей Стриївської сільської ради Н...,1824085601,суслвськийлцейстривськосльськорадиновоградволи...,06670121
27512,Гульський ліцей Стриївської сільської ради Нов...,1824081001,гульськийлцейстривськосльськорадиновоградволин...,06669744
27513,Киківський ліцей Стриївської сільської ради Но...,1824081801,киквськийлцейстривськосльськорадиновоградволин...,06669773
27516,Павлівська загальноосвітня школа I-III ступені...,6525483001,павлвськазагальноосвтняшкола3ступенвприсиваськ...,24754519

In [20]:
unmatched = schools_ed[schools_ed['Код ЄДРПОУ'].isna()].sort_values(by=['KOATUU_2020', 'eoname'])

In [21]:
unmatched.to_csv('unmatched.csv', index=False)

In [7]:
#!pip install -U duckpy
from duckpy import Client
from tqdm import tqdm
import time
tqdm.pandas()

def search_opendatabot(school_name, max_retry=20):
    """
    Search for school in opendatabot.ua
    """
    client = Client()
    opendatabot_url = ''
    retry = 0
    while not opendatabot_url and retry < max_retry:
        try:
            results = client.search(school_name.replace('"','').replace("'","")+ ' ЄДРПОУ', limit=20)
        except:
            time.sleep(20)
            continue
        for site in results:
            if site['url'].startswith('https://opendatabot.ua/c/'):
                opendatabot_url = site['url']
                break
        retry += 1
    return {'eoname': school_name, "url": opendatabot_url}

search_opendatabot("Комаровецький заклад загальної середньої освіти І-ІІ ступенів - заклад дошкільної освіти Барської міської ради")

{'eoname': 'Комаровецький заклад загальної середньої освіти І-ІІ ступенів - заклад дошкільної освіти Барської міської ради',
 'url': 'https://opendatabot.ua/c/26229527'}

In [23]:
opendatabot_links = []
for eoname in tqdm(unmatched['eoname']):
    opendatabot_links.append(search_opendatabot(eoname))

100%|██████████| 22121/22121 [22:09:37<00:00,  3.61s/it]

In [24]:
opendatabot_df = pd.DataFrame(opendatabot_links)
# TODO: join with unmatched table

In [ ]:
# # Works faster, but they will block your IP if you send too many requests
# from concurrent.futures.thread import ThreadPoolExecutor
# import concurrent

# opendatabot_links = []



# with ThreadPoolExecutor() as executor:
#     futures = []
#     print("Loading executor")
#     for eoname in tqdm(unmatched['eoname']):
#         future = executor.submit(search_opendatabot, eoname)
#         futures.append(future)
    
#     print("Collecting results from executor")
#     with tqdm(total=len(unmatched['eoname'])) as pbar:
#         for future in concurrent.futures.as_completed(futures):
#             result = future.result()
#             opendatabot_links.append(result)
#             pbar.update(1)

In [25]:
opendatabot_df

,eoname,url
0,"ВСП ""Технологічно-промисловий фаховий коледж В...",https://opendatabot.ua/c/00419667
1,Вище професійне училище №11 м. Вінниці,https://opendatabot.ua/c/03065891
2,Вище художнє професійно-технічне училище №5 м....,https://opendatabot.ua/c/02539890
3,"Відокремлений структурний підрозділ ""Вінницьки...",https://opendatabot.ua/c/35725833
4,"Відокремлений структурний підрозділ ""Вінницьки...",https://opendatabot.ua/c/38417484
...,...,...
22116,Школа №25 І-ІІІ ступенів Шевченківського район...,
22117,Школа №27 І-ІІІ ступенів Шевченківського район...,https://opendatabot.ua/c/26125710
22118,Школа №70 І-ІІІ ступенів Шевченківського район...,https://opendatabot.ua/c/22881828
22119,Школа №95 І-ІІІ ступенів Шевченківського район...,https://opendatabot.ua/c/26125905
22120,"Лучицький навчально-виховний комплекс ""Загальн...",https://opendatabot.ua/c/23947156

In [26]:
opendatabot_df[opendatabot_df.url.apply(lambda x: isinstance(x, str) and len(x.strip())> 0)]

,eoname,url
0,"ВСП ""Технологічно-промисловий фаховий коледж В...",https://opendatabot.ua/c/00419667
1,Вище професійне училище №11 м. Вінниці,https://opendatabot.ua/c/03065891
2,Вище художнє професійно-технічне училище №5 м....,https://opendatabot.ua/c/02539890
3,"Відокремлений структурний підрозділ ""Вінницьки...",https://opendatabot.ua/c/35725833
4,"Відокремлений структурний підрозділ ""Вінницьки...",https://opendatabot.ua/c/38417484
...,...,...
22104,"ТОВ ""Політико-правовий коледж ""АЛСКО""",https://opendatabot.ua/c/19033611
22117,Школа №27 І-ІІІ ступенів Шевченківського район...,https://opendatabot.ua/c/26125710
22118,Школа №70 І-ІІІ ступенів Шевченківського район...,https://opendatabot.ua/c/22881828
22119,Школа №95 І-ІІІ ступенів Шевченківського район...,https://opendatabot.ua/c/26125905
22120,"Лучицький навчально-виховний комплекс ""Загальн...",https://opendatabot.ua/c/23947156

In [27]:
unmatched_link = unmatched.merge(opendatabot_df[['url']], left_on=[unmatched['eoname']], right_on=[opendatabot_df['eoname']], how='left')
unmatched_link = unmatched_link.drop(columns = ['key_0'], axis=1)
unmatched_link.head()

,eoname,KOATUU_2020,id,Код ЄДРПОУ,url
0,"ВСП ""Технологічно-промисловий фаховий коледж В...",0510100000,всптехнологчнопромисловийфаховийколеджвницьког...,NaN,https://opendatabot.ua/c/00419667
1,Вище професійне училище №11 м. Вінниці,0510100000,вищепрофесйнеучилище№11мвниц,NaN,https://opendatabot.ua/c/03065891
2,Вище художнє професійно-технічне училище №5 м....,0510100000,вищехудожнєпрофесйнотехнчнеучилище№5мвниця,NaN,https://opendatabot.ua/c/02539890
3,"Відокремлений структурний підрозділ ""Вінницьки...",0510100000,вдокремленийструктурнийпдроздлвницькийфаховийк...,NaN,https://opendatabot.ua/c/35725833
4,"Відокремлений структурний підрозділ ""Вінницьки...",0510100000,вдокремленийструктурнийпдроздлвницькийфаховийк...,NaN,https://opendatabot.ua/c/38417484

In [31]:
unmatched_link.to_csv('unmatched_link.csv', index=False)

In [29]:
unmatched_new = unmatched_link[~unmatched_link.url.apply(lambda x: isinstance(x, str) and len(x.strip())> 0)]
unmatched_new

,eoname,KOATUU_2020,id,Код ЄДРПОУ,url
5,Відокремлений структурний підрозділ «Вінницьки...,0510100000,вдокремленийструктурнийпдроздлвницькийторговел...,NaN,
6,Відокремлений структурний підрозділ Вінницький...,0510100000,вдокремленийструктурнийпдроздлвницькийфаховийк...,NaN,
7,Відокремлений структурний підрозділ Закладу ви...,0510100000,вдокремленийструктурнийпдроздлзакладувищоосвти...,NaN,
8,Вінницька Установа виконання покарань Управлін...,0510100000,вницькаустановавиконаняпокараньуправлнядержавн...,NaN,
9,Вінницька виправна колонія Управління Державно...,0510100000,вницькавиправнаколоняуправлнядержавногодепарта...,NaN,
...,...,...,...,...,...
22434,Школа №163 І-ІІІ ступенів імені М.Кирпоноса Ше...,8039100000,школа№1633ступенвменменкирпоносашевченквського...,NaN,
22435,Школа №169 І-ІІІ ступенів Шевченківського райо...,8039100000,школа№1693ступенвшевченквськогорайонумкиєва,NaN,
22436,Школа №175 І-ІІІ ступенів Шевченківського райо...,8039100000,школа№1753ступенвшевченквськогорайонумкиєва,NaN,
22437,Школа №199 І-ІІІ ступенів Шевченківського райо...,8039100000,школа№1993ступенвшевченквськогорайонумкиєва,NaN,
22438,Школа №25 І-ІІІ ступенів Шевченківського район...,8039100000,школа№253ступенвшевченквськогорайонумкиєва,NaN,

In [30]:
opendatabot_links_new = []
for eoname in tqdm(unmatched_new['eoname']):
    opendatabot_links_new.append(search_opendatabot(eoname))

100%|██████████| 14917/14917 [14:45:43<00:00,  3.56s/it]

In [32]:
opendatabot_df_new = pd.DataFrame(opendatabot_links_new)
opendatabot_df_new

,eoname,url
0,Відокремлений структурний підрозділ «Вінницьки...,
1,Відокремлений структурний підрозділ Вінницький...,
2,Відокремлений структурний підрозділ Закладу ви...,
3,Вінницька Установа виконання покарань Управлін...,
4,Вінницька виправна колонія Управління Державно...,
...,...,...
14912,Школа №163 І-ІІІ ступенів імені М.Кирпоноса Ше...,https://opendatabot.ua/c/26125756
14913,Школа №169 І-ІІІ ступенів Шевченківського райо...,https://opendatabot.ua/c/22881900
14914,Школа №175 І-ІІІ ступенів Шевченківського райо...,https://opendatabot.ua/c/26125940
14915,Школа №199 І-ІІІ ступенів Шевченківського райо...,https://opendatabot.ua/c/22881923
14916,Школа №25 І-ІІІ ступенів Шевченківського район...,

In [ ]:
unmatched_new

In [33]:
unmatched_link = unmatched_link.merge(opendatabot_df_new[['url']], left_on=[unmatched_link['eoname']], right_on=[opendatabot_df_new['eoname']], how='left')
unmatched_link = unmatched_link.drop(columns = ['key_0'], axis=1)
unmatched_link.head()

,eoname,KOATUU_2020,id,Код ЄДРПОУ,url_x,url_y
0,"ВСП ""Технологічно-промисловий фаховий коледж В...",0510100000,всптехнологчнопромисловийфаховийколеджвницьког...,NaN,https://opendatabot.ua/c/00419667,NaN
1,Вище професійне училище №11 м. Вінниці,0510100000,вищепрофесйнеучилище№11мвниц,NaN,https://opendatabot.ua/c/03065891,NaN
2,Вище художнє професійно-технічне училище №5 м....,0510100000,вищехудожнєпрофесйнотехнчнеучилище№5мвниця,NaN,https://opendatabot.ua/c/02539890,NaN
3,"Відокремлений структурний підрозділ ""Вінницьки...",0510100000,вдокремленийструктурнийпдроздлвницькийфаховийк...,NaN,https://opendatabot.ua/c/35725833,NaN
4,"Відокремлений структурний підрозділ ""Вінницьки...",0510100000,вдокремленийструктурнийпдроздлвницькийфаховийк...,NaN,https://opendatabot.ua/c/38417484,NaN

In [34]:
unmatched_link.loc[unmatched_link['url_x'] == '', 'url_x'] = unmatched_link.loc[unmatched_link['url_x'] == '', 'url_y']
unmatched_link

,eoname,KOATUU_2020,id,Код ЄДРПОУ,url_x,url_y
0,"ВСП ""Технологічно-промисловий фаховий коледж В...",0510100000,всптехнологчнопромисловийфаховийколеджвницьког...,NaN,https://opendatabot.ua/c/00419667,NaN
1,Вище професійне училище №11 м. Вінниці,0510100000,вищепрофесйнеучилище№11мвниц,NaN,https://opendatabot.ua/c/03065891,NaN
2,Вище художнє професійно-технічне училище №5 м....,0510100000,вищехудожнєпрофесйнотехнчнеучилище№5мвниця,NaN,https://opendatabot.ua/c/02539890,NaN
3,"Відокремлений структурний підрозділ ""Вінницьки...",0510100000,вдокремленийструктурнийпдроздлвницькийфаховийк...,NaN,https://opendatabot.ua/c/35725833,NaN
4,"Відокремлений структурний підрозділ ""Вінницьки...",0510100000,вдокремленийструктурнийпдроздлвницькийфаховийк...,NaN,https://opendatabot.ua/c/38417484,NaN
...,...,...,...,...,...,...
23745,Школа №25 І-ІІІ ступенів Шевченківського район...,8039100000,школа№253ступенвшевченквськогорайонумкиєва,NaN,,
23746,Школа №27 І-ІІІ ступенів Шевченківського район...,8039100000,школа№273ступенвшевченквськогорайонумкиєва,NaN,https://opendatabot.ua/c/26125710,NaN
23747,Школа №70 І-ІІІ ступенів Шевченківського район...,8039100000,школа№703ступенвшевченквськогорайонумкиєва,NaN,https://opendatabot.ua/c/22881828,NaN
23748,Школа №95 І-ІІІ ступенів Шевченківського район...,8039100000,школа№953ступенвшевченквськогорайонумкиєва,NaN,https://opendatabot.ua/c/26125905,NaN
23749,"Лучицький навчально-виховний комплекс ""Загальн...",NaN,лучицькийнавчальновиховнийкомплексзагальноосвт...,NaN,https://opendatabot.ua/c/23947156,NaN

In [36]:
unmatched_link = unmatched_link.drop(columns=['url_y'], axis=1)
unmatched_link = unmatched_link.rename(columns = {'url_x':'url'})
unmatched_link

In [38]:
unmatched_link[unmatched_link.url.apply(lambda x: isinstance(x, str) and len(x.strip())> 0)]

,eoname,KOATUU_2020,id,Код ЄДРПОУ,url
0,"ВСП ""Технологічно-промисловий фаховий коледж В...",0510100000,всптехнологчнопромисловийфаховийколеджвницьког...,NaN,https://opendatabot.ua/c/00419667
1,Вище професійне училище №11 м. Вінниці,0510100000,вищепрофесйнеучилище№11мвниц,NaN,https://opendatabot.ua/c/03065891
2,Вище художнє професійно-технічне училище №5 м....,0510100000,вищехудожнєпрофесйнотехнчнеучилище№5мвниця,NaN,https://opendatabot.ua/c/02539890
3,"Відокремлений структурний підрозділ ""Вінницьки...",0510100000,вдокремленийструктурнийпдроздлвницькийфаховийк...,NaN,https://opendatabot.ua/c/35725833
4,"Відокремлений структурний підрозділ ""Вінницьки...",0510100000,вдокремленийструктурнийпдроздлвницькийфаховийк...,NaN,https://opendatabot.ua/c/38417484
...,...,...,...,...,...
23744,Школа №199 І-ІІІ ступенів Шевченківського райо...,8039100000,школа№1993ступенвшевченквськогорайонумкиєва,NaN,https://opendatabot.ua/c/22881923
23746,Школа №27 І-ІІІ ступенів Шевченківського район...,8039100000,школа№273ступенвшевченквськогорайонумкиєва,NaN,https://opendatabot.ua/c/26125710
23747,Школа №70 І-ІІІ ступенів Шевченківського район...,8039100000,школа№703ступенвшевченквськогорайонумкиєва,NaN,https://opendatabot.ua/c/22881828
23748,Школа №95 І-ІІІ ступенів Шевченківського район...,8039100000,школа№953ступенвшевченквськогорайонумкиєва,NaN,https://opendatabot.ua/c/26125905
23749,"Лучицький навчально-виховний комплекс ""Загальн...",NaN,лучицькийнавчальновиховнийкомплексзагальноосвт...,NaN,https://opendatabot.ua/c/23947156

In [39]:
unmatched_link.to_csv('unmatched_link.csv', index=False)

# Stop here

In [2]:
import pandas as pd

In [3]:
unmatched_link = pd.read_csv('schools_edrpou.csv', dtype=str)
unmatched_link

,eoname,KOATUU_2020,year,KOATUU_2020_reg,id,EDRPOU
0,"ВСП ""Технологічно-промисловий фаховий коледж В...",0510100000,[2022],05,вдокремленийструктурнийпдроздлтехнологчнопроми...,NaN
1,Вище професійне училище №11 м. Вінниці,0510100000,"[2018, 2019, 2020, 2021, 2022]",05,вищепрофесйнеучилище11мвниц,03065891
2,Вище художнє професійно-технічне училище №5 м....,0510100000,"[2018, 2019, 2020, 2021, 2022]",05,вищехудожнєпрофесйнотехнчнеучилище5мвниц,02539890
3,"Відокремлений структурний підрозділ ""Вінницьки...",0510100000,"[2021, 2022]",05,вдокремленийструктурнийпдроздлвницькийколеджна...,35725833
4,"Відокремлений структурний підрозділ ""Вінницьки...",0510100000,"[2021, 2022]",05,вдокремленийструктурнийпдроздлвницькийколеджек...,38417484
...,...,...,...,...,...,...
27505,Школа №25 І-ІІІ ступенів Шевченківського район...,8039100000,"[2016, 2017, 2018, 2019, 2020, 2021]",80,школа253ступшевченквськогорайонумкиєв,22880786
27506,Школа №27 І-ІІІ ступенів Шевченківського район...,8039100000,[2016],80,школа273ступшевченквськогорайонумкиєв,26125710
27507,Школа №70 І-ІІІ ступенів Шевченківського район...,8039100000,[2016],80,школа703ступшевченквськогорайонумкиєв,22881828
27508,Школа №95 І-ІІІ ступенів Шевченківського район...,8039100000,[2017],80,школа953ступшевченквськогорайонумкиєв,26125905
27509,школа І-ІІІ ступенів №175 ім.В Марченка Шевчен...,8039100000,"[2020, 2021, 2022]",80,школа3ступ175менвмарченкашевченквськогорайонум...,26125940

In [4]:
# additional 
unmatched_link = unmatched_link[unmatched_link['EDRPOU'].isna()]
unmatched_link

,eoname,KOATUU_2020,year,KOATUU_2020_reg,id,EDRPOU
0,"ВСП ""Технологічно-промисловий фаховий коледж В...",0510100000,[2022],05,вдокремленийструктурнийпдроздлтехнологчнопроми...,NaN
5,Відокремлений структурний підрозділ «Вінницьки...,0510100000,[2022],05,вдокремленийструктурнийпдроздлвницькийторговел...,NaN
8,Вінницька Установа виконання покарань Управлін...,0510100000,[2016],05,вницькаустановавиконаняпокараньуправлнядержавн...,NaN
9,Вінницька виправна колонія Управління Державно...,0510100000,[2016],05,вницькавиправнаколоняуправлнядержавногодепарта...,NaN
11,Вінницьке відділення Ірпінського державного ко...,0510100000,"[2019, 2020]",05,вницькевддленярпнськогодержавногоколеджуеконом...,NaN
...,...,...,...,...,...,...
27357,Середня загальноосвітня школа №279 імені Петра...,8038900000,"[2016, 2017, 2018, 2019, 2020, 2021, 2022]",80,середнязагальноосвтняшкола279менпетрагригоренк...,NaN
27365,Середня загальноосвітня школа №69 Солом'янсько...,8038900000,"[2016, 2017, 2018, 2019, 2020, 2021, 2022]",80,середнязагальноосвтняшкола69соломянськогорайон...,NaN
27390,Технічний ліцей Національного технічного уніве...,8038900000,"[2016, 2017, 2018, 2019, 2020, 2021, 2022]",80,технчнийлцейнацональноготехнчногоунверситетуук...,NaN
27479,"Товариство з обмеженою відповідальністю ""Франц...",8039100000,"[2016, 2017, 2018, 2019, 2020, 2021, 2022]",80,товариствозобмеженоювдповдальнстюфранцузькийлц...,NaN
27501,Школа №163 І-ІІІ ступенів імені М.Кирпоноса Ше...,8039100000,[2016],80,школа1633ступменменкирпоносашевченквськогорайо...,NaN

In [5]:
unmatched_new = unmatched_link

In [6]:
unmatched_new = unmatched_link[~unmatched_link.url.apply(lambda x: isinstance(x, str) and len(x.strip())> 0)]
unmatched_new

AttributeError: 'DataFrame' object has no attribute 'url'

In [8]:
opendatabot_links_new = []
for eoname in tqdm(unmatched_new['eoname']):
    opendatabot_links_new.append(search_opendatabot(eoname))

100%|██████████| 3318/3318 [2:38:28<00:00,  2.87s/it]

In [9]:
opendatabot_df_new = pd.DataFrame(opendatabot_links_new)
opendatabot_df_new

,eoname,url
0,"ВСП ""Технологічно-промисловий фаховий коледж В...",https://opendatabot.ua/c/00419667
1,Відокремлений структурний підрозділ «Вінницьки...,https://opendatabot.ua/c/40397462
2,Вінницька Установа виконання покарань Управлін...,https://opendatabot.ua/c/08562602
3,Вінницька виправна колонія Управління Державно...,https://opendatabot.ua/c/08562594
4,Вінницьке відділення Ірпінського державного ко...,https://opendatabot.ua/c/35023972
...,...,...
3313,Середня загальноосвітня школа №279 імені Петра...,
3314,Середня загальноосвітня школа №69 Солом'янсько...,
3315,Технічний ліцей Національного технічного уніве...,
3316,"Товариство з обмеженою відповідальністю ""Франц...",
3317,Школа №163 І-ІІІ ступенів імені М.Кирпоноса Ше...,

In [10]:
opendatabot_df_new[opendatabot_df_new.url!='']

,eoname,url
0,"ВСП ""Технологічно-промисловий фаховий коледж В...",https://opendatabot.ua/c/00419667
1,Відокремлений структурний підрозділ «Вінницьки...,https://opendatabot.ua/c/40397462
2,Вінницька Установа виконання покарань Управлін...,https://opendatabot.ua/c/08562602
3,Вінницька виправна колонія Управління Державно...,https://opendatabot.ua/c/08562594
4,Вінницьке відділення Ірпінського державного ко...,https://opendatabot.ua/c/35023972
...,...,...
3295,Генічеська загальноосвітня вечірня (змінна) шк...,https://opendatabot.ua/c/24752437
3308,Середня загальноосвітня школа №328 - загальноо...,https://opendatabot.ua/c/22880935
3309,Спеціалізована школа №181 імені Івана Кудрі,https://opendatabot.ua/c/32492571
3310,"Загальноосвітній навчальний заклад ""Міжнародна...",https://opendatabot.ua/c/24382845
3311,Гімназія біотехнологій №177 Солом'янського рай...,https://opendatabot.ua/c/22880194

In [12]:
opendatabot_df_new[opendatabot_df_new.url!=''].to_csv('unmatched_link2.csv', index=False)

In [10]:
df = unmatched_link.merge(opendatabot_df_new[['url']], left_on=[unmatched_link['eoname']], right_on=[opendatabot_df_new['eoname']], how='left')

df[~df.url_y.isnull()]

AttributeError: 'DataFrame' object has no attribute 'url_y'

In [ ]:
unmatched_link = unmatched_link.merge(opendatabot_df_new[['url']], left_on=[unmatched_link['eoname']], right_on=[opendatabot_df_new['eoname']], how='left')
unmatched_link = unmatched_link.drop(columns = ['key_0'], axis=1)
unmatched_link.head()

,eoname,KOATUU_2020,id,Код ЄДРПОУ,url_x,url_y
0,"ВСП ""Технологічно-промисловий фаховий коледж В...",0510100000,всптехнологчнопромисловийфаховийколеджвницьког...,NaN,https://opendatabot.ua/c/00419667,NaN
1,Вище професійне училище №11 м. Вінниці,0510100000,вищепрофесйнеучилище№11мвниц,NaN,https://opendatabot.ua/c/03065891,NaN
2,Вище художнє професійно-технічне училище №5 м....,0510100000,вищехудожнєпрофесйнотехнчнеучилище№5мвниця,NaN,https://opendatabot.ua/c/02539890,NaN
3,"Відокремлений структурний підрозділ ""Вінницьки...",0510100000,вдокремленийструктурнийпдроздлвницькийфаховийк...,NaN,https://opendatabot.ua/c/35725833,NaN
4,"Відокремлений структурний підрозділ ""Вінницьки...",0510100000,вдокремленийструктурнийпдроздлвницькийфаховийк...,NaN,https://opendatabot.ua/c/38417484,NaN

In [ ]:
unmatched_link.loc[unmatched_link['url_x'].isna(), 'url_x'] = ''

In [ ]:
unmatched_link.loc[unmatched_link['url_x'] == '', 'url_x'] = unmatched_link.loc[unmatched_link['url_x'] == '', 'url_y']
unmatched_link

,eoname,KOATUU_2020,id,Код ЄДРПОУ,url_x,url_y
0,"ВСП ""Технологічно-промисловий фаховий коледж В...",0510100000,всптехнологчнопромисловийфаховийколеджвницьког...,NaN,https://opendatabot.ua/c/00419667,NaN
1,Вище професійне училище №11 м. Вінниці,0510100000,вищепрофесйнеучилище№11мвниц,NaN,https://opendatabot.ua/c/03065891,NaN
2,Вище художнє професійно-технічне училище №5 м....,0510100000,вищехудожнєпрофесйнотехнчнеучилище№5мвниця,NaN,https://opendatabot.ua/c/02539890,NaN
3,"Відокремлений структурний підрозділ ""Вінницьки...",0510100000,вдокремленийструктурнийпдроздлвницькийфаховийк...,NaN,https://opendatabot.ua/c/35725833,NaN
4,"Відокремлений структурний підрозділ ""Вінницьки...",0510100000,вдокремленийструктурнийпдроздлвницькийфаховийк...,NaN,https://opendatabot.ua/c/38417484,NaN
...,...,...,...,...,...,...
22683,Школа №25 І-ІІІ ступенів Шевченківського район...,8039100000,школа№253ступенвшевченквськогорайонумкиєва,NaN,,
22684,Школа №27 І-ІІІ ступенів Шевченківського район...,8039100000,школа№273ступенвшевченквськогорайонумкиєва,NaN,https://opendatabot.ua/c/26125710,NaN
22685,Школа №70 І-ІІІ ступенів Шевченківського район...,8039100000,школа№703ступенвшевченквськогорайонумкиєва,NaN,https://opendatabot.ua/c/22881828,NaN
22686,Школа №95 І-ІІІ ступенів Шевченківського район...,8039100000,школа№953ступенвшевченквськогорайонумкиєва,NaN,https://opendatabot.ua/c/26125905,NaN
22687,"Лучицький навчально-виховний комплекс ""Загальн...",NaN,лучицькийнавчальновиховнийкомплексзагальноосвт...,NaN,https://opendatabot.ua/c/23947156,NaN

In [ ]:
unmatched_link = unmatched_link.drop(columns=['url_y'], axis=1)
unmatched_link = unmatched_link.rename(columns = {'url_x':'url'})
unmatched_link

,eoname,KOATUU_2020,id,Код ЄДРПОУ,url
0,"ВСП ""Технологічно-промисловий фаховий коледж В...",0510100000,всптехнологчнопромисловийфаховийколеджвницьког...,NaN,https://opendatabot.ua/c/00419667
1,Вище професійне училище №11 м. Вінниці,0510100000,вищепрофесйнеучилище№11мвниц,NaN,https://opendatabot.ua/c/03065891
2,Вище художнє професійно-технічне училище №5 м....,0510100000,вищехудожнєпрофесйнотехнчнеучилище№5мвниця,NaN,https://opendatabot.ua/c/02539890
3,"Відокремлений структурний підрозділ ""Вінницьки...",0510100000,вдокремленийструктурнийпдроздлвницькийфаховийк...,NaN,https://opendatabot.ua/c/35725833
4,"Відокремлений структурний підрозділ ""Вінницьки...",0510100000,вдокремленийструктурнийпдроздлвницькийфаховийк...,NaN,https://opendatabot.ua/c/38417484
...,...,...,...,...,...
22683,Школа №25 І-ІІІ ступенів Шевченківського район...,8039100000,школа№253ступенвшевченквськогорайонумкиєва,NaN,
22684,Школа №27 І-ІІІ ступенів Шевченківського район...,8039100000,школа№273ступенвшевченквськогорайонумкиєва,NaN,https://opendatabot.ua/c/26125710
22685,Школа №70 І-ІІІ ступенів Шевченківського район...,8039100000,школа№703ступенвшевченквськогорайонумкиєва,NaN,https://opendatabot.ua/c/22881828
22686,Школа №95 І-ІІІ ступенів Шевченківського район...,8039100000,школа№953ступенвшевченквськогорайонумкиєва,NaN,https://opendatabot.ua/c/26125905
22687,"Лучицький навчально-виховний комплекс ""Загальн...",NaN,лучицькийнавчальновиховнийкомплексзагальноосвт...,NaN,https://opendatabot.ua/c/23947156

In [ ]:
unmatched_link.drop_duplicates(inplace=True)

In [ ]:
unmatched_link.reset_index(drop=True, inplace=True)

In [ ]:
unmatched_link[~unmatched_link.url.apply(lambda x: isinstance(x, str) and len(x.strip())> 0)]

,eoname,KOATUU_2020,id,Код ЄДРПОУ,url
10,Вінницьке відділення Ірпінського державного ко...,0510100000,вницькевддленярпнськогодержавногоколеджуеконом...,NaN,
11,Вінницьке відділення Ірпінського державного ко...,0510100000,вницькевддленярпнськогодержавногоколеджуеконом...,NaN,
13,Вінницький коледж Національного університету х...,0510100000,вницькийколеджнацональногоунверситетухарчовихт...,NaN,
14,Вінницький коледж будівництва і архітектури Ки...,0510100000,вницькийколеджбудвництваархтектурикивськогонац...,NaN,
16,Вінницький коледж економіки та підприємництва ...,0510100000,вницькийколеджекономкитапдприємництватернопльс...,NaN,
...,...,...,...,...,...
22288,Спеціалізована школа №135 І-ІІІ ступенів з пог...,8039100000,спецалзованашкола№1353ступенвзпоглибленимвивче...,NaN,
22304,"Товариство з обмеженою відповідальністю ""Франц...",8039100000,товариствозобмеженоювдповдальнстюфранцузькийлц...,NaN,
22305,"Фаховий коледж Університету ""КРОК""",8039100000,фаховийколеджунверситетукрок,NaN,
22306,Фаховий коледж бізнесу та аналітики Національн...,8039100000,фаховийколеджбзнесутааналтикинацональноакадемс...,NaN,
22315,Школа №25 І-ІІІ ступенів Шевченківського район...,8039100000,школа№253ступенвшевченквськогорайонумкиєва,NaN,

In [ ]:
unmatched_link1 = unmatched_link.copy()

In [ ]:
unmatched_link.to_csv('unmatched_link1.csv',  index=False, encoding='utf-8')

In [ ]:
schools_reg = schools_edrpou_id.merge(schools_data_id[['Код ЄДРПОУ']], left_on=[schools_edrpou_id['id']], right_on=[schools_data_id.id], how='left')
schools_reg = schools_reg.drop(columns = ['key_0'], axis=1)
schools_reg.head()

In [ ]:
schools_reg[schools_reg['Код ЄДРПОУ'].notna()]

In [9]:
# sample 20% for check
unmatched_link[~unmatched_link.url.isna()].sample(4470).to_csv('unmatched_link_test_sample.csv', index=False)

# Youcontrol parser

In [130]:
#!pip install -U duckpy
from duckpy import Client
from tqdm import tqdm
import time
tqdm.pandas()

def search_youcontrol(school_name, max_retry=20):
    """
    Search for school in youcontrol.com.ua
    """
    client = Client()
    opendatabot_url = ''
    retry = 0
    while not opendatabot_url and retry < max_retry:
        try:
            results = client.search(school_name, limit=20)
        except:
            time.sleep(20)
            continue
        for site in results:
            if site['url'].startswith('https://youcontrol.com.ua/catalog/company_details/'):
                opendatabot_url = site['url']
                break
        retry += 1
    return {'eoname': school_name, "url": opendatabot_url}

search_youcontrol('ЄДРПОУ:'+'Вінницьке відділення Ірпінського державного коледжу економіки та права')

{'eoname': 'ЄДРПОУ:Вінницьке відділення Ірпінського державного коледжу економіки та права',
 'url': ''}

In [131]:
unmatched_link = pd.read_csv('unmatched_link1.csv', dtype=str)
unmatched_link

,eoname,KOATUU_2020,id,Код ЄДРПОУ,url
0,"ВСП ""Технологічно-промисловий фаховий коледж В...",0510100000,всптехнологчнопромисловийфаховийколеджвницьког...,NaN,https://opendatabot.ua/c/00419667
1,Вище професійне училище №11 м. Вінниці,0510100000,вищепрофесйнеучилище№11мвниц,NaN,https://opendatabot.ua/c/03065891
2,Вище художнє професійно-технічне училище №5 м....,0510100000,вищехудожнєпрофесйнотехнчнеучилище№5мвниця,NaN,https://opendatabot.ua/c/02539890
3,"Відокремлений структурний підрозділ ""Вінницьки...",0510100000,вдокремленийструктурнийпдроздлвницькийфаховийк...,NaN,https://opendatabot.ua/c/35725833
4,"Відокремлений структурний підрозділ ""Вінницьки...",0510100000,вдокремленийструктурнийпдроздлвницькийфаховийк...,NaN,https://opendatabot.ua/c/38417484
...,...,...,...,...,...
22315,Школа №25 І-ІІІ ступенів Шевченківського район...,8039100000,школа№253ступенвшевченквськогорайонумкиєва,NaN,NaN
22316,Школа №27 І-ІІІ ступенів Шевченківського район...,8039100000,школа№273ступенвшевченквськогорайонумкиєва,NaN,https://opendatabot.ua/c/26125710
22317,Школа №70 І-ІІІ ступенів Шевченківського район...,8039100000,школа№703ступенвшевченквськогорайонумкиєва,NaN,https://opendatabot.ua/c/22881828
22318,Школа №95 І-ІІІ ступенів Шевченківського район...,8039100000,школа№953ступенвшевченквськогорайонумкиєва,NaN,https://opendatabot.ua/c/26125905
22319,"Лучицький навчально-виховний комплекс ""Загальн...",NaN,лучицькийнавчальновиховнийкомплексзагальноосвт...,NaN,https://opendatabot.ua/c/23947156

In [132]:
unmatched_new = unmatched_link[~unmatched_link.url.apply(lambda x: isinstance(x, str) and len(x.strip())> 0)]
unmatched_new

,eoname,KOATUU_2020,id,Код ЄДРПОУ,url
10,Вінницьке відділення Ірпінського державного ко...,0510100000,вницькевддленярпнськогодержавногоколеджуеконом...,NaN,NaN
11,Вінницьке відділення Ірпінського державного ко...,0510100000,вницькевддленярпнськогодержавногоколеджуеконом...,NaN,NaN
13,Вінницький коледж Національного університету х...,0510100000,вницькийколеджнацональногоунверситетухарчовихт...,NaN,NaN
14,Вінницький коледж будівництва і архітектури Ки...,0510100000,вницькийколеджбудвництваархтектурикивськогонац...,NaN,NaN
16,Вінницький коледж економіки та підприємництва ...,0510100000,вницькийколеджекономкитапдприємництватернопльс...,NaN,NaN
...,...,...,...,...,...
22288,Спеціалізована школа №135 І-ІІІ ступенів з пог...,8039100000,спецалзованашкола№1353ступенвзпоглибленимвивче...,NaN,NaN
22304,"Товариство з обмеженою відповідальністю ""Франц...",8039100000,товариствозобмеженоювдповдальнстюфранцузькийлц...,NaN,NaN
22305,"Фаховий коледж Університету ""КРОК""",8039100000,фаховийколеджунверситетукрок,NaN,NaN
22306,Фаховий коледж бізнесу та аналітики Національн...,8039100000,фаховийколеджбзнесутааналтикинацональноакадемс...,NaN,NaN
22315,Школа №25 І-ІІІ ступенів Шевченківського район...,8039100000,школа№253ступенвшевченквськогорайонумкиєва,NaN,NaN

In [133]:
opendatabot_links_new = []
for eoname in tqdm(unmatched_new['eoname']):
    opendatabot_links_new.append(search_youcontrol(eoname))

100%|██████████| 3865/3865 [4:40:34<00:00,  4.36s/it]

In [134]:
opendatabot_df_new = pd.DataFrame(opendatabot_links_new)
opendatabot_df_new

,eoname,url
0,Вінницьке відділення Ірпінського державного ко...,
1,Вінницьке відділення Ірпінського державного ко...,
2,Вінницький коледж Національного університету х...,
3,Вінницький коледж будівництва і архітектури Ки...,
4,Вінницький коледж економіки та підприємництва ...,
...,...,...
3860,Спеціалізована школа №135 І-ІІІ ступенів з пог...,https://opendatabot.ua/c/26125779
3861,"Товариство з обмеженою відповідальністю ""Франц...",
3862,"Фаховий коледж Університету ""КРОК""",
3863,Фаховий коледж бізнесу та аналітики Національн...,
3864,Школа №25 І-ІІІ ступенів Шевченківського район...,

In [135]:
opendatabot_df_new[opendatabot_df_new.url!='']

,eoname,url
69,Барська загальноосвітня школа I-III ступенів №...,https://opendatabot.ua/c/21724083
84,Каришківська загальноосвітня школа I-III ступенів,https://opendatabot.ua/c/13337801
100,Осіївська загальноосвітня школа I-III ступенів,https://opendatabot.ua/c/26228290
101,П'ятківська загальноосвітня школа I-III ступенів,https://opendatabot.ua/c/26228278
116,"Комунальний заклад ""Мізяківсько-Хутірський нав...",https://opendatabot.ua/c/26242150
...,...,...
3775,Спеціалізована школа №210 загальноосвітній нав...,https://opendatabot.ua/c/22880906
3789,Комунальний вищий навчальний заклад Київської ...,https://opendatabot.ua/c/02214938
3790,Комунальний заклад вищої освіти Київської обла...,https://opendatabot.ua/c/02214938
3804,Київське вище професійне училище будівництва і...,https://opendatabot.ua/c/05536739
3860,Спеціалізована школа №135 І-ІІІ ступенів з пог...,https://opendatabot.ua/c/26125779

In [136]:
df = unmatched_link.merge(opendatabot_df_new[['url']], left_on=[unmatched_link['eoname']], right_on=[opendatabot_df_new['eoname']], how='left')

df[~df.url_y.isnull()]

,key_0,eoname,KOATUU_2020,id,Код ЄДРПОУ,url_x,url_y
10,Вінницьке відділення Ірпінського державного ко...,Вінницьке відділення Ірпінського державного ко...,0510100000,вницькевддленярпнськогодержавногоколеджуеконом...,NaN,NaN,
11,Вінницьке відділення Ірпінського державного ко...,Вінницьке відділення Ірпінського державного ко...,0510100000,вницькевддленярпнськогодержавногоколеджуеконом...,NaN,NaN,
13,Вінницький коледж Національного університету х...,Вінницький коледж Національного університету х...,0510100000,вницькийколеджнацональногоунверситетухарчовихт...,NaN,NaN,
14,Вінницький коледж будівництва і архітектури Ки...,Вінницький коледж будівництва і архітектури Ки...,0510100000,вницькийколеджбудвництваархтектурикивськогонац...,NaN,NaN,
16,Вінницький коледж економіки та підприємництва ...,Вінницький коледж економіки та підприємництва ...,0510100000,вницькийколеджекономкитапдприємництватернопльс...,NaN,NaN,
...,...,...,...,...,...,...,...
22622,Спеціалізована школа №135 І-ІІІ ступенів з пог...,Спеціалізована школа №135 І-ІІІ ступенів з пог...,8039100000,спецалзованашкола№1353ступенвзпоглибленимвивче...,NaN,NaN,https://opendatabot.ua/c/26125779
22638,"Товариство з обмеженою відповідальністю ""Франц...","Товариство з обмеженою відповідальністю ""Франц...",8039100000,товариствозобмеженоювдповдальнстюфранцузькийлц...,NaN,NaN,
22639,"Фаховий коледж Університету ""КРОК""","Фаховий коледж Університету ""КРОК""",8039100000,фаховийколеджунверситетукрок,NaN,NaN,
22640,Фаховий коледж бізнесу та аналітики Національн...,Фаховий коледж бізнесу та аналітики Національн...,8039100000,фаховийколеджбзнесутааналтикинацональноакадемс...,NaN,NaN,
22649,Школа №25 І-ІІІ ступенів Шевченківського район...,Школа №25 І-ІІІ ступенів Шевченківського район...,8039100000,школа№253ступенвшевченквськогорайонумкиєва,NaN,NaN,

In [137]:
unmatched_link = unmatched_link.merge(opendatabot_df_new[['url']], left_on=[unmatched_link['eoname']], right_on=[opendatabot_df_new['eoname']], how='left')
unmatched_link = unmatched_link.drop(columns = ['key_0'], axis=1)
unmatched_link.head()

,eoname,KOATUU_2020,id,Код ЄДРПОУ,url_x,url_y
0,"ВСП ""Технологічно-промисловий фаховий коледж В...",0510100000,всптехнологчнопромисловийфаховийколеджвницьког...,NaN,https://opendatabot.ua/c/00419667,NaN
1,Вище професійне училище №11 м. Вінниці,0510100000,вищепрофесйнеучилище№11мвниц,NaN,https://opendatabot.ua/c/03065891,NaN
2,Вище художнє професійно-технічне училище №5 м....,0510100000,вищехудожнєпрофесйнотехнчнеучилище№5мвниця,NaN,https://opendatabot.ua/c/02539890,NaN
3,"Відокремлений структурний підрозділ ""Вінницьки...",0510100000,вдокремленийструктурнийпдроздлвницькийфаховийк...,NaN,https://opendatabot.ua/c/35725833,NaN
4,"Відокремлений структурний підрозділ ""Вінницьки...",0510100000,вдокремленийструктурнийпдроздлвницькийфаховийк...,NaN,https://opendatabot.ua/c/38417484,NaN

In [138]:
unmatched_link.loc[unmatched_link['url_x'].isna(), 'url_x'] = ''

In [139]:
unmatched_link.loc[unmatched_link['url_x'] == '', 'url_x'] = unmatched_link.loc[unmatched_link['url_x'] == '', 'url_y']
unmatched_link

,eoname,KOATUU_2020,id,Код ЄДРПОУ,url_x,url_y
0,"ВСП ""Технологічно-промисловий фаховий коледж В...",0510100000,всптехнологчнопромисловийфаховийколеджвницьког...,NaN,https://opendatabot.ua/c/00419667,NaN
1,Вище професійне училище №11 м. Вінниці,0510100000,вищепрофесйнеучилище№11мвниц,NaN,https://opendatabot.ua/c/03065891,NaN
2,Вище художнє професійно-технічне училище №5 м....,0510100000,вищехудожнєпрофесйнотехнчнеучилище№5мвниця,NaN,https://opendatabot.ua/c/02539890,NaN
3,"Відокремлений структурний підрозділ ""Вінницьки...",0510100000,вдокремленийструктурнийпдроздлвницькийфаховийк...,NaN,https://opendatabot.ua/c/35725833,NaN
4,"Відокремлений структурний підрозділ ""Вінницьки...",0510100000,вдокремленийструктурнийпдроздлвницькийфаховийк...,NaN,https://opendatabot.ua/c/38417484,NaN
...,...,...,...,...,...,...
22649,Школа №25 І-ІІІ ступенів Шевченківського район...,8039100000,школа№253ступенвшевченквськогорайонумкиєва,NaN,,
22650,Школа №27 І-ІІІ ступенів Шевченківського район...,8039100000,школа№273ступенвшевченквськогорайонумкиєва,NaN,https://opendatabot.ua/c/26125710,NaN
22651,Школа №70 І-ІІІ ступенів Шевченківського район...,8039100000,школа№703ступенвшевченквськогорайонумкиєва,NaN,https://opendatabot.ua/c/22881828,NaN
22652,Школа №95 І-ІІІ ступенів Шевченківського район...,8039100000,школа№953ступенвшевченквськогорайонумкиєва,NaN,https://opendatabot.ua/c/26125905,NaN
22653,"Лучицький навчально-виховний комплекс ""Загальн...",NaN,лучицькийнавчальновиховнийкомплексзагальноосвт...,NaN,https://opendatabot.ua/c/23947156,NaN

In [140]:
unmatched_link = unmatched_link.drop(columns=['url_y'], axis=1)
unmatched_link = unmatched_link.rename(columns = {'url_x':'url'})
unmatched_link

,eoname,KOATUU_2020,id,Код ЄДРПОУ,url
0,"ВСП ""Технологічно-промисловий фаховий коледж В...",0510100000,всптехнологчнопромисловийфаховийколеджвницьког...,NaN,https://opendatabot.ua/c/00419667
1,Вище професійне училище №11 м. Вінниці,0510100000,вищепрофесйнеучилище№11мвниц,NaN,https://opendatabot.ua/c/03065891
2,Вище художнє професійно-технічне училище №5 м....,0510100000,вищехудожнєпрофесйнотехнчнеучилище№5мвниця,NaN,https://opendatabot.ua/c/02539890
3,"Відокремлений структурний підрозділ ""Вінницьки...",0510100000,вдокремленийструктурнийпдроздлвницькийфаховийк...,NaN,https://opendatabot.ua/c/35725833
4,"Відокремлений структурний підрозділ ""Вінницьки...",0510100000,вдокремленийструктурнийпдроздлвницькийфаховийк...,NaN,https://opendatabot.ua/c/38417484
...,...,...,...,...,...
22649,Школа №25 І-ІІІ ступенів Шевченківського район...,8039100000,школа№253ступенвшевченквськогорайонумкиєва,NaN,
22650,Школа №27 І-ІІІ ступенів Шевченківського район...,8039100000,школа№273ступенвшевченквськогорайонумкиєва,NaN,https://opendatabot.ua/c/26125710
22651,Школа №70 І-ІІІ ступенів Шевченківського район...,8039100000,школа№703ступенвшевченквськогорайонумкиєва,NaN,https://opendatabot.ua/c/22881828
22652,Школа №95 І-ІІІ ступенів Шевченківського район...,8039100000,школа№953ступенвшевченквськогорайонумкиєва,NaN,https://opendatabot.ua/c/26125905
22653,"Лучицький навчально-виховний комплекс ""Загальн...",NaN,лучицькийнавчальновиховнийкомплексзагальноосвт...,NaN,https://opendatabot.ua/c/23947156

In [141]:
unmatched_link.drop_duplicates(inplace=True)

In [142]:
unmatched_link.reset_index(drop=True, inplace=True)

In [143]:
unmatched_link[~unmatched_link.url.apply(lambda x: isinstance(x, str) and len(x.strip())> 0)]

,eoname,KOATUU_2020,id,Код ЄДРПОУ,url
10,Вінницьке відділення Ірпінського державного ко...,0510100000,вницькевддленярпнськогодержавногоколеджуеконом...,NaN,
11,Вінницьке відділення Ірпінського державного ко...,0510100000,вницькевддленярпнськогодержавногоколеджуеконом...,NaN,
13,Вінницький коледж Національного університету х...,0510100000,вницькийколеджнацональногоунверситетухарчовихт...,NaN,
14,Вінницький коледж будівництва і архітектури Ки...,0510100000,вницькийколеджбудвництваархтектурикивськогонац...,NaN,
16,Вінницький коледж економіки та підприємництва ...,0510100000,вницькийколеджекономкитапдприємництватернопльс...,NaN,
...,...,...,...,...,...
22283,Коледж мистецтв та дизайну Київського націонал...,8039100000,коледжмистецтвтадизайнукивськогонацональногоун...,NaN,
22310,"Товариство з обмеженою відповідальністю ""Франц...",8039100000,товариствозобмеженоювдповдальнстюфранцузькийлц...,NaN,
22311,"Фаховий коледж Університету ""КРОК""",8039100000,фаховийколеджунверситетукрок,NaN,
22312,Фаховий коледж бізнесу та аналітики Національн...,8039100000,фаховийколеджбзнесутааналтикинацональноакадемс...,NaN,
22321,Школа №25 І-ІІІ ступенів Шевченківського район...,8039100000,школа№253ступенвшевченквськогорайонумкиєва,NaN,

In [144]:
unmatched_link1 = unmatched_link.copy()

In [146]:
unmatched_link.to_csv('unmatched_link1.csv',  index=False, encoding='utf-8')

# One school on KOATUU_2020

In [ ]:
# where one school on KOATUU_2020
df_one = unmatched.drop(columns=['id','Код ЄДРПОУ']).reset_index(drop=True)
df_one.head()

In [ ]:
schools_data_one = schools_data_id.groupby(by=['Код КОАТУУ']).agg(
    {
        "Повна назва": lambda x: len(x.unique()),
    }
).reset_index()

schools_data_one = pd.DataFrame(schools_data_one[schools_data_one['Повна назва'] == 1]['Код КОАТУУ'])
schools_data_one.head()

In [ ]:
schools_data_one = schools_data_one.merge(schools_data_id, on='Код КОАТУУ', how='inner')

In [ ]:
schools_data_one = schools_data_one[['Код КОАТУУ', 'Повна назва', 'Код ЄДРПОУ']]
schools_data_one.head()

In [ ]:
df_one = df_one.merge(schools_data_one, how='inner', left_on='KOATUU_2020', right_on='Код КОАТУУ')
df_one = df_one.drop(columns=['Код КОАТУУ'])
df_one

In [ ]:
# save
df_one.to_csv('school_one_fuzzymatch.csv', index=False)

# Match unmatched schools with schools

In [198]:
df = pd.read_csv('unmatched_schools_edrpou_bot.csv')
df.head()

,eoname,KOATUU_2020,year,id,EDRPOU,KOATUU_2020_reg
0,"ВСП ""Технологічно-промисловий фаховий коледж В...",510100000,[2022],вдокремленийструктурнийпдроздлтехнологчнопроми...,NaN,5
1,Вище професійне училище №11 м. Вінниці,510100000,"[2018, 2019, 2020, 2021, 2022]",вищепрофесйнеучилище11мвниц,NaN,5
2,Вище художнє професійно-технічне училище №5 м....,510100000,"[2018, 2019, 2020, 2021, 2022]",вищехудожнєпрофесйнотехнчнеучилище5мвниця,NaN,5
3,Відокремлений структурний підрозділ «Вінницьки...,510100000,[2022],вдокремленийструктурнийпдроздлвницькийторговел...,NaN,5
4,Відокремлений структурний підрозділ Вінницький...,510100000,"[2021, 2022]",вдокремленийструктурнийпдроздлвницькийколеджбу...,NaN,5

In [199]:
df.shape

(8188, 6)

In [200]:
df = df[df['Код ЄДРПОУ'].isna()]
df = df.drop(columns=['Код ЄДРПОУ'])
df

KeyError: 'Код ЄДРПОУ'

In [201]:
df_link = pd.read_csv('unmatched_link1.csv')
df_link = df_link[:22325] # delete bad row without KOATUU_2020

In [202]:
df_link['KOATUU_2020'] = df_link['KOATUU_2020'].astype(int)
df_link

,eoname,KOATUU_2020,id,Код ЄДРПОУ,url
0,"ВСП ""Технологічно-промисловий фаховий коледж В...",510100000,всптехнологчнопромисловийфаховийколеджвницьког...,NaN,https://opendatabot.ua/c/00419667
1,Вище професійне училище №11 м. Вінниці,510100000,вищепрофесйнеучилище№11мвниц,NaN,https://opendatabot.ua/c/03065891
2,Вище художнє професійно-технічне училище №5 м....,510100000,вищехудожнєпрофесйнотехнчнеучилище№5мвниця,NaN,https://opendatabot.ua/c/02539890
3,"Відокремлений структурний підрозділ ""Вінницьки...",510100000,вдокремленийструктурнийпдроздлвницькийфаховийк...,NaN,https://opendatabot.ua/c/35725833
4,"Відокремлений структурний підрозділ ""Вінницьки...",510100000,вдокремленийструктурнийпдроздлвницькийфаховийк...,NaN,https://opendatabot.ua/c/38417484
...,...,...,...,...,...
22320,Школа №199 І-ІІІ ступенів Шевченківського райо...,8039100000,школа№1993ступенвшевченквськогорайонумкиєва,NaN,https://opendatabot.ua/c/22881923
22321,Школа №25 І-ІІІ ступенів Шевченківського район...,8039100000,школа№253ступенвшевченквськогорайонумкиєва,NaN,NaN
22322,Школа №27 І-ІІІ ступенів Шевченківського район...,8039100000,школа№273ступенвшевченквськогорайонумкиєва,NaN,https://opendatabot.ua/c/26125710
22323,Школа №70 І-ІІІ ступенів Шевченківського район...,8039100000,школа№703ступенвшевченквськогорайонумкиєва,NaN,https://opendatabot.ua/c/22881828
22324,Школа №95 І-ІІІ ступенів Шевченківського район...,8039100000,школа№953ступенвшевченквськогорайонумкиєва,NaN,https://opendatabot.ua/c/26125905

In [203]:
df_link = df_link[df_link['url'].notna()]
df_link

,eoname,KOATUU_2020,id,Код ЄДРПОУ,url
0,"ВСП ""Технологічно-промисловий фаховий коледж В...",510100000,всптехнологчнопромисловийфаховийколеджвницьког...,NaN,https://opendatabot.ua/c/00419667
1,Вище професійне училище №11 м. Вінниці,510100000,вищепрофесйнеучилище№11мвниц,NaN,https://opendatabot.ua/c/03065891
2,Вище художнє професійно-технічне училище №5 м....,510100000,вищехудожнєпрофесйнотехнчнеучилище№5мвниця,NaN,https://opendatabot.ua/c/02539890
3,"Відокремлений структурний підрозділ ""Вінницьки...",510100000,вдокремленийструктурнийпдроздлвницькийфаховийк...,NaN,https://opendatabot.ua/c/35725833
4,"Відокремлений структурний підрозділ ""Вінницьки...",510100000,вдокремленийструктурнийпдроздлвницькийфаховийк...,NaN,https://opendatabot.ua/c/38417484
...,...,...,...,...,...
22319,Школа №175 І-ІІІ ступенів Шевченківського райо...,8039100000,школа№1753ступенвшевченквськогорайонумкиєва,NaN,https://opendatabot.ua/c/26125940
22320,Школа №199 І-ІІІ ступенів Шевченківського райо...,8039100000,школа№1993ступенвшевченквськогорайонумкиєва,NaN,https://opendatabot.ua/c/22881923
22322,Школа №27 І-ІІІ ступенів Шевченківського район...,8039100000,школа№273ступенвшевченквськогорайонумкиєва,NaN,https://opendatabot.ua/c/26125710
22323,Школа №70 І-ІІІ ступенів Шевченківського район...,8039100000,школа№703ступенвшевченквськогорайонумкиєва,NaN,https://opendatabot.ua/c/22881828
22324,Школа №95 І-ІІІ ступенів Шевченківського район...,8039100000,школа№953ступенвшевченквськогорайонумкиєва,NaN,https://opendatabot.ua/c/26125905

In [204]:
df_new = df.merge(df_link[['eoname', 'KOATUU_2020','url']], left_on=['eoname', 'KOATUU_2020'], right_on=['eoname', 'KOATUU_2020'], how='inner').drop_duplicates()

In [205]:
len(df[['eoname','KOATUU_2020']].drop_duplicates()), len(df['eoname'])

(8188, 8188)

In [206]:
df_new[df_new.duplicated(subset=['eoname','KOATUU_2020'], keep=False)]

,eoname,KOATUU_2020,year,id,EDRPOU,KOATUU_2020_reg,url
451,Загальноосвітня школа І-ІІІ ступеня с. Городищ...,722880706,[2016],загальноосвтняшкола3ступсгородище2луцькогорайо...,NaN,7,https://opendatabot.ua/c/23018994
452,Загальноосвітня школа І-ІІІ ступеня с. Городищ...,722880706,[2016],загальноосвтняшкола3ступсгородище2луцькогорайо...,NaN,7,https://opendatabot.ua/c/23018913
454,Загальноосвітня школа І-ІІІ ступеня с. Городищ...,722881701,[2016],загальноосвтняшкола3ступсгородище2луцькогорайо...,NaN,7,https://opendatabot.ua/c/23018994
455,Загальноосвітня школа І-ІІІ ступеня с. Городищ...,722881701,[2016],загальноосвтняшкола3ступсгородище2луцькогорайо...,NaN,7,https://opendatabot.ua/c/23018913
877,Мар'ївська загальноосвітня школа І-ІІІ ступені...,1225283304,"[2016, 2017, 2018, 2019, 2020, 2021]",марвськазагальноосвтняшкола3ступ2софвськорайон...,NaN,12,https://opendatabot.ua/c/23545340
...,...,...,...,...,...,...,...
4419,Кременецька загальноосвітня школа - інтернат І...,6123486202,[2018],кременецьказагальноосвтняшколантернат3ступ,NaN,61,https://opendatabot.ua/c/23591073
4539,І-Іванівська загальноосвітня школа I-III ступе...,6320481504,"[2016, 2017, 2020, 2021]",ванвськазагальноосвтняшкола3ступбарвнквськорай...,NaN,63,https://opendatabot.ua/c/25791362
4540,І-Іванівська загальноосвітня школа I-III ступе...,6320481504,"[2016, 2017, 2020, 2021]",ванвськазагальноосвтняшкола3ступбарвнквськорай...,NaN,63,https://opendatabot.ua/c/25791391
4542,І-Іванівська загальноосвітня школа I-III ступе...,6320483501,"[2016, 2017, 2020, 2021]",ванвськазагальноосвтняшкола3ступбарвнквськорай...,NaN,63,https://opendatabot.ua/c/25791362
4543,І-Іванівська загальноосвітня школа I-III ступе...,6320483501,"[2016, 2017, 2020, 2021]",ванвськазагальноосвтняшкола3ступбарвнквськорай...,NaN,63,https://opendatabot.ua/c/25791391

In [194]:
13977+67

14044

In [207]:
df_new.to_csv('unm_schools_with_links.csv', index=False)

In [ ]:
schools_edrpou_loc = schools_edrpou.merge(locations[['KOATUU_2020']], left_on=[schools_edrpou['eoregname'],schools_edrpou['eoareaname'], schools_edrpou['eotername']], right_on=[locations['regname'],locations['areaname'], locations['tername']], how='left')
schools_edrpou_loc = schools_edrpou_loc.drop(columns = ['key_0', 'key_1', 'key_2'], axis=1)