In [1]:
import pandas as pd
import json
from deep_translator import GoogleTranslator

In [2]:
zno_orig = pd.read_csv('school_dataset_sample.csv')
translate_features = ['eoname', 'eotypename_min', 'eoregname_min',
                      'eoareaname_min', 'eotername_min', 'eoparent_min']
translator_google = GoogleTranslator(source='uk', target='en')

/home/olha/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3331: DtypeWarning: Columns (293) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [3]:
zno_orig.head()

,eoname,year,sexM,sexF,phys_mat,foreign_phyl,universal,ukr_phyl,technology,bio_phys,...,"Разом кількість учнів, та дітей, які здобувають дошкільну освіту","Видатки на функціонування закладу (загальний фонд), тис.грн.\n2019 рік (касові видатки)","Видатки на функціонування закладу (загальний фонд), тис.грн.\n2020 рік (план)","Питома вага непедагогічного персоналу у загальній кількості працівників, %","Питома вага педагогічних працівників пенсійного віку у загальній кількості педагогічних працівників, %","Фактична наповнюваність класів, учнів на клас","Видатки на функціонування закладу (загальний фонд), тис.грн.\n2020 рік (касові видатки)","Видатки на функціонування закладу (загальний фонд), тис.грн.\n2021 рік (план)","Видатки на 1 учня, 2020, тис. грн.","Видатки на 1 клас, тис. грн. 2020 рік (каса)"
0,"""Демино-Олександрівський ліцей Троїцької селищ...",2019,3,5,0,0,8,0,0,0,...,59.0,3468.816,4066.48,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"""Демино-Олександрівський ліцей Троїцької селищ...",2020,6,3,0,0,9,0,0,0,...,NaN,NaN,NaN,0.285714,0.133333,7.750000,3620.1,4862.1,58.388710,452.512500
2,"""Лантратівський ліцей Троїцької селищної ради ...",2019,8,4,0,0,12,0,0,0,...,95.0,4170.501,4652.336,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"""Лантратівський ліцей Троїцької селищної ради ...",2020,2,2,0,0,4,0,0,0,...,NaN,NaN,NaN,0.346154,0.235294,8.727273,4298.7,5290.8,44.778125,390.790909
4,"""Навчально-виховний комплекс ""Школа І-ІІ ступе...",2019,23,21,0,20,0,0,0,0,...,778.0,18463.070,28107.648,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
zno_orig.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18637 entries, 0 to 18636
Columns: 301 entries, eoname to Видатки на 1 клас, тис. грн. 2020 рік (каса)
dtypes: float64(148), int64(145), object(8)
memory usage: 42.8+ MB

In [5]:
zno_orig.columns.to_series().groupby(zno_orig.dtypes).groups

{int64: ['year', 'sexM', 'sexF', 'phys_mat', 'foreign_phyl', 'universal', 'ukr_phyl', 'technology', 'bio_phys', 'economy', 'history', 'sport', 'math', 'law', 'other', 'martial_sport', 'philosophy', 'ecology', 'arts', 'geography', 'physics', 'chem_tech', 'biology', 'phys_chem', 'young_spec', 'qual_work', 'hung_lang_max', 'ukr_lang_max', 'rus_lang_max', 'roman_lang_max', 'pol_lang_max', 'mold_lang_max', 'other_lang_max', 'ukrtest_count', 'ukr_accept', 'ukr_fail', 'ukr_abscent', 'ukr_annul', 'ukr_no_choice', 'histtest_count', 'hist_ukrlang', 'hist_ruslang', 'hist_moldlang', 'hist_hunglang', 'hist_romlang', 'hist_pollang', 'hist_accept', 'hist_fail', 'hist_abscent', 'hist_annul', 'hist_no_choice', 'mathtest_count', 'math_ukrlang', 'math_ruslang', 'math_moldlang', 'math_hunglang', 'math_romlang', 'math_pollang', 'math_accept', 'math_fail', 'math_abscent', 'math_annul', 'math_no_choice', 'phystest_count', 'phys_ukrlang', 'phys_ruslang', 'phys_moldlang', 'phys_hunglang', 'phys_romlang', 'phys_pollang', 'phys_accept', 'phys_fail', 'phys_abscent', 'phys_annul', 'phys_no_choice', 'chemtest_count', 'chem_ukrlang', 'chem_ruslang', 'chem_moldlang', 'chem_hunglang', 'chem_romlang', 'chem_pollang', 'chem_accept', 'chem_fail', 'chem_abscent', 'chem_annul', 'chem_no_choice', 'biotest_count', 'bio_ukrlang', 'bio_ruslang', 'bio_moldlang', 'bio_hunglang', 'bio_romlang', 'bio_pollang', 'bio_accept', 'bio_fail', 'bio_abscent', 'bio_annul', 'bio_no_choice', 'geotest_count', ...], float64: ['ukrball100_min', 'ukrball100_max', 'ukrball100_q25', 'ukrball100_q50', 'ukrball100_q75', 'ukrball100_mean', 'ukrball_min', 'ukrball_max', 'ukrball_q25', 'ukrball_q50', 'ukrball_q75', 'ukrball_mean', 'histball100_min', 'histball100_max', 'histball100_q25', 'histball100_q50', 'histball100_q75', 'histball100_mean', 'histball_min', 'histball_max', 'histball_q25', 'histball_q50', 'histball_q75', 'histball_mean', 'mathball100_min', 'mathball100_max', 'mathball100_q25', 'mathball100_q50', 'mathball100_q75', 'mathball100_mean', 'mathball_min', 'mathball_max', 'mathball_q25', 'mathball_q50', 'mathball_q75', 'mathball_mean', 'physball100_min', 'physball100_max', 'physball100_q25', 'physball100_q50', 'physball100_q75', 'physball100_mean', 'physball_min', 'physball_max', 'physball_q25', 'physball_q50', 'physball_q75', 'physball_mean', 'chemball100_min', 'chemball100_max', 'chemball100_q25', 'chemball100_q50', 'chemball100_q75', 'chemball100_mean', 'chemball_min', 'chemball_max', 'chemball_q25', 'chemball_q50', 'chemball_q75', 'chemball_mean', 'bioball100_min', 'bioball100_max', 'bioball100_q25', 'bioball100_q50', 'bioball100_q75', 'bioball100_mean', 'bioball_min', 'bioball_max', 'bioball_q25', 'bioball_q50', 'bioball_q75', 'bioball_mean', 'geoball100_min', 'geoball100_max', 'geoball100_q25', 'geoball100_q50', 'geoball100_q75', 'geoball100_mean', 'geoball_min', 'geoball_max', 'geoball_q25', 'geoball_q50', 'geoball_q75', 'geoball_mean', 'engball100_min', 'engball100_max', 'engball100_q25', 'engball100_q50', 'engball100_q75', 'engball100_mean', 'engball_min', 'engball_max', 'engball_q25', 'engball_q50', 'engball_q75', 'engball_mean', 'fraball100_min', 'fraball100_max', 'fraball100_q25', 'fraball100_q50', ...], object: ['eoname', 'eotypename_min', 'eoregname_min', 'eoareaname_min', 'eotername_min', 'eoparent_min', 'Ступінь закладу ( I, I-II, I-III)', 'Видатки на функціонування закладу (загальний фонд), тис.грн.
2020 рік (план)']}

In [6]:
column_names = list(zno_orig.columns)
column_names_ukr = column_names[282:]

In [7]:
translated_column_names = {}
for name in column_names_ukr:
    translated_column_names[name] = translator_google.translate(name)

In [8]:
translated_column_names

{'Ступінь закладу ( I, I-II, I-III)': 'Degree of institution (I, I-II, I-III)',
 'Кількість штатних працівників педагогічного персоналу  разом': 'The total number of full-time teaching staff',
 'Кількість штатних працівників непедагогічного персоналу  разом': 'The total number of full-time non-teaching staff',
 'Кількість штатних працівників педагогічного персоналу  пенсійного віку': 'The number of full-time teaching staff of retirement age',
 'Кількість учнів разом': 'The total number of students',
 'Кількість класів разом': 'Number of classes together',
 'Видатки на функціонування закладу (загальний фонд), тис.грн.\n2018рік (касові видатки)': 'Expenses for the functioning of the institution (general fund), thousand hryvnias.\n2018 (cash expenses)',
 'Видатки на функціонування закладу (загальний фонд), тис.грн.\n2019 рік (план)': 'Expenses for the functioning of the institution (general fund), thousand hryvnias.\n2019 (plan)',
 'Видатки на 1 клас, тис. грн.** 2018 рік (каса)': 'Expenses for 1st class, thousand UAH** 2018 (cash register)',
 'Разом кількість учнів, та дітей, які здобувають дошкільну освіту': 'Total number of students and children receiving preschool education',
 'Видатки на функціонування закладу (загальний фонд), тис.грн.\n2019 рік (касові видатки)': 'Expenses for the functioning of the institution (general fund), thousand hryvnias.\n2019 (cash expenses)',
 'Видатки на функціонування закладу (загальний фонд), тис.грн.\n2020 рік (план)': 'Expenses for the functioning of the institution (general fund), thousand hryvnias.\n2020 (plan)',
 'Питома вага непедагогічного персоналу у загальній кількості працівників, %': 'Specific weight of non-teaching staff in the total number of employees, %',
 'Питома вага педагогічних працівників пенсійного віку у загальній кількості педагогічних працівників, %': 'The specific weight of pedagogical workers of retirement age in the total number of pedagogical workers, %',
 'Фактична наповнюваність класів, учнів на клас': 'The actual number of classes, students per class',
 'Видатки на функціонування закладу (загальний фонд), тис.грн.\n2020 рік (касові видатки)': 'Expenses for the functioning of the institution (general fund), thousand hryvnias.\n2020 (cash expenses)',
 'Видатки на функціонування закладу (загальний фонд), тис.грн.\n2021 рік (план)': 'Expenses for the functioning of the institution (general fund), thousand hryvnias.\n2021 (plan)',
 'Видатки на 1 учня, 2020, тис. грн.': 'Expenditures for 1 student, 2020, thousand UAH.',
 'Видатки на 1 клас, тис. грн. 2020 рік (каса)': 'Expenses for 1st class, thousand UAH. 2020 (box office)'}

In [9]:
zno_orig = zno_orig.rename(columns=translated_column_names)
zno_orig.head()

,eoname,year,sexM,sexF,phys_mat,foreign_phyl,universal,ukr_phyl,technology,bio_phys,...,Total number of students and children receiving preschool education,"Expenses for the functioning of the institution (general fund), thousand hryvnias.\n2019 (cash expenses)","Expenses for the functioning of the institution (general fund), thousand hryvnias.\n2020 (plan)","Specific weight of non-teaching staff in the total number of employees, %","The specific weight of pedagogical workers of retirement age in the total number of pedagogical workers, %","The actual number of classes, students per class","Expenses for the functioning of the institution (general fund), thousand hryvnias.\n2020 (cash expenses)","Expenses for the functioning of the institution (general fund), thousand hryvnias.\n2021 (plan)","Expenditures for 1 student, 2020, thousand UAH.","Expenses for 1st class, thousand UAH. 2020 (box office)"
0,"""Демино-Олександрівський ліцей Троїцької селищ...",2019,3,5,0,0,8,0,0,0,...,59.0,3468.816,4066.48,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"""Демино-Олександрівський ліцей Троїцької селищ...",2020,6,3,0,0,9,0,0,0,...,NaN,NaN,NaN,0.285714,0.133333,7.750000,3620.1,4862.1,58.388710,452.512500
2,"""Лантратівський ліцей Троїцької селищної ради ...",2019,8,4,0,0,12,0,0,0,...,95.0,4170.501,4652.336,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"""Лантратівський ліцей Троїцької селищної ради ...",2020,2,2,0,0,4,0,0,0,...,NaN,NaN,NaN,0.346154,0.235294,8.727273,4298.7,5290.8,44.778125,390.790909
4,"""Навчально-виховний комплекс ""Школа І-ІІ ступе...",2019,23,21,0,20,0,0,0,0,...,778.0,18463.070,28107.648,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
translated_columns = []
for feature in translate_features:
    to_tr = zno_orig[feature].unique()
    print("translating", feature, len(to_tr))
    translated_google = {}
    for el in to_tr:
        if not pd.isnull(el):
            translated_google[el] = translator_google.translate(el)
    translated_columns.append(translated_google)

translating eoname 9499
translating eotypename_min 8
translating eoregname_min 25
translating eoareaname_min 682
translating eotername_min 4919
translating eoparent_min 1730

In [12]:
len(translated_columns)

6

In [13]:
for feat_i in range(len(translate_features)):
    print("translating", translate_features[feat_i], len(zno_orig[translate_features[feat_i]].unique()))
    for i in range(0, len(translated_columns[feat_i]) + 1, 1000):
        tr_now = dict(list(translated_columns[feat_i].items())[i:i+1000])
        zno_orig.replace({translate_features[feat_i]: tr_now}, inplace=True)
    print(len(zno_orig[translate_features[feat_i]].unique()))

translating eoname 9499
9431
translating eotypename_min 8
8
translating eoregname_min 25
25
translating eoareaname_min 682
682
translating eotername_min 4919
4848
translating eoparent_min 1730
1678

In [14]:
zno_translated = zno_orig
zno_translated

,eoname,year,sexM,sexF,phys_mat,foreign_phyl,universal,ukr_phyl,technology,bio_phys,...,Total number of students and children receiving preschool education,"Expenses for the functioning of the institution (general fund), thousand hryvnias.\n2019 (cash expenses)","Expenses for the functioning of the institution (general fund), thousand hryvnias.\n2020 (plan)","Specific weight of non-teaching staff in the total number of employees, %","The specific weight of pedagogical workers of retirement age in the total number of pedagogical workers, %","The actual number of classes, students per class","Expenses for the functioning of the institution (general fund), thousand hryvnias.\n2020 (cash expenses)","Expenses for the functioning of the institution (general fund), thousand hryvnias.\n2021 (plan)","Expenditures for 1 student, 2020, thousand UAH.","Expenses for 1st class, thousand UAH. 2020 (box office)"
0,"""Demino-Olexandriv Lyceum of the Troitsky Sett...",2019,3,5,0,0,8,0,0,0,...,59.0,3468.816,4066.48,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"""Demino-Olexandriv Lyceum of the Troitsky Sett...",2020,6,3,0,0,9,0,0,0,...,NaN,NaN,NaN,0.285714,0.133333,7.750000,3620.100000,4862.100000,58.388710,452.512500
2,"""Lantrativ Lyceum of the Troitsky Settlement C...",2019,8,4,0,0,12,0,0,0,...,95.0,4170.501,4652.336,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"""Lantrativ Lyceum of the Troitsky Settlement C...",2020,2,2,0,0,4,0,0,0,...,NaN,NaN,NaN,0.346154,0.235294,8.727273,4298.700000,5290.800000,44.778125,390.790909
4,"""Educational and educational complex ""School o...",2019,23,21,0,20,0,0,0,0,...,778.0,18463.070,28107.648,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18632,"the main institution of education ""Krasiliv Ac...",2020,7,8,0,0,0,0,0,0,...,NaN,NaN,NaN,0.477273,0.000000,8.214286,6302.083323,6429.120117,54.800725,450.148809
18633,"supporting institution of education ""Stavriv e...",2019,6,5,0,0,0,11,0,0,...,424.0,10841.395,12277.22,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18634,"supporting educational institution ""Apostolivs...",2019,11,11,0,0,0,13,0,0,...,844.0,19541.000,21160.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18635,School of I-III degrees No. 104 named after O....,2019,20,20,0,0,0,0,0,0,...,1011.0,25717.609,31263.175,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18636,School of I-III degrees No. 104 named after O....,2020,24,23,0,0,0,0,0,0,...,NaN,NaN,NaN,0.500000,0.241379,31.000000,27213.933000,39694.435000,26.602085,824.664636

In [15]:
zno_orig.to_csv("translated_school_dataset.csv", index=False)