# Create `Students_Take_Tests` table

In [1]:
import numpy as np
import pandas as pd

In [2]:
# load datasets
datasets = {}
years = range(2016, 2024)
for year in years:
    print(f"EIE {year} Loading...")
    if int(year) >= 2019:
        file_name = f'Odata{year}File.csv'
    else:
        file_name = f'OpenData{year}.csv'
    try:           
        dataset = pd.read_csv(f"../../data_loader/{year}/{file_name}", sep=";", encoding='utf-8', dtype = str)
    except:
        dataset = pd.read_csv(f"../../data_loader/{year}/{file_name}", sep=";", encoding='Windows 1251', dtype = str)
    datasets.update({year:dataset})
    print("success")

EIE 2016 Loading...
success
EIE 2017 Loading...
success
EIE 2018 Loading...
success
EIE 2019 Loading...
success
EIE 2020 Loading...
success
EIE 2021 Loading...
success
EIE 2022 Loading...
success
EIE 2023 Loading...
success

## Preprocess and correctly concated datasets by years

In [3]:
eie_2016 = {
    'sptest': 'spatest',
    'spteststatus': 'spateststatus',
    'spball100': 'spaball100',
    'spptname': 'spaptname',
    'spptregname': 'spaptregname',
    'spptareaname': 'spaptareaname',
    'sppttername': 'spapttername',
    'frtest': 'fratest',
    'frteststatus': 'frateststatus',
    'frball100': 'fraball100',
    'frptname': 'fraptname',
    'frptregname': 'fraptregname',
    'frptareaname': 'fraptareaname',
    'frpttername': 'frapttername',
    
}

nmt_2022 = {
    'block1':'ukrtest',
    'block1ball':'ukrball',
    'block1ball100':'ukrball100',
    'block2':'histtest',
    'block2ball':'histball',
    'block2ball100':'histball100',
    'block3':'mathtest',
    'block3ball':'mathball',
    'block3ball100':'mathball100',
}

nmt_2023 = {
    'ukrblock': 'ukrtest',
    'ukrblockstatus': 'ukrteststatus', 
    'ukrblockball100': 'ukrball100', 
    'ukrblockball': 'ukrball', 
    'histblock': 'histtest',
    'histblockstatus': 'histteststatus', 
    'histblockball100': 'histball100',
    'histblockball': 'histball',
    'mathblock': 'mathtest',
    'mathblockstatus': 'mathteststatus',
    'mathblockball100': 'mathball100',
    'mathblockball': 'mathball', 
    'physblock': 'phystest',
    'physblockstatus': 'physteststatus', 
    'physblockball100': 'physball100',
    'physblockball': 'physball', 
    'chemblock': 'chemtest',
    'chemblockstatus': 'chemteststatus', 
    'chemblockball100': 'chemball100', 
    'chemblockball': 'chemball', 
    'bioblock': 'biotest',
    'bioblockstatus': 'bioteststatus', 
    'bioblockball100': 'bioball100', 
    'bioblockball': 'bioball', 
    'engblock': 'engtest',
    'engblockstatus': 'engteststatus',
    'engblockball100': 'engball100', 
    'engblockball': 'engball', 
    'frablock': 'fratest',
    'frablockstatus': 'frateststatus', 
    'frablockball100': 'fraball100', 
    'frablockball': 'fraball', 
    'deublock': 'deutest',
    'deublockstatus': 'deuteststatus', 
    'deublockball100': 'deuball100', 
    'deublockball': 'deuball', 
    'spablock': 'spatest',
    'spablockstatus': 'spateststatus', 
    'spablockball100': 'spaball100', 
    'spablockball': 'spaball',
}

In [4]:
for year, dataset in datasets.items():
    #lowercase all columns and add year as attribute
    dataset.columns = [col.lower() for col in dataset.columns]
    dataset['year'] = year

    if year == 2016:
        dataset = dataset.rename(columns=eie_2016)

    if year == 2022:
        dataset = dataset.rename(columns=nmt_2022)
        for type_ in ['ukr', 'hist', 'math']:
            dataset.loc[:, f'{type_}ptregname'] = dataset['ptregname']
            dataset.loc[:, f'{type_}ptareaname'] = dataset['ptareaname']
            dataset.loc[:, f'{type_}pttername'] = dataset['pttername']
            dataset.loc[:, f'{type_}teststatus'] = dataset['teststatus']
        dataset.drop(columns=['ptregname', 'ptareaname', 'pttername','teststatus'], inplace=True)
    elif year == 2023:
        dataset = dataset.rename(columns=nmt_2023)
        for type_ in ['ukr', 'hist', 'math', 'phys', 'chem', 'bio', 'eng', 'fra', 'deu', 'spa']:
            dataset.loc[:, f'{type_}ptregname'] = dataset['ptregname']
            dataset.loc[:, f'{type_}ptareaname'] = dataset['ptareaname']
            dataset.loc[:, f'{type_}pttername'] = dataset['pttername']
        dataset.drop(columns=['ptregname', 'ptareaname', 'pttername'], inplace=True)
    dataset.reset_index(drop=True, inplace=True)
    datasets.update({year:dataset})

In [5]:
for year, dataset in datasets.items():
    print(year,":",[col for col in dataset.columns])

2016 : ['outid', 'birth', 'sextypename', 'regname', 'areaname', 'tername', 'regtypename', 'eoname', 'eotypename', 'eoregname', 'eoareaname', 'eotername', 'eoparent', 'ukrtest', 'ukrteststatus', 'ukrball100', 'ukrball12', 'ukrptname', 'ukrptregname', 'ukrptareaname', 'ukrpttername', 'histtest', 'histlang', 'histteststatus', 'histball100', 'histball12', 'histptname', 'histptregname', 'histptareaname', 'histpttername', 'mathtest', 'mathlang', 'mathteststatus', 'mathball100', 'mathball12', 'mathptname', 'mathptregname', 'mathptareaname', 'mathpttername', 'phystest', 'physlang', 'physteststatus', 'physball100', 'physptname', 'physptregname', 'physptareaname', 'physpttername', 'chemtest', 'chemlang', 'chemteststatus', 'chemball100', 'chemptname', 'chemptregname', 'chemptareaname', 'chempttername', 'biotest', 'biolang', 'bioteststatus', 'bioball100', 'bioptname', 'bioptregname', 'bioptareaname', 'biopttername', 'geotest', 'geolang', 'geoteststatus', 'geoball100', 'geoptname', 'geoptregname', 'geoptareaname', 'geopttername', 'engtest', 'engteststatus', 'engball100', 'engptname', 'engptregname', 'engptareaname', 'engpttername', 'fratest', 'frateststatus', 'fraball100', 'fraptname', 'fraptregname', 'fraptareaname', 'frapttername', 'deutest', 'deuteststatus', 'deuball100', 'deuptname', 'deuptregname', 'deuptareaname', 'deupttername', 'spatest', 'spateststatus', 'spaball100', 'spaptname', 'spaptregname', 'spaptareaname', 'spapttername', 'rustest', 'rusteststatus', 'rusball100', 'rusptname', 'rusptregname', 'rusptareaname', 'ruspttername', 'year']
2017 : ['outid', 'stid', 'birth', 'sextypename', 'regname', 'areaname', 'tername', 'regtypename', 'tertypename', 'classprofilename', 'classlangname', 'eoname', 'eotypename', 'eoregname', 'eoareaname', 'eotername', 'eoparent', 'ukrtest', 'ukrteststatus', 'ukrball100', 'ukrball12', 'ukrptname', 'ukrptregname', 'ukrptareaname', 'ukrpttername', 'histtest', 'histlang', 'histteststatus', 'histball100', 'histball12', 'histptname', 'histptregname', 'histptareaname', 'histpttername', 'mathtest', 'mathlang', 'mathteststatus', 'mathball100', 'mathball12', 'mathptname', 'mathptregname', 'mathptareaname', 'mathpttername', 'phystest', 'physlang', 'physteststatus', 'physball100', 'physball12', 'physptname', 'physptregname', 'physptareaname', 'physpttername', 'chemtest', 'chemlang', 'chemteststatus', 'chemball100', 'chemball12', 'chemptname', 'chemptregname', 'chemptareaname', 'chempttername', 'biotest', 'biolang', 'bioteststatus', 'bioball100', 'bioball12', 'bioptname', 'bioptregname', 'bioptareaname', 'biopttername', 'geotest', 'geolang', 'geoteststatus', 'geoball100', 'geoball12', 'geoptname', 'geoptregname', 'geoptareaname', 'geopttername', 'engtest', 'engteststatus', 'engball100', 'engball12', 'engptname', 'engptregname', 'engptareaname', 'engpttername', 'fratest', 'frateststatus', 'fraball100', 'fraball12', 'fraptname', 'fraptregname', 'fraptareaname', 'frapttername', 'deutest', 'deuteststatus', 'deuball100', 'deuball12', 'deuptname', 'deuptregname', 'deuptareaname', 'deupttername', 'spatest', 'spateststatus', 'spaball100', 'spaball12', 'spaptname', 'spaptregname', 'spaptareaname', 'spapttername', 'rustest', 'rusteststatus', 'rusball100', 'rusball12', 'rusptname', 'rusptregname', 'rusptareaname', 'ruspttername', 'year']
2018 : ['outid', 'birth', 'sextypename', 'regname', 'areaname', 'tername', 'regtypename', 'tertypename', 'classprofilename', 'classlangname', 'eoname', 'eotypename', 'eoregname', 'eoareaname', 'eotername', 'eoparent', 'ukrtest', 'ukrteststatus', 'ukrball100', 'ukrball12', 'ukrball', 'ukrptname', 'ukrptregname', 'ukrptareaname', 'ukrpttername', 'histtest', 'histlang', 'histteststatus', 'histball100', 'histball12', 'histball', 'histptname', 'histptregname', 'histptareaname', 'histpttername', 'mathtest', 'mathlang', 'mathteststatus', 'mathball100', 'mathball12', 'mathball', 'mathptname', 'mathptregname', 'mathptareaname', 'mathpttername', 'phystest', 'physlang', 'physteststatus', 'physball100', 'physball12', 'physball', 'physptname', 'physptregname', 'physptareaname', 'physpttername', 'chemtest', 'chemlang', 'chemteststatus', 'chemball100', 'chemball12', 'chemball', 'chemptname', 'chemptregname', 'chemptareaname', 'chempttername', 'biotest', 'biolang', 'bioteststatus', 'bioball100', 'bioball12', 'bioball', 'bioptname', 'bioptregname', 'bioptareaname', 'biopttername', 'geotest', 'geolang', 'geoteststatus', 'geoball100', 'geoball12', 'geoball', 'geoptname', 'geoptregname', 'geoptareaname', 'geopttername', 'engtest', 'engteststatus', 'engball100', 'engball12', 'engdpalevel', 'engball', 'engptname', 'engptregname', 'engptareaname', 'engpttername', 'fratest', 'frateststatus', 'fraball100', 'fraball12', 'fradpalevel', 'fraball', 'fraptname', 'fraptregname', 'fraptareaname', 'frapttername', 'deutest', 'deuteststatus', 'deuball100', 'deuball12', 'deudpalevel', 'deuball', 'deuptname', 'deuptregname', 'deuptareaname', 'deupttername', 'spatest', 'spateststatus', 'spaball100', 'spaball12', 'spadpalevel', 'spaball', 'spaptname', 'spaptregname', 'spaptareaname', 'spapttername', 'year']
2019 : ['outid', 'birth', 'sextypename', 'regname', 'areaname', 'tername', 'regtypename', 'tertypename', 'classprofilename', 'classlangname', 'eoname', 'eotypename', 'eoregname', 'eoareaname', 'eotername', 'eoparent', 'ukrtest', 'ukrteststatus', 'ukrball100', 'ukrball12', 'ukrball', 'ukradaptscale', 'ukrptname', 'ukrptregname', 'ukrptareaname', 'ukrpttername', 'histtest', 'histlang', 'histteststatus', 'histball100', 'histball12', 'histball', 'histptname', 'histptregname', 'histptareaname', 'histpttername', 'mathtest', 'mathlang', 'mathteststatus', 'mathball100', 'mathball12', 'mathball', 'mathptname', 'mathptregname', 'mathptareaname', 'mathpttername', 'phystest', 'physlang', 'physteststatus', 'physball100', 'physball12', 'physball', 'physptname', 'physptregname', 'physptareaname', 'physpttername', 'chemtest', 'chemlang', 'chemteststatus', 'chemball100', 'chemball12', 'chemball', 'chemptname', 'chemptregname', 'chemptareaname', 'chempttername', 'biotest', 'biolang', 'bioteststatus', 'bioball100', 'bioball12', 'bioball', 'bioptname', 'bioptregname', 'bioptareaname', 'biopttername', 'geotest', 'geolang', 'geoteststatus', 'geoball100', 'geoball12', 'geoball', 'geoptname', 'geoptregname', 'geoptareaname', 'geopttername', 'engtest', 'engteststatus', 'engball100', 'engball12', 'engdpalevel', 'engball', 'engptname', 'engptregname', 'engptareaname', 'engpttername', 'fratest', 'frateststatus', 'fraball100', 'fraball12', 'fradpalevel', 'fraball', 'fraptname', 'fraptregname', 'fraptareaname', 'frapttername', 'deutest', 'deuteststatus', 'deuball100', 'deuball12', 'deudpalevel', 'deuball', 'deuptname', 'deuptregname', 'deuptareaname', 'deupttername', 'spatest', 'spateststatus', 'spaball100', 'spaball12', 'spadpalevel', 'spaball', 'spaptname', 'spaptregname', 'spaptareaname', 'spapttername', 'year']
2020 : ['outid', 'birth', 'sextypename', 'regname', 'areaname', 'tername', 'regtypename', 'tertypename', 'classprofilename', 'classlangname', 'eoname', 'eotypename', 'eoregname', 'eoareaname', 'eotername', 'eoparent', 'ukrtest', 'ukrteststatus', 'ukrball100', 'ukrball12', 'ukrball', 'ukradaptscale', 'ukrptname', 'ukrptregname', 'ukrptareaname', 'ukrpttername', 'histtest', 'histlang', 'histteststatus', 'histball100', 'histball12', 'histball', 'histptname', 'histptregname', 'histptareaname', 'histpttername', 'mathtest', 'mathlang', 'mathteststatus', 'mathball100', 'mathball12', 'mathball', 'mathptname', 'mathptregname', 'mathptareaname', 'mathpttername', 'phystest', 'physlang', 'physteststatus', 'physball100', 'physball12', 'physball', 'physptname', 'physptregname', 'physptareaname', 'physpttername', 'chemtest', 'chemlang', 'chemteststatus', 'chemball100', 'chemball12', 'chemball', 'chemptname', 'chemptregname', 'chemptareaname', 'chempttername', 'biotest', 'biolang', 'bioteststatus', 'bioball100', 'bioball12', 'bioball', 'bioptname', 'bioptregname', 'bioptareaname', 'biopttername', 'geotest', 'geolang', 'geoteststatus', 'geoball100', 'geoball12', 'geoball', 'geoptname', 'geoptregname', 'geoptareaname', 'geopttername', 'engtest', 'engteststatus', 'engball100', 'engball12', 'engdpalevel', 'engball', 'engptname', 'engptregname', 'engptareaname', 'engpttername', 'fratest', 'frateststatus', 'fraball100', 'fraball12', 'fradpalevel', 'fraball', 'fraptname', 'fraptregname', 'fraptareaname', 'frapttername', 'deutest', 'deuteststatus', 'deuball100', 'deuball12', 'deudpalevel', 'deuball', 'deuptname', 'deuptregname', 'deuptareaname', 'deupttername', 'spatest', 'spateststatus', 'spaball100', 'spaball12', 'spadpalevel', 'spaball', 'spaptname', 'spaptregname', 'spaptareaname', 'spapttername', 'year']
2021 : ['outid', 'birth', 'sextypename', 'regname', 'areaname', 'tername', 'regtypename', 'tertypename', 'classprofilename', 'classlangname', 'eoname', 'eotypename', 'eoregname', 'eoareaname', 'eotername', 'eoparent', 'umltest', 'umlteststatus', 'umlball100', 'umlball12', 'umlball', 'umladaptscale', 'umlptname', 'umlptregname', 'umlptareaname', 'umlpttername', 'ukrtest', 'ukrsubtest', 'ukrteststatus', 'ukrball100', 'ukrball12', 'ukrball', 'ukradaptscale', 'ukrptname', 'ukrptregname', 'ukrptareaname', 'ukrpttername', 'histtest', 'histlang', 'histteststatus', 'histball100', 'histball12', 'histball', 'histptname', 'histptregname', 'histptareaname', 'histpttername', 'mathtest', 'mathlang', 'mathteststatus', 'mathball100', 'mathball12', 'mathdpalevel', 'mathball', 'mathptname', 'mathptregname', 'mathptareaname', 'mathpttername', 'mathsttest', 'mathstlang', 'mathstteststatus', 'mathstball12', 'mathstball', 'mathstptname', 'mathstptregname', 'mathstptareaname', 'mathstpttername', 'phystest', 'physlang', 'physteststatus', 'physball100', 'physball12', 'physball', 'physptname', 'physptregname', 'physptareaname', 'physpttername', 'chemtest', 'chemlang', 'chemteststatus', 'chemball100', 'chemball12', 'chemball', 'chemptname', 'chemptregname', 'chemptareaname', 'chempttername', 'biotest', 'biolang', 'bioteststatus', 'bioball100', 'bioball12', 'bioball', 'bioptname', 'bioptregname', 'bioptareaname', 'biopttername', 'geotest', 'geolang', 'geoteststatus', 'geoball100', 'geoball12', 'geoball', 'geoptname', 'geoptregname', 'geoptareaname', 'geopttername', 'engtest', 'engteststatus', 'engball100', 'engball12', 'engdpalevel', 'engball', 'engptname', 'engptregname', 'engptareaname', 'engpttername', 'fratest', 'frateststatus', 'fraball100', 'fraball12', 'fradpalevel', 'fraball', 'fraptname', 'fraptregname', 'fraptareaname', 'frapttername', 'deutest', 'deuteststatus', 'deuball100', 'deuball12', 'deudpalevel', 'deuball', 'deuptname', 'deuptregname', 'deuptareaname', 'deupttername', 'spatest', 'spateststatus', 'spaball100', 'spaball12', 'spadpalevel', 'spaball', 'spaptname', 'spaptregname', 'spaptareaname', 'spapttername', 'year']
2022 : ['outid', 'birth', 'sextypename', 'regname', 'areaname', 'tername', 'regtypename', 'tertypename', 'eoname', 'eotypename', 'eoregname', 'eoareaname', 'eotername', 'eoparent', 'test', 'testdate', 'ukrtest', 'ukrball100', 'ukrball', 'histtest', 'histball100', 'histball', 'mathtest', 'mathball100', 'mathball', 'year', 'ukrptregname', 'ukrptareaname', 'ukrpttername', 'ukrteststatus', 'histptregname', 'histptareaname', 'histpttername', 'histteststatus', 'mathptregname', 'mathptareaname', 'mathpttername', 'mathteststatus']
2023 : ['outid', 'birth', 'sextypename', 'regname', 'areaname', 'tername', 'regtypename', 'tertypename', 'eoname', 'eotypename', 'eoregname', 'eoareaname', 'eotername', 'eoparent', 'test', 'testdate', 'ukrtest', 'ukrteststatus', 'ukrball100', 'ukrball', 'histtest', 'histteststatus', 'histball100', 'histball', 'mathtest', 'mathteststatus', 'mathball100', 'mathball', 'phystest', 'physteststatus', 'physball100', 'physball', 'chemtest', 'chemteststatus', 'chemball100', 'chemball', 'biotest', 'bioteststatus', 'bioball100', 'bioball', 'engtest', 'engteststatus', 'engball100', 'engball', 'fratest', 'frateststatus', 'fraball100', 'fraball', 'deutest', 'deuteststatus', 'deuball100', 'deuball', 'spatest', 'spateststatus', 'spaball100', 'spaball', 'year', 'ukrptregname', 'ukrptareaname', 'ukrpttername', 'histptregname', 'histptareaname', 'histpttername', 'mathptregname', 'mathptareaname', 'mathpttername', 'physptregname', 'physptareaname', 'physpttername', 'chemptregname', 'chemptareaname', 'chempttername', 'bioptregname', 'bioptareaname', 'biopttername', 'engptregname', 'engptareaname', 'engpttername', 'fraptregname', 'fraptareaname', 'frapttername', 'deuptregname', 'deuptareaname', 'deupttername', 'spaptregname', 'spaptareaname', 'spapttername']

In [6]:
pd.set_option('display.max_columns', None)
datasets[2018].head()

,outid,birth,sextypename,regname,areaname,tername,regtypename,tertypename,classprofilename,classlangname,eoname,eotypename,eoregname,eoareaname,eotername,eoparent,ukrtest,ukrteststatus,ukrball100,ukrball12,ukrball,ukrptname,ukrptregname,ukrptareaname,ukrpttername,histtest,histlang,histteststatus,histball100,histball12,histball,histptname,histptregname,histptareaname,histpttername,mathtest,mathlang,mathteststatus,mathball100,mathball12,mathball,mathptname,mathptregname,mathptareaname,mathpttername,phystest,physlang,physteststatus,physball100,physball12,physball,physptname,physptregname,physptareaname,physpttername,chemtest,chemlang,chemteststatus,chemball100,chemball12,chemball,chemptname,chemptregname,chemptareaname,chempttername,biotest,biolang,bioteststatus,bioball100,bioball12,bioball,bioptname,bioptregname,bioptareaname,biopttername,geotest,geolang,geoteststatus,geoball100,geoball12,geoball,geoptname,geoptregname,geoptareaname,geopttername,engtest,engteststatus,engball100,engball12,engdpalevel,engball,engptname,engptregname,engptareaname,engpttername,fratest,frateststatus,fraball100,fraball12,fradpalevel,fraball,fraptname,fraptregname,fraptareaname,frapttername,deutest,deuteststatus,deuball100,deuball12,deudpalevel,deuball,deuptname,deuptregname,deuptareaname,deupttername,spatest,spateststatus,spaball100,spaball12,spadpalevel,spaball,spaptname,spaptregname,spaptareaname,spapttername,year
0,a4e039d0-07ef-4a3d-820d-106dcaf01b96,2001,чоловіча,Закарпатська область,Берегівський район,с.Косонь,Випускник закладу загальної середньої освіти 2...,село,Фізико-математичний,угорська,Косоньська загальноосвітня школа І-ІІІ ступені...,середня загальноосвітня школа,Закарпатська область,Берегівський район,с.Косонь,"Відділ освіти, молоді та спорту Берегівської р...",Українська мова і література,Не подолав поріг,0.0,2,15,Берегівська загальноосвітня школа І-ІІІ ступен...,Закарпатська область,м.Берегове,м.Берегове,Історія України,угорська,Не подолав поріг,0.0,5,24,Берегівська загальноосвітня школа І-ІІІ ступен...,Закарпатська область,м.Берегове,м.Берегове,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Біологія,угорська,Зараховано,100.0,4,22,Мукачівська загальноосвітня школа І-ІІІ ступен...,Закарпатська область,м.Мукачево,м.Мукачево,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
1,c1fa1ed0-d2af-4964-9a88-3c138008304b,2001,жіноча,Київська область,Київська область,м.Бровари,Випускник закладу загальної середньої освіти 2...,місто,Іноземної філології,українська,Броварська спеціалізована школа І-ІІІ ступенів...,спеціалізована школа,Київська область,м.Бровари,м.Бровари,Управління освіти і науки Броварської міської ...,Українська мова і література,Зараховано,185.0,11,87,Комунальний вищий навчальний заклад Київської ...,Київська область,м.Бровари,м.Бровари,Історія України,українська,Зараховано,164.0,9,56,Броварська загальноосвітня школа І-ІІІ ступені...,Київська область,м.Бровари,м.Бровари,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Географія,українська,Зараховано,140.0,NaN,43,Броварська спеціалізована школа І-ІІІ ступенів...,Київська область,м.Бровари,м.Бровари,Англійська мова,Зараховано,189.0,11,профільний,63,Броварська загальноосвітня школа І-ІІІ ступені...,Київська область,м.Бровари,м.Бровари,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
2,6504a7f3-7dfd-4a64-a2d9-4d49f5021303,2000,жіноча,Харківська область,м.Харків,Червонозаводський район міста,Випускник закладу загальної середньої освіти 2...,місто,Іноземної філології,українська,Харківська гімназія № 12 Харківської міської р...,гімназія,Харківська область,м.Харків. Червонозаводський район міста,Червонозаводський район міста,Управління освіти адміністрації Основ'янського...,Українська мова і література,Зараховано,186.0,10,88,Харківський інститут фінансів Київського націо...,Харківська область,м.Харків. Червонозаводський район міста,Червонозаводський район міста,Історія України,українська,Зараховано,170.0,9,61,Харківський національний автомобільно-дорожній...,Харківська область,м.Харків. Московський район міста,Московський район міста,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Англійська мова,Зараховано,175.0,10,профільний,55,Харківська загальноосвітня школа I-III ступені...,Харківська область,м.Харків. Київський район міста,Київський район міста,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
3,5cbcd343-2e63-48b8-b36d-48797a76be31,2000,чоловіча,Рівненська область,Млинівський район,смт Млинів,Випускник закладу загальної середньої освіти 2...,місто,Фізико-математичний,українська,Млинівська загальноосвітня школа І-ІІІ ступені...,середня загальноосвітня школа,Рівненська область,Млинівський район,смт Млинів,"Управління освіти, культури, туризму, молоді т...",Українська мова і література,Зараховано,119.0,5,34,Млинівська загальноосвітня школа І-ІІІ ступені...,Рівненська область,Млинівський район,смт Млинів,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Математика,українська,Зараховано,107.0,4,12,Дубенська гімназія №2 Дубенської міської ради ...,Рівненська область,м.Дубно,м.Дубно,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Біологія,українська,Зараховано,115.0,5,28,Рівненська загальноосвітня школа І-ІІІ ступені...,Рівненська область,м.Рівне,м.Рівне,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
4,063c6498-7345-492c-b567-174938bac671,1999,чоловіча,Рівненська область,Рівненська область,м.Острог,Учень (слухач) закладу професійної (професійно...,місто,NaN,NaN,Державний професійно-технічний навчальний закл...,вище професійне училище,Рівненська область,м.Острог,м.Острог,Управління освіти і науки Рівненської обласної...,Українська мова і література,Зараховано,105.0,3,26,"Острозький навчально-виховний комплекс ""Школа ...",Рівненська область,м.Острог,м.Острог,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018

In [7]:
# temp for test
df = pd.concat([dataset for year, dataset in datasets.items()], ignore_index=True)

In [8]:
# show all columns with ball
print(sorted(df.columns[df.columns.str.contains('ball')]))

df.loc[:, 'mathstball100'] = None
df.loc[:, 'rusball'] = None

['bioball', 'bioball100', 'bioball12', 'chemball', 'chemball100', 'chemball12', 'deuball', 'deuball100', 'deuball12', 'engball', 'engball100', 'engball12', 'fraball', 'fraball100', 'fraball12', 'geoball', 'geoball100', 'geoball12', 'histball', 'histball100', 'histball12', 'mathball', 'mathball100', 'mathball12', 'mathstball', 'mathstball12', 'physball', 'physball100', 'physball12', 'rusball100', 'rusball12', 'spaball', 'spaball100', 'spaball12', 'ukrball', 'ukrball100', 'ukrball12', 'umlball', 'umlball100', 'umlball12']

/var/folders/cz/wq9d8j_11fx3b8pjjbk7z8br0000gn/T/ipykernel_43555/2513467481.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[:, 'mathstball100'] = None
/var/folders/cz/wq9d8j_11fx3b8pjjbk7z8br0000gn/T/ipykernel_43555/2513467481.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[:, 'rusball'] = None

In [9]:
df.head()

,outid,birth,sextypename,regname,areaname,tername,regtypename,eoname,eotypename,eoregname,eoareaname,eotername,eoparent,ukrtest,ukrteststatus,ukrball100,ukrball12,ukrptname,ukrptregname,ukrptareaname,ukrpttername,histtest,histlang,histteststatus,histball100,histball12,histptname,histptregname,histptareaname,histpttername,mathtest,mathlang,mathteststatus,mathball100,mathball12,mathptname,mathptregname,mathptareaname,mathpttername,phystest,physlang,physteststatus,physball100,physptname,physptregname,physptareaname,physpttername,chemtest,chemlang,chemteststatus,chemball100,chemptname,chemptregname,chemptareaname,chempttername,biotest,biolang,bioteststatus,bioball100,bioptname,bioptregname,bioptareaname,biopttername,geotest,geolang,geoteststatus,geoball100,geoptname,geoptregname,geoptareaname,geopttername,engtest,engteststatus,engball100,engptname,engptregname,engptareaname,engpttername,fratest,frateststatus,fraball100,fraptname,fraptregname,fraptareaname,frapttername,deutest,deuteststatus,deuball100,deuptname,deuptregname,deuptareaname,deupttername,spatest,spateststatus,spaball100,spaptname,spaptregname,spaptareaname,spapttername,rustest,rusteststatus,rusball100,rusptname,rusptregname,rusptareaname,ruspttername,year,stid,tertypename,classprofilename,classlangname,physball12,chemball12,bioball12,geoball12,engball12,fraball12,deuball12,spaball12,rusball12,ukrball,histball,mathball,physball,chemball,bioball,geoball,engdpalevel,engball,fradpalevel,fraball,deudpalevel,deuball,spadpalevel,spaball,ukradaptscale,umltest,umlteststatus,umlball100,umlball12,umlball,umladaptscale,umlptname,umlptregname,umlptareaname,umlpttername,ukrsubtest,mathdpalevel,mathsttest,mathstlang,mathstteststatus,mathstball12,mathstball,mathstptname,mathstptregname,mathstptareaname,mathstpttername,test,testdate,mathstball100,rusball
0,a99c6c63-aa70-4aec-ba42-370f7261e857,1998,чоловіча,Запорізька область,Мелітопольський район,с.Терпіння,Випускник загальноосвітнього навчального закла...,"Терпіннівський колегіум ""Джерело"" Мелітопольсь...",колегіум,Запорізька область,Мелітопольський район,с.Терпіння,Відділ освіти Мелітопольської районної державн...,Українська мова і література,Отримав результат,"112,0",5,Мелітопольська загальноосвітня школа І-ІІІ сту...,Запорізька область,м.Мелітополь,м.Мелітополь,Історія України,українська,Отримав результат,"125,0",5,Мелітопольська загальноосвітня школа I-III сту...,Запорізька область,м.Мелітополь,м.Мелітополь,NaN,NaN,Не зареєстровано для проходження основної сесії,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Не зареєстровано для проходження основної сесії,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Не зареєстровано для проходження основної сесії,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Не зареєстровано для проходження основної сесії,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Не зареєстровано для проходження основної сесії,NaN,NaN,NaN,NaN,NaN,NaN,Не зареєстровано для проходження основної сесії,NaN,NaN,NaN,NaN,NaN,NaN,Не зареєстровано для проходження основної сесії,NaN,NaN,NaN,NaN,NaN,NaN,Не зареєстровано для проходження основної сесії,NaN,NaN,NaN,NaN,NaN,NaN,Не зареєстровано для проходження основної сесії,NaN,NaN,NaN,NaN,NaN,NaN,Не зареєстровано для проходження основної сесії,NaN,NaN,NaN,NaN,NaN,2016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None
1,c3136421-569e-422e-ae8f-41c4c931fd70,1998,жіноча,Хмельницька область,Красилівський район,м.Красилів,Випускник загальноосвітнього навчального закла...,Красилівська загальноосвітня школа I-III ступе...,середня загальноосвітня школа,Хмельницька область,Красилівський район,м.Красилів,"Управління освіти, молоді та спорту Красилівсь...",Українська мова і література,Отримав результат,"133,0",5,"Красилівський навчально-виховний комплекс ""Гім...",Хмельницька область,Красилівський район,м.Красилів,Історія України,українська,Отримав результат,"111,0",4,"Красилівський навчально-виховний комплекс ""Гім...",Хмельницька область,Красилівський район,м.Красилів,NaN,NaN,Не зареєстровано для проходження основної сесії,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Не зареєстровано для проходження основної сесії,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Не зареєстровано для проходження основної сесії,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Не зареєстровано для проходження основної сесії,NaN,NaN,NaN,NaN,NaN,Географія,українська,Не склав,"0,0",Хмельницький національний університет,Хмельницька область,м.Хмельницький,м.Хмельницький,NaN,Не зареєстровано для проходження основної сесії,NaN,NaN,NaN,NaN,NaN,NaN,Не зареєстровано для проходження основної сесії,NaN,NaN,NaN,NaN,NaN,NaN,Не зареєстровано для проходження основної сесії,NaN,NaN,NaN,NaN,NaN,NaN,Не зареєстровано для проходження основної сесії,NaN,NaN,NaN,NaN,NaN,NaN,Не зареєстровано для проходження основної сесії,NaN,NaN,NaN,NaN,NaN,2016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None
2,fbd0e280-4b77-4f34-942d-00bc850c2992,1995,жіноча,Дніпропетровська область,Петропавлівський район,с.Дмитрівка,Випускник минулих років,NaN,NaN,NaN,NaN,NaN,NaN,Українська мова і література,Отримав результат,"149,0",NaN,Першотравенська загальноосвітня школа І-ІІІ ст...,Дніпропетровська область,м.Першотравенськ,м.Першотравенськ,Історія України,українська,Отримав результат,"128,0",NaN,Першотравенська загальноосвітня школа І-ІІІ ст...,Дніпропетровська область,м.Першотравенськ,м.Першотравенськ,Математика,українська,Отримав результат,"125,0",NaN,Першотравенська загальноосвітня школа І-ІІІ ст...,Дніпропетровська область,м.Першотравенськ,м.Першотравенськ,NaN,NaN,Не зареєстровано для проходження основної сесії,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Не зареєстровано для проходження основної сесії,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Не зареєстровано для проходження основної сесії,NaN,NaN,NaN,NaN,NaN,Географія,українська,Не з'явився,NaN,Західно-Донбаський професійний ліцей,Дніпропетровська область,м.Павлоград,м.Павлоград,NaN,Не зареєстровано для проходження основної сесії,NaN,NaN,NaN,NaN,NaN,NaN,Не зареєстровано для проходження основної сесії,NaN,NaN,NaN,NaN,NaN,NaN,Не зареєстровано для проходження основної сесії,NaN,NaN,NaN,NaN,NaN,NaN,Не зареєстровано для проходження основної сесії,NaN,NaN,NaN,NaN,NaN,NaN,Не зареєстровано для проходження основної сесії,NaN,NaN,NaN,NaN,NaN,2016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None
3,30de395e-7a74-452a-8370-6856d240fbfb,1999,чоловіча,Чернівецька область,м.Чернівці,Шевченківський район міста,Випускник загальноосвітнього навчального закла...,Чернівецька спеціалізована школа І-ІІІ ступені...,спеціалізована школа,Чернівецька область,м.Чернівці,Шевченківський район міста,Управління освіти Чернівецької міської ради,Українська мова і література,Отримав результат,"160,0",9,Чернівецька загальноосвітня школа І-ІІІ ступен...,Чернівецька область,м.Чернівці. Шевченківський район міста,Шевченківський район міста,NaN,NaN,Не зареєстровано для проходження основної сесії,NaN,NaN,NaN,NaN,NaN,NaN,Математика,українська,Отримав результат,"143,0",6,Чернівецька загальноосвітня школа І-ІІІ ступен...,Чернівецька область,м.Чернівці. Шевченківський район міста,Шевченківський район міста,Фізика,українська,Отримав результат,"147,0",Чернівецька гімназія №4 Чернівецької міської ради,Чернівецька область,м.Чернівці. Шевченківський район міста,Шевченківський район міста,NaN,NaN,Не зареєстровано для проходження основної сесії,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Не зареєстровано для проходження основної сесії,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Не зареєстровано для проходження основної сесії,NaN,NaN,NaN,NaN,NaN,Англійська мова,Отримав результат,"132,0",Чернівецька загальноосвітня школа І-ІІІ ступен...,Чернівецька область,м.Чернівці. Шевченківський район міста,Шевченківський район міста,NaN,Не зареєстровано для проходження основної сесії,NaN,NaN,NaN,NaN,NaN,NaN,Не зареєстровано для проходження основної сесії,NaN,NaN,NaN,NaN,NaN,NaN,Не зареєстровано для проходження основної сесії,NaN,NaN,NaN,NaN,NaN,NaN,Не зареєстровано для проходження основної сесії,NaN,NaN,NaN,NaN,NaN,2016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None
4,52a40c74-374e-4744-bd6f-938ab7a4a641,1997,чоловіча,Миколаївська область,Врадіївський район,с.Кумарі,"Учень (слухач, студент) професійно-технічного,...",NaN,NaN,NaN,NaN,NaN,NaN,Українська мова і література,Отримав результат,"151,0",NaN,Первомайська загальноосвітня школа I-III ступе...,Миколаївська область,м.Первомайськ,м.Первомайськ,Історія України,українська,Отримав результат,"166,0",NaN,"Первомайський навчально-виховний комплекс ""Заг...",Миколаївська область,м.Первомайськ,м.Первомайськ,Математика,українська,Отримав результат,"140,0",NaN,"Первомайський навчально-виховний комплекс ""Заг...",Миколаївська область,м.Первомайськ,м.Первомайськ,NaN,NaN,Не зареєстровано для проходження основної сесії,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Не зареєстровано для проходження основної сесії,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Не зареєстровано для проходження основної сесії,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Не зареєстровано для проходження основної сесії,NaN,NaN,NaN,NaN,NaN,Англійська мова,Не з'явився,NaN,"Первомайський навчально-виховний комплекс ""Заг...",Миколаївська область,м.Первомайськ,м.Первомайськ,NaN,Не зареєстровано для проходження основної сесії,NaN,NaN,NaN,NaN,NaN,NaN,Не зареєстровано для проходження основної сесії,NaN,NaN,NaN,NaN,NaN,NaN,Не зареєстровано для проходження основної сесії,NaN,NaN,NaN,NaN,NaN,NaN,Не зареєстровано для проходження основної сесії,NaN,NaN,NaN,NaN,NaN,2016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None

In [10]:
from itertools import cycle
import pandas as pd


def is_scalar(obj):
    if isinstance(obj, str):
        return True
    elif hasattr(obj, "__iter__"):
        return False
    else:
        return True


def multi_melt(
    df: pd.DataFrame,
    id_vars=None,
    value_vars=None,
    var_name=None,
    value_name="value",
    col_level=None,
    ignore_index=True,
) -> pd.DataFrame:

    # Note: we don't broadcast value_vars ... that would seem unintuitive
    value_vars = value_vars if not is_scalar(value_vars[0]) else [value_vars]
    var_name = var_name if not is_scalar(var_name) else cycle([var_name])
    value_name = value_name if not is_scalar(value_name) else cycle([value_name])

    melted_dfs = [
        (
            df.melt(
                id_vars,
                *melt_args,
                col_level,
                ignore_index,
            ).pipe(lambda df: df.set_index([*id_vars, df.groupby(id_vars).cumcount()]))
        )
        for melt_args in zip(value_vars, var_name, value_name)
    ]

    return (
        pd.concat(melted_dfs, axis=1)
        .sort_index(level=2)
        .reset_index(level=2, drop=True)
        .reset_index()
    )

In [11]:
df = df.pipe(
    multi_melt,
    id_vars=["outid","year"],
    value_vars=[[col for col in df.columns if 'ball100' in col], 
                [col for col in df.columns if 'ball12' in col],
                [col for col in df.columns if col.endswith('ball')],
                [col for col in df.columns if col.endswith('teststatus')],
                [col for col in df.columns if col.endswith('ptname')],
                [col for col in df.columns if col.endswith('ptregname')],
                [col for col in df.columns if col.endswith('ptareaname')],
                [col for col in df.columns if col.endswith('pttername')],
                ],
    var_name=["score100_id", "score12_id", "score_id", "test_status_id", "testcenter_name_id",
                 "test_reg_id", "test_area_id", "test_ter_id"],
    value_name=["score100", "score12", "score", "test_status_", "testcenter_name", "test_reg", "test_area", "test_ter"],
)

In [12]:
df

,outid,year,score100_id,score100,score12_id,score12,score_id,score,test_status_id,test_status_,testcenter_name_id,testcenter_name,test_reg_id,test_reg,test_area_id,test_area,test_ter_id,test_ter
0,00000AC7-CDDE-4C77-B979-8B0351AF1305,2017,ukrball100,161.0,ukrball12,9.0,ukrball,NaN,ukrteststatus,Зараховано,ukrptname,"Одеський навчально-виховний комплекс № 53 ""Заг...",ukrptregname,Одеська область,ukrptareaname,м.Одеса. Малиновський район міста,ukrpttername,Малиновський район міста
1,00000dce-36de-4d58-9dc2-7ffc824f597a,2021,ukrball100,NaN,ukrball12,NaN,ukrball,NaN,ukrteststatus,Не з’явився,ukrptname,Коростенський міський ліцей Житомирської області,ukrptregname,Житомирська область,ukrptareaname,м.Коростень,ukrpttername,м.Коростень
2,00001a8d-fff5-4c7c-bea2-b0157f7c5655,2021,ukrball100,"128,0",ukrball12,6,ukrball,31,ukrteststatus,Зараховано,ukrptname,Черкаська спеціалізована школа І-ІІІ ступенів ...,ukrptregname,Черкаська область,ukrptareaname,м.Черкаси. Придніпровський район міста,ukrpttername,Придніпровський район міста
3,0000268f-9fdd-49b2-9ee2-422778c9c4f1,2016,ukrball100,"160,0",ukrball12,8,ukrball,NaN,ukrteststatus,Отримав результат,ukrptname,"Комунальний заклад ""Харківська загальноосвітня...",ukrptregname,Харківська область,ukrptareaname,м.Харків. Київський район міста,ukrpttername,Київський район міста
4,0000324e-f525-49c4-a963-8df0cc02d6d5,2018,ukrball100,166.0,ukrball12,9,ukrball,69,ukrteststatus,Зараховано,ukrptname,Стрийський коледж Львівського національного аг...,ukrptregname,Львівська область,ukrptareaname,м.Стрий,ukrpttername,м.Стрий
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34860737,ffffeb30-6810-4054-b0b3-04c13a450c85,2022,mathstball100,None,mathstball12,NaN,rusball,None,mathstteststatus,NaN,mathstptname,NaN,mathstptregname,NaN,mathstptareaname,NaN,mathstpttername,NaN
34860738,ffffeeb2-7258-4465-bca3-88dd19902340,2019,mathstball100,None,mathstball12,NaN,rusball,None,mathstteststatus,NaN,mathstptname,NaN,mathstptregname,NaN,mathstptareaname,NaN,mathstpttername,NaN
34860739,fffff6db-6fcc-481f-aa92-49906c0ad1c8,2021,mathstball100,None,mathstball12,NaN,rusball,None,mathstteststatus,Не з’явився,mathstptname,Середня загальноосвітня школа №84 імені Блажен...,mathstptregname,Львівська область,mathstptareaname,м.Львів. Сихівський район міста,mathstpttername,Сихівський район міста
34860740,fffff7dc-0331-41bb-aa5e-e51024ac605e,2021,mathstball100,None,mathstball12,NaN,rusball,None,mathstteststatus,NaN,mathstptname,NaN,mathstptregname,NaN,mathstptareaname,NaN,mathstpttername,NaN
34860741,fffffc86-fc3f-4175-8a4a-a3d1206bf792,2018,mathstball100,None,mathstball12,NaN,rusball,None,mathstteststatus,NaN,mathstptname,NaN,mathstptregname,NaN,mathstptareaname,NaN,mathstpttername,NaN

In [13]:
df[df.outid=='00000AC7-CDDE-4C77-B979-8B0351AF1305']

,outid,year,score100_id,score100,score12_id,score12,score_id,score,test_status_id,test_status_,testcenter_name_id,testcenter_name,test_reg_id,test_reg,test_area_id,test_area,test_ter_id,test_ter
0,00000AC7-CDDE-4C77-B979-8B0351AF1305,2017,ukrball100,161.0,ukrball12,9.0,ukrball,NaN,ukrteststatus,Зараховано,ukrptname,"Одеський навчально-виховний комплекс № 53 ""Заг...",ukrptregname,Одеська область,ukrptareaname,м.Одеса. Малиновський район міста,ukrpttername,Малиновський район міста
2490053,00000AC7-CDDE-4C77-B979-8B0351AF1305,2017,histball100,155.0,histball12,8.0,histball,NaN,histteststatus,Зараховано,histptname,Одеська загальноосвітня школа № 31 І-III ступе...,histptregname,Одеська область,histptareaname,м.Одеса. Малиновський район міста,histpttername,Малиновський район міста
4980106,00000AC7-CDDE-4C77-B979-8B0351AF1305,2017,mathball100,NaN,mathball12,NaN,mathball,NaN,mathteststatus,NaN,mathptname,NaN,mathptregname,NaN,mathptareaname,NaN,mathpttername,NaN
7470159,00000AC7-CDDE-4C77-B979-8B0351AF1305,2017,physball100,NaN,physball12,NaN,physball,NaN,physteststatus,NaN,physptname,NaN,physptregname,NaN,physptareaname,NaN,physpttername,NaN
9960212,00000AC7-CDDE-4C77-B979-8B0351AF1305,2017,chemball100,NaN,chemball12,NaN,chemball,NaN,chemteststatus,NaN,chemptname,NaN,chemptregname,NaN,chemptareaname,NaN,chempttername,NaN
12450265,00000AC7-CDDE-4C77-B979-8B0351AF1305,2017,bioball100,NaN,bioball12,NaN,bioball,NaN,bioteststatus,NaN,bioptname,NaN,bioptregname,NaN,bioptareaname,NaN,biopttername,NaN
14940318,00000AC7-CDDE-4C77-B979-8B0351AF1305,2017,geoball100,NaN,geoball12,NaN,geoball,NaN,geoteststatus,NaN,geoptname,NaN,geoptregname,NaN,geoptareaname,NaN,geopttername,NaN
17430371,00000AC7-CDDE-4C77-B979-8B0351AF1305,2017,engball100,137.0,engball12,7.0,engball,NaN,engteststatus,Зараховано,engptname,Одеська загальноосвітня школа №46 I-III ступен...,engptregname,Одеська область,engptareaname,м.Одеса. Малиновський район міста,engpttername,Малиновський район міста
19920424,00000AC7-CDDE-4C77-B979-8B0351AF1305,2017,fraball100,NaN,fraball12,NaN,fraball,NaN,frateststatus,NaN,fraptname,NaN,fraptregname,NaN,fraptareaname,NaN,frapttername,NaN
22410477,00000AC7-CDDE-4C77-B979-8B0351AF1305,2017,deuball100,NaN,deuball12,NaN,deuball,NaN,deuteststatus,NaN,deuptname,NaN,deuptregname,NaN,deuptareaname,NaN,deupttername,NaN
24900530,00000AC7-CDDE-4C77-B979-8B0351AF1305,2017,spaball100,NaN,spaball12,NaN,spaball,NaN,spateststatus,NaN,spaptname,NaN,spaptregname,NaN,spaptareaname,NaN,spapttername,NaN
27390583,00000AC7-CDDE-4C77-B979-8B0351AF1305,2017,rusball100,NaN,rusball12,NaN,umlball,NaN,rusteststatus,NaN,rusptname,NaN,rusptregname,NaN,rusptareaname,NaN,ruspttername,NaN
29880636,00000AC7-CDDE-4C77-B979-8B0351AF1305,2017,umlball100,NaN,umlball12,NaN,mathstball,NaN,umlteststatus,NaN,umlptname,NaN,umlptregname,NaN,umlptareaname,NaN,umlpttername,NaN
32370689,00000AC7-CDDE-4C77-B979-8B0351AF1305,2017,mathstball100,None,mathstball12,NaN,rusball,None,mathstteststatus,NaN,mathstptname,NaN,mathstptregname,NaN,mathstptareaname,NaN,mathstpttername,NaN

In [14]:
# delete rows with subject where person didn't take test
df = df[~df.test_status_.isna()]
df.reset_index(drop=True, inplace=True)

In [15]:
df

,outid,year,score100_id,score100,score12_id,score12,score_id,score,test_status_id,test_status_,testcenter_name_id,testcenter_name,test_reg_id,test_reg,test_area_id,test_area,test_ter_id,test_ter
0,00000AC7-CDDE-4C77-B979-8B0351AF1305,2017,ukrball100,161.0,ukrball12,9.0,ukrball,NaN,ukrteststatus,Зараховано,ukrptname,"Одеський навчально-виховний комплекс № 53 ""Заг...",ukrptregname,Одеська область,ukrptareaname,м.Одеса. Малиновський район міста,ukrpttername,Малиновський район міста
1,00000dce-36de-4d58-9dc2-7ffc824f597a,2021,ukrball100,NaN,ukrball12,NaN,ukrball,NaN,ukrteststatus,Не з’явився,ukrptname,Коростенський міський ліцей Житомирської області,ukrptregname,Житомирська область,ukrptareaname,м.Коростень,ukrpttername,м.Коростень
2,00001a8d-fff5-4c7c-bea2-b0157f7c5655,2021,ukrball100,"128,0",ukrball12,6,ukrball,31,ukrteststatus,Зараховано,ukrptname,Черкаська спеціалізована школа І-ІІІ ступенів ...,ukrptregname,Черкаська область,ukrptareaname,м.Черкаси. Придніпровський район міста,ukrpttername,Придніпровський район міста
3,0000268f-9fdd-49b2-9ee2-422778c9c4f1,2016,ukrball100,"160,0",ukrball12,8,ukrball,NaN,ukrteststatus,Отримав результат,ukrptname,"Комунальний заклад ""Харківська загальноосвітня...",ukrptregname,Харківська область,ukrptareaname,м.Харків. Київський район міста,ukrpttername,Київський район міста
4,0000324e-f525-49c4-a963-8df0cc02d6d5,2018,ukrball100,166.0,ukrball12,9,ukrball,69,ukrteststatus,Зараховано,ukrptname,Стрийський коледж Львівського національного аг...,ukrptregname,Львівська область,ukrptareaname,м.Стрий,ukrpttername,м.Стрий
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10597983,fffdecee-6adc-4de9-9f11-3895f6652b99,2021,mathstball100,None,mathstball12,NaN,rusball,None,mathstteststatus,Не з’явився,mathstptname,Хустська спеціалізована школа І-ІІІ ступенів №...,mathstptregname,Закарпатська область,mathstptareaname,м.Хуст,mathstpttername,м.Хуст
10597984,fffed487-0571-4dc2-93e8-c9fbc293c02d,2021,mathstball100,None,mathstball12,NaN,rusball,None,mathstteststatus,Не з’явився,mathstptname,Ніжинський державний університет імені Миколи ...,mathstptregname,Чернігівська область,mathstptareaname,м.Ніжин,mathstpttername,м.Ніжин
10597985,ffff3ae9-5e83-4c92-bdec-d080cc49b1b6,2021,mathstball100,None,mathstball12,NaN,rusball,None,mathstteststatus,Не з’явився,mathstptname,Вище професійне училище №21 м. Миколаєва,mathstptregname,Миколаївська область,mathstptareaname,м.Миколаїв. Заводський район міста,mathstpttername,Заводський район міста
10597986,ffff820f-d5d0-4e38-814e-7e958770e85b,2021,mathstball100,None,mathstball12,NaN,rusball,None,mathstteststatus,Не з’явився,mathstptname,Снігурівська загальноосвітня школа I-III ступе...,mathstptregname,Миколаївська область,mathstptareaname,Снігурівський район,mathstpttername,м.Снігурівка
10597987,fffff6db-6fcc-481f-aa92-49906c0ad1c8,2021,mathstball100,None,mathstball12,NaN,rusball,None,mathstteststatus,Не з’явився,mathstptname,Середня загальноосвітня школа №84 імені Блажен...,mathstptregname,Львівська область,mathstptareaname,м.Львів. Сихівський район міста,mathstpttername,Сихівський район міста

## Add `test_type`+ `test_subject` column

In [16]:
print(df.test_status_id.unique())

['ukrteststatus' 'histteststatus' 'mathteststatus' 'physteststatus'
 'chemteststatus' 'bioteststatus' 'geoteststatus' 'engteststatus'
 'frateststatus' 'deuteststatus' 'spateststatus' 'rusteststatus'
 'umlteststatus' 'mathstteststatus']

In [17]:
test_subject_map = {
    'ukrteststatus': 'ukrtest',
    'histteststatus': 'histtest',
    'mathteststatus': 'mathtest',
    'physteststatus': 'phystest',
    'chemteststatus': 'chemtest',
    'bioteststatus': 'biotest',
    'geoteststatus': 'geotest', 
    'engteststatus': 'engtest',
    'frateststatus': 'fratest', 
    'deuteststatus': 'deutest',
    'spateststatus': 'spatest', 
    'rusteststatus': 'rustest',
    'umlteststatus': 'umltest', 
    'mathstteststatus': 'mathsttest',
}

In [18]:
df.loc[:, 'test_subject'] = df.test_status_id.map(test_subject_map)

/var/folders/cz/wq9d8j_11fx3b8pjjbk7z8br0000gn/T/ipykernel_43555/3063039057.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[:, 'test_subject'] = df.test_status_id.map(test_subject_map)

In [19]:
df.loc[:, 'test_type'] = df.year.map(lambda x: 'EIE' if x < 2022 else 'NMT')

/var/folders/cz/wq9d8j_11fx3b8pjjbk7z8br0000gn/T/ipykernel_43555/4062354352.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[:, 'test_type'] = df.year.map(lambda x: 'EIE' if x < 2022 else 'NMT')

In [20]:
df.head()

,outid,year,score100_id,score100,score12_id,score12,score_id,score,test_status_id,test_status_,testcenter_name_id,testcenter_name,test_reg_id,test_reg,test_area_id,test_area,test_ter_id,test_ter,test_subject,test_type
0,00000AC7-CDDE-4C77-B979-8B0351AF1305,2017,ukrball100,161.0,ukrball12,9.0,ukrball,NaN,ukrteststatus,Зараховано,ukrptname,"Одеський навчально-виховний комплекс № 53 ""Заг...",ukrptregname,Одеська область,ukrptareaname,м.Одеса. Малиновський район міста,ukrpttername,Малиновський район міста,ukrtest,EIE
1,00000dce-36de-4d58-9dc2-7ffc824f597a,2021,ukrball100,NaN,ukrball12,NaN,ukrball,NaN,ukrteststatus,Не з’явився,ukrptname,Коростенський міський ліцей Житомирської області,ukrptregname,Житомирська область,ukrptareaname,м.Коростень,ukrpttername,м.Коростень,ukrtest,EIE
2,00001a8d-fff5-4c7c-bea2-b0157f7c5655,2021,ukrball100,"128,0",ukrball12,6,ukrball,31,ukrteststatus,Зараховано,ukrptname,Черкаська спеціалізована школа І-ІІІ ступенів ...,ukrptregname,Черкаська область,ukrptareaname,м.Черкаси. Придніпровський район міста,ukrpttername,Придніпровський район міста,ukrtest,EIE
3,0000268f-9fdd-49b2-9ee2-422778c9c4f1,2016,ukrball100,"160,0",ukrball12,8,ukrball,NaN,ukrteststatus,Отримав результат,ukrptname,"Комунальний заклад ""Харківська загальноосвітня...",ukrptregname,Харківська область,ukrptareaname,м.Харків. Київський район міста,ukrpttername,Київський район міста,ukrtest,EIE
4,0000324e-f525-49c4-a963-8df0cc02d6d5,2018,ukrball100,166.0,ukrball12,9,ukrball,69,ukrteststatus,Зараховано,ukrptname,Стрийський коледж Львівського національного аг...,ukrptregname,Львівська область,ukrptareaname,м.Стрий,ukrpttername,м.Стрий,ukrtest,EIE

In [21]:
# drop _id col
df.drop(columns=[col for col in df.columns if col.endswith('_id')], inplace=True)

/var/folders/cz/wq9d8j_11fx3b8pjjbk7z8br0000gn/T/ipykernel_43555/3911891021.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(columns=[col for col in df.columns if col.endswith('_id')], inplace=True)

In [22]:
# rename test_status_ to test_status
df.rename(columns={'test_status_': 'test_status'}, inplace=True)

/var/folders/cz/wq9d8j_11fx3b8pjjbk7z8br0000gn/T/ipykernel_43555/2630213758.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={'test_status_': 'test_status'}, inplace=True)

In [23]:
df.tail()

,outid,year,score100,score12,score,test_status,testcenter_name,test_reg,test_area,test_ter,test_subject,test_type
10597983,fffdecee-6adc-4de9-9f11-3895f6652b99,2021,None,NaN,None,Не з’явився,Хустська спеціалізована школа І-ІІІ ступенів №...,Закарпатська область,м.Хуст,м.Хуст,mathsttest,EIE
10597984,fffed487-0571-4dc2-93e8-c9fbc293c02d,2021,None,NaN,None,Не з’явився,Ніжинський державний університет імені Миколи ...,Чернігівська область,м.Ніжин,м.Ніжин,mathsttest,EIE
10597985,ffff3ae9-5e83-4c92-bdec-d080cc49b1b6,2021,None,NaN,None,Не з’явився,Вище професійне училище №21 м. Миколаєва,Миколаївська область,м.Миколаїв. Заводський район міста,Заводський район міста,mathsttest,EIE
10597986,ffff820f-d5d0-4e38-814e-7e958770e85b,2021,None,NaN,None,Не з’явився,Снігурівська загальноосвітня школа I-III ступе...,Миколаївська область,Снігурівський район,м.Снігурівка,mathsttest,EIE
10597987,fffff6db-6fcc-481f-aa92-49906c0ad1c8,2021,None,NaN,None,Не з’явився,Середня загальноосвітня школа №84 імені Блажен...,Львівська область,м.Львів. Сихівський район міста,Сихівський район міста,mathsttest,EIE

## Add `test_center_name` column

In [24]:
# load location dictionary
locations = pd.read_csv('./final_tables/locations.csv', encoding='utf-8', dtype=str)
locations

,regname,areaname,tername,KOATUU_2020,KATOTTG_2023
0,Запорізька область,Мелітопольський район,с.Терпіння,2323085101,UA23080270010078454
1,Хмельницька область,Красилівський район,м.Красилів,6822710100,UA68040210010032567
2,Дніпропетровська область,Петропавлівський район,с.Дмитрівка,1223881501,UA12140170040016918
3,Чернівецька область,м.Чернівці,Шевченківський район міста,7310100000,UA73060610010033137
4,Миколаївська область,Врадіївський район,с.Кумарі,4822383001,UA48080050190079797
...,...,...,...,...,...
29214,США,м.Детройт,м.Детройт,0026010000,OC26010000000000000
29215,Велика Британія,м.Абериствіт,м.Абериствіт,0008030000,OC08030000000000000
29216,США,м.Нью-Йорк,м.Нью-Йорк,0026020000,OC26020000000000000
29217,США,м.Х'юстон,м.Х'юстон,0026040000,OC26040000000000000
29218,Канада,м.Монктон,м.Монктон,0013020000,OC13020000000000000

In [25]:
locations = locations.drop_duplicates(subset=['regname', 'areaname', 'tername'], keep='first')

In [26]:
# rename columns
locations.rename(columns={'regname': 'test_reg', 'areaname': 'test_area', 'tername': 'test_ter'}, inplace=True)
locations.head()

/var/folders/cz/wq9d8j_11fx3b8pjjbk7z8br0000gn/T/ipykernel_43555/3823010113.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  locations.rename(columns={'regname': 'test_reg', 'areaname': 'test_area', 'tername': 'test_ter'}, inplace=True)

,test_reg,test_area,test_ter,KOATUU_2020,KATOTTG_2023
0,Запорізька область,Мелітопольський район,с.Терпіння,2323085101,UA23080270010078454
1,Хмельницька область,Красилівський район,м.Красилів,6822710100,UA68040210010032567
2,Дніпропетровська область,Петропавлівський район,с.Дмитрівка,1223881501,UA12140170040016918
3,Чернівецька область,м.Чернівці,Шевченківський район міста,7310100000,UA73060610010033137
4,Миколаївська область,Врадіївський район,с.Кумарі,4822383001,UA48080050190079797

In [27]:
# add location codifier
df_loc = df.merge(locations[['test_reg', 'test_area', 'test_ter', 'KOATUU_2020']], 
                                    on=['test_reg', 'test_area', 'test_ter'], 
                                    how='left')

df_loc

,outid,year,score100,score12,score,test_status,testcenter_name,test_reg,test_area,test_ter,test_subject,test_type,KOATUU_2020
0,00000AC7-CDDE-4C77-B979-8B0351AF1305,2017,161.0,9.0,NaN,Зараховано,"Одеський навчально-виховний комплекс № 53 ""Заг...",Одеська область,м.Одеса. Малиновський район міста,Малиновський район міста,ukrtest,EIE,5110137300
1,00000dce-36de-4d58-9dc2-7ffc824f597a,2021,NaN,NaN,NaN,Не з’явився,Коростенський міський ліцей Житомирської області,Житомирська область,м.Коростень,м.Коростень,ukrtest,EIE,1810700000
2,00001a8d-fff5-4c7c-bea2-b0157f7c5655,2021,"128,0",6,31,Зараховано,Черкаська спеціалізована школа І-ІІІ ступенів ...,Черкаська область,м.Черкаси. Придніпровський район міста,Придніпровський район міста,ukrtest,EIE,7110136400
3,0000268f-9fdd-49b2-9ee2-422778c9c4f1,2016,"160,0",8,NaN,Отримав результат,"Комунальний заклад ""Харківська загальноосвітня...",Харківська область,м.Харків. Київський район міста,Київський район міста,ukrtest,EIE,6310136600
4,0000324e-f525-49c4-a963-8df0cc02d6d5,2018,166.0,9,69,Зараховано,Стрийський коледж Львівського національного аг...,Львівська область,м.Стрий,м.Стрий,ukrtest,EIE,4611200000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10597983,fffdecee-6adc-4de9-9f11-3895f6652b99,2021,None,NaN,None,Не з’явився,Хустська спеціалізована школа І-ІІІ ступенів №...,Закарпатська область,м.Хуст,м.Хуст,mathsttest,EIE,2110800000
10597984,fffed487-0571-4dc2-93e8-c9fbc293c02d,2021,None,NaN,None,Не з’явився,Ніжинський державний університет імені Миколи ...,Чернігівська область,м.Ніжин,м.Ніжин,mathsttest,EIE,7410400000
10597985,ffff3ae9-5e83-4c92-bdec-d080cc49b1b6,2021,None,NaN,None,Не з’явився,Вище професійне училище №21 м. Миколаєва,Миколаївська область,м.Миколаїв. Заводський район міста,Заводський район міста,mathsttest,EIE,4810136300
10597986,ffff820f-d5d0-4e38-814e-7e958770e85b,2021,None,NaN,None,Не з’явився,Снігурівська загальноосвітня школа I-III ступе...,Миколаївська область,Снігурівський район,м.Снігурівка,mathsttest,EIE,4825710100
10597987,fffff6db-6fcc-481f-aa92-49906c0ad1c8,2021,None,NaN,None,Не з’явився,Середня загальноосвітня школа №84 імені Блажен...,Львівська область,м.Львів. Сихівський район міста,Сихівський район міста,mathsttest,EIE,4610136800

In [28]:
df_loc[df_loc.KOATUU_2020.isna()].year.value_counts()

year
2016    2337784
Name: count, dtype: int64

In [29]:
# delete bad row
df_loc = df_loc[df_loc.outid!='3b07c9d4-067c-47fa-8cf4-8e2097ade009']
df_loc.head()

,outid,year,score100,score12,score,test_status,testcenter_name,test_reg,test_area,test_ter,test_subject,test_type,KOATUU_2020
0,00000AC7-CDDE-4C77-B979-8B0351AF1305,2017,161.0,9.0,NaN,Зараховано,"Одеський навчально-виховний комплекс № 53 ""Заг...",Одеська область,м.Одеса. Малиновський район міста,Малиновський район міста,ukrtest,EIE,5110137300
1,00000dce-36de-4d58-9dc2-7ffc824f597a,2021,NaN,NaN,NaN,Не з’явився,Коростенський міський ліцей Житомирської області,Житомирська область,м.Коростень,м.Коростень,ukrtest,EIE,1810700000
2,00001a8d-fff5-4c7c-bea2-b0157f7c5655,2021,"128,0",6,31,Зараховано,Черкаська спеціалізована школа І-ІІІ ступенів ...,Черкаська область,м.Черкаси. Придніпровський район міста,Придніпровський район міста,ukrtest,EIE,7110136400
3,0000268f-9fdd-49b2-9ee2-422778c9c4f1,2016,"160,0",8,NaN,Отримав результат,"Комунальний заклад ""Харківська загальноосвітня...",Харківська область,м.Харків. Київський район міста,Київський район міста,ukrtest,EIE,6310136600
4,0000324e-f525-49c4-a963-8df0cc02d6d5,2018,166.0,9,69,Зараховано,Стрийський коледж Львівського національного аг...,Львівська область,м.Стрий,м.Стрий,ukrtest,EIE,4611200000

## Add `test_center_id` column

In [30]:
centers_df = pd.read_csv('./final_tables/test_centers_edrpou.csv', encoding='utf-8', dtype=str)
centers_df

,ptname,KOATUU_2020,year,EDRPOU
0,Вище професійне училище №11 м. Вінниці,0510100000,"[2018, 2019, 2020, 2021]",03065891
1,"Відокремлений структурний підрозділ ""Вінницьки...",0510100000,[2021],35725833
2,Відокремлений структурний підрозділ Вінницький...,0510100000,[2021],38814461
3,Вінницький коледж Національного університету х...,0510100000,"[2018, 2019, 2020]",35725833
4,Вінницький коледж будівництва і архітектури Ки...,0510100000,"[2016, 2017, 2018, 2019, 2020]",38814461
...,...,...,...,...
3353,Школа №199 І-ІІІ ступенів Шевченківського райо...,8039100000,[2016],22881923
3354,Школа №25 І-ІІІ ступенів Шевченківського район...,8039100000,"[2018, 2019, 2020, 2021]",22880786
3355,Школа №70 І-ІІІ ступенів Шевченківського район...,8039100000,[2016],22881828
3356,Школа №95 І-ІІІ ступенів Шевченківського район...,8039100000,[2017],26125905
3357,школа І-ІІІ ступенів №175 ім.В Марченка Шевчен...,8039100000,[2021],26125940

In [31]:
centers_df[centers_df.duplicated(subset=['ptname', 'KOATUU_2020'], keep=False)]

Empty DataFrame
Columns: [ptname, KOATUU_2020, year, EDRPOU]
Index: []

In [32]:
centers_df = centers_df.rename(columns={'ptname':'testcenter_name'})

In [33]:
# add edrpou to test centers in students take tests dataset
df_loc = df_loc.merge(
    centers_df[['testcenter_name', 'KOATUU_2020', 'EDRPOU']], 
    on=['testcenter_name','KOATUU_2020'], 
    how='left'
)

df_loc

,outid,year,score100,score12,score,test_status,testcenter_name,test_reg,test_area,test_ter,test_subject,test_type,KOATUU_2020,EDRPOU
0,00000AC7-CDDE-4C77-B979-8B0351AF1305,2017,161.0,9.0,NaN,Зараховано,"Одеський навчально-виховний комплекс № 53 ""Заг...",Одеська область,м.Одеса. Малиновський район міста,Малиновський район міста,ukrtest,EIE,5110137300,20995060
1,00000dce-36de-4d58-9dc2-7ffc824f597a,2021,NaN,NaN,NaN,Не з’явився,Коростенський міський ліцей Житомирської області,Житомирська область,м.Коростень,м.Коростень,ukrtest,EIE,1810700000,22061344
2,00001a8d-fff5-4c7c-bea2-b0157f7c5655,2021,"128,0",6,31,Зараховано,Черкаська спеціалізована школа І-ІІІ ступенів ...,Черкаська область,м.Черкаси. Придніпровський район міста,Придніпровський район міста,ukrtest,EIE,7110136400,25922746
3,0000268f-9fdd-49b2-9ee2-422778c9c4f1,2016,"160,0",8,NaN,Отримав результат,"Комунальний заклад ""Харківська загальноосвітня...",Харківська область,м.Харків. Київський район міста,Київський район міста,ukrtest,EIE,6310136600,24486622
4,0000324e-f525-49c4-a963-8df0cc02d6d5,2018,166.0,9,69,Зараховано,Стрийський коледж Львівського національного аг...,Львівська область,м.Стрий,м.Стрий,ukrtest,EIE,4611200000,34387362
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10597971,fffdecee-6adc-4de9-9f11-3895f6652b99,2021,None,NaN,None,Не з’явився,Хустська спеціалізована школа І-ІІІ ступенів №...,Закарпатська область,м.Хуст,м.Хуст,mathsttest,EIE,2110800000,26325975
10597972,fffed487-0571-4dc2-93e8-c9fbc293c02d,2021,None,NaN,None,Не з’явився,Ніжинський державний університет імені Миколи ...,Чернігівська область,м.Ніжин,м.Ніжин,mathsttest,EIE,7410400000,02125668
10597973,ffff3ae9-5e83-4c92-bdec-d080cc49b1b6,2021,None,NaN,None,Не з’явився,Вище професійне училище №21 м. Миколаєва,Миколаївська область,м.Миколаїв. Заводський район міста,Заводський район міста,mathsttest,EIE,4810136300,05537288
10597974,ffff820f-d5d0-4e38-814e-7e958770e85b,2021,None,NaN,None,Не з’явився,Снігурівська загальноосвітня школа I-III ступе...,Миколаївська область,Снігурівський район,м.Снігурівка,mathsttest,EIE,4825710100,26117159
10597975,fffff6db-6fcc-481f-aa92-49906c0ad1c8,2021,None,NaN,None,Не з’явився,Середня загальноосвітня школа №84 імені Блажен...,Львівська область,м.Львів. Сихівський район міста,Сихівський район міста,mathsttest,EIE,4610136800,20823778

## Post-process and save the table

In [34]:
df_loc.drop(columns=['testcenter_name', 'test_reg', 'test_area', 'test_ter'], inplace=True)

df_loc.loc[:, 'score100'] = df_loc['score100'].astype(str).fillna('')
df_loc.loc[:, 'score'] = df_loc['score'].astype(str).fillna('')
df_loc.loc[:,'score12'] = df_loc['score12'].astype(str).fillna('')

In [35]:
df_loc.loc[:, 'score100'] = df_loc['score100'].str.replace(',', '.')
df_loc.loc[:, 'score'] = df_loc['score'].str.replace(',', '.')
df_loc.loc[:, 'score12'] = df_loc['score12'].str.replace(',', '.')

df_loc.head()

,outid,year,score100,score12,score,test_status,test_subject,test_type,KOATUU_2020,EDRPOU
0,00000AC7-CDDE-4C77-B979-8B0351AF1305,2017,161.0,9.0,NaN,Зараховано,ukrtest,EIE,5110137300,20995060
1,00000dce-36de-4d58-9dc2-7ffc824f597a,2021,NaN,NaN,NaN,Не з’явився,ukrtest,EIE,1810700000,22061344
2,00001a8d-fff5-4c7c-bea2-b0157f7c5655,2021,128.0,6,31,Зараховано,ukrtest,EIE,7110136400,25922746
3,0000268f-9fdd-49b2-9ee2-422778c9c4f1,2016,160.0,8,NaN,Отримав результат,ukrtest,EIE,6310136600,24486622
4,0000324e-f525-49c4-a963-8df0cc02d6d5,2018,166.0,9,69,Зараховано,ukrtest,EIE,4611200000,34387362

In [36]:
df_loc.loc[:, 'score100'] = df_loc['score100'].str.replace('nan', '')
df_loc.loc[:, 'score'] = df_loc['score'].str.replace('nan', '')
df_loc.loc[:, 'score12'] = df_loc['score12'].str.replace('nan', '')

df_loc.head()

,outid,year,score100,score12,score,test_status,test_subject,test_type,KOATUU_2020,EDRPOU
0,00000AC7-CDDE-4C77-B979-8B0351AF1305,2017,161.0,9.0,NaN,Зараховано,ukrtest,EIE,5110137300,20995060
1,00000dce-36de-4d58-9dc2-7ffc824f597a,2021,NaN,NaN,NaN,Не з’явився,ukrtest,EIE,1810700000,22061344
2,00001a8d-fff5-4c7c-bea2-b0157f7c5655,2021,128.0,6,31,Зараховано,ukrtest,EIE,7110136400,25922746
3,0000268f-9fdd-49b2-9ee2-422778c9c4f1,2016,160.0,8,NaN,Отримав результат,ukrtest,EIE,6310136600,24486622
4,0000324e-f525-49c4-a963-8df0cc02d6d5,2018,166.0,9,69,Зараховано,ukrtest,EIE,4611200000,34387362

## Translate test status to english

In [37]:
# unique test status values
df_loc.test_status.unique()

array(['Зараховано', 'Не з’явився', 'Отримав результат',
       'Не подолав поріг', 'Не склав', 'Анульовано', "Не з'явився",
       'Не обрано 100-200',
       'Не зареєстровано для проходження основної сесії'], dtype=object)

In [38]:
translation_map = {
  "Зараховано": "Accepted",
  "Не з’явився": "Absent",
  "Отримав результат": "Received results",
  "Не подолав поріг": "Did not pass the threshold",
  "Не склав": "Failed",
  "Анульовано": "Canceled",
  "Не з'явився": "Absent",
  "Не обрано 100-200": "Not selected 100-200",
  "Не зареєстровано для проходження основної сесії": "Not registered for the main session"
}

df_loc.loc[:, 'test_status'] = df_loc['test_status'].map(translation_map)
df_loc.head()

,outid,year,score100,score12,score,test_status,test_subject,test_type,KOATUU_2020,EDRPOU
0,00000AC7-CDDE-4C77-B979-8B0351AF1305,2017,161.0,9.0,NaN,Accepted,ukrtest,EIE,5110137300,20995060
1,00000dce-36de-4d58-9dc2-7ffc824f597a,2021,NaN,NaN,NaN,Absent,ukrtest,EIE,1810700000,22061344
2,00001a8d-fff5-4c7c-bea2-b0157f7c5655,2021,128.0,6,31,Accepted,ukrtest,EIE,7110136400,25922746
3,0000268f-9fdd-49b2-9ee2-422778c9c4f1,2016,160.0,8,NaN,Received results,ukrtest,EIE,6310136600,24486622
4,0000324e-f525-49c4-a963-8df0cc02d6d5,2018,166.0,9,69,Accepted,ukrtest,EIE,4611200000,34387362

In [39]:
df_loc.shape

(10597976, 10)

## Save DataFrame

In [40]:
# save dataframe
df_loc.to_csv("./final_tables/students_take_tests.csv", index=False)