In [1]:
import pandas as pd
import numpy as np
import importlib
import renaming_dictionaries as renam

In [3]:
eie_orig = pd.read_csv('eie_preprocessed.csv')

/var/folders/cz/wq9d8j_11fx3b8pjjbk7z8br0000gn/T/ipykernel_706/3550493859.py:1: DtypeWarning: Columns (7,8,9,10,11,12,13,14,17,18,19,20,22,26,31,35,39,40,41,43,44,45,46,47,48,49,51,52,53,54,55,56,57,59,60,61,62,63,64,65,67,68,69,70,71,72,74,75,76,77,78,79,81,82,83,84,85,86,88,89,90,91,92,93,95,96,97,98,99,100,102,103,104,105,110,111,128,130,132,134,137,138,143,144,145,146,147,148) have mixed types. Specify dtype option on import or set low_memory=False.
  eie_orig = pd.read_csv('eie_preprocessed.csv')

Класифікатор об'єктів адміністративно-територіального устрою України (КОАТУУ) — структурований перелік усіх адміністративно-територіальних одиниць України, що підтримувався і публікувався державними статистичними відомствами України з 1997 до 2020 року. 

The Classifier of Objects of the Administrative-Territorial Structure of Ukraine (COATSU) is a structured list of all administrative-territorial units of Ukraine, maintained and published by the state statistical agencies of Ukraine from 1997 to 2020.

In [4]:
code2020 = pd.read_excel('KOATUU_26112020.xls',  dtype=str)
code2020

               TE   NP                                       NU
0      0100000000  NaN  АВТОНОМНА РЕСПУБЛІКА КРИМ/М.СІМФЕРОПОЛЬ
1      0110000000  NaN         МІСТА АВТОНОМНОЇ РЕСПУБЛІКИ КРИМ
2      0110100000  NaN                              СІМФЕРОПОЛЬ
3      0110130000  NaN                     РАЙОНИ М.СІМФЕРОПОЛЯ
4      0110136300    Р                              ЗАЛІЗНИЧНИЙ
...           ...  ...                                      ...
39415  8536990504    С                                  КАМИШЛИ
39416  8536990505    С                                ПИРОГОВКА
39417  8536990507    С                                ПОВОРОТНЕ
39418  8536990509    С                                 ФРОНТОВЕ
39419  8536990511    С                                 ФРУКТОВЕ

[39420 rows x 3 columns]

In [5]:
code2020['region_code'] = code2020['TE'].str[:2]
code2020['area_code'] = code2020['TE'].str[2:5]
code2020['local_code'] = code2020['TE'].str[5:]
code2020

,TE,NP,NU,region_code,area_code,local_code
0,0100000000,NaN,АВТОНОМНА РЕСПУБЛІКА КРИМ/М.СІМФЕРОПОЛЬ,01,000,00000
1,0110000000,NaN,МІСТА АВТОНОМНОЇ РЕСПУБЛІКИ КРИМ,01,100,00000
2,0110100000,NaN,СІМФЕРОПОЛЬ,01,101,00000
3,0110130000,NaN,РАЙОНИ М.СІМФЕРОПОЛЯ,01,101,30000
4,0110136300,Р,ЗАЛІЗНИЧНИЙ,01,101,36300
...,...,...,...,...,...,...
39415,8536990504,С,КАМИШЛИ,85,369,90504
39416,8536990505,С,ПИРОГОВКА,85,369,90505
39417,8536990507,С,ПОВОРОТНЕ,85,369,90507
39418,8536990509,С,ФРОНТОВЕ,85,369,90509
39419,8536990511,С,ФРУКТОВЕ,85,369,90511

# Matching regions

In [6]:
code2020['reg_name'] = code2020['NU'].str.split('/').str[0].str.lower().str.capitalize()
code2020[code2020.area_code == '000'][['NU', 'region_code', 'reg_name']]

,NU,region_code,reg_name
0,АВТОНОМНА РЕСПУБЛІКА КРИМ/М.СІМФЕРОПОЛЬ,01,Автономна республіка крим
1328,ВІННИЦЬКА ОБЛАСТЬ/М.ВІННИЦЯ,05,Вінницька область
3508,ВОЛИНСЬКА ОБЛАСТЬ/М.ЛУЦЬК,07,Волинська область
4870,ДНІПРОПЕТРОВСЬКА ОБЛАСТЬ/М.ДНІПРО,12,Дніпропетровська область
6645,ДОНЕЦЬКА ОБЛАСТЬ/М.ДОНЕЦЬК,14,Донецька область
8272,ЖИТОМИРСЬКА ОБЛАСТЬ/М.ЖИТОМИР,18,Житомирська область
10367,ЗАКАРПАТСЬКА ОБЛАСТЬ/М.УЖГОРОД,21,Закарпатська область
11303,ЗАПОРІЗЬКА ОБЛАСТЬ/М.ЗАПОРІЖЖЯ,23,Запорізька область
12483,ІВАНО-ФРАНКІВСЬКА ОБЛАСТЬ/М.ІВАНО-ФРАНКІВСЬК,26,Івано-франківська область
13716,КИЇВСЬКА ОБЛАСТЬ/М.КИЇВ,32,Київська область
15548,КІРОВОГРАДСЬКА ОБЛАСТЬ/М.КРОПИВНИЦЬКИЙ,35,Кіровоградська область
17013,ЛУГАНСЬКА ОБЛАСТЬ/М.ЛУГАНСЬК,44,Луганська область
18187,ЛЬВІВСЬКА ОБЛАСТЬ/М.ЛЬВІВ,46,Львівська область
20787,МИКОЛАЇВСЬКА ОБЛАСТЬ/М.МИКОЛАЇВ,48,Миколаївська область
21951,ОДЕСЬКА ОБЛАСТЬ/М.ОДЕСА,51,Одеська область
23588,ПОЛТАВСЬКА ОБЛАСТЬ/М.ПОЛТАВА,53,Полтавська область
25930,РІВНЕНСЬКА ОБЛАСТЬ/М.РІВНЕ,56,Рівненська область
27273,СУМСЬКА ОБЛАСТЬ/М.СУМИ,59,Сумська область
29114,ТЕРНОПІЛЬСЬКА ОБЛАСТЬ/М.ТЕРНОПІЛЬ,61,Тернопільська область
30650,ХАРКІВСЬКА ОБЛАСТЬ/М.ХАРКІВ,63,Харківська область
32823,ХЕРСОНСЬКА ОБЛАСТЬ/М.ХЕРСОН,65,Херсонська область
33798,ХМЕЛЬНИЦЬКА ОБЛАСТЬ/М.ХМЕЛЬНИЦЬКИЙ,68,Хмельницька область
35623,ЧЕРКАСЬКА ОБЛАСТЬ/М.ЧЕРКАСИ,71,Черкаська область
36952,ЧЕРНІВЕЦЬКА ОБЛАСТЬ/М.ЧЕРНІВЦІ,73,Чернівецька область
37569,ЧЕРНІГІВСЬКА ОБЛАСТЬ/М.ЧЕРНІГІВ,74,Чернігівська область
39363,М.КИЇВ,80,М.київ
39375,М.СЕВАСТОПОЛЬ,85,М.севастополь

Drop '01' and '85' since we don't have them in our dataset

In [7]:
code2020 = code2020[~code2020['region_code'].isin(['01', '85'])]

Drop heneral names that are not connected to specific locations

In [8]:
code2020 = code2020[~code2020['reg_name'].str.lower().str.startswith('міста ')]
code2020 = code2020[~code2020['reg_name'].str.lower().str.startswith('райони ')]
code2020 = code2020[~code2020['reg_name'].str.lower().str.startswith('селища ')]
code2020 = code2020[~code2020['reg_name'].str.lower().str.startswith('населенi ')]
code2020 = code2020[~code2020['reg_name'].str.lower().str.startswith('селища, ')]
code2020 = code2020[~code2020['reg_name'].str.lower().str.startswith('сільради ')]
code2020 = code2020.reset_index(drop=True)

TE - a codifier in KOATUU

NP - category of the object, where С - село, Щ - селище, Т - селище міського типу,                 М - місто, Р - район міста;
NU - name in Ukrainian.

In [11]:
code2020.NP.unique()

array([nan, 'М', 'Т', 'С', 'Щ', 'Р'], dtype=object)

In [10]:
code2020.NP = code2020.NP.str.replace('C', 'С')

In [12]:
code2020.loc[code2020['NP'] == 'М', 'reg_name'] = 'м.' + code2020.loc[code2020['NP'] == 'М', 'reg_name']
code2020.loc[code2020['NP'] == 'С', 'reg_name'] = 'с.' + code2020.loc[code2020['NP'] == 'С', 'reg_name']
code2020.loc[code2020['NP'] == 'Щ', 'reg_name'] = 'с-ще ' + code2020.loc[code2020['NP'] == 'Щ', 'reg_name']
code2020.loc[code2020['NP'] == 'Т', 'reg_name'] = 'смт ' + code2020.loc[code2020['NP'] == 'Т', 'reg_name']

In [13]:
set(code2020[code2020.area_code == '000'].reg_name.str.lower())^set(eie_orig.regname.str.lower())

set()

In [14]:
eie_orig_new = eie_orig.merge(code2020[['region_code']], left_on=eie_orig['regname'].str.lower(), right_on=code2020['reg_name'].str.lower(), how='left')
eie_orig_new = eie_orig_new.drop('key_0', axis=1)
eie_orig_new.head()

,outid,birth,sextypename,regname,areaname,tername,regtypename,eoname,eotypename,eoregname,...,ukrlangball,ukrlangadaptscale,ukrlangptname,ukrlangptregname,ukrlangptareaname,ukrlangpttername,mathdpalevel,testdate,regtypename_detailed,region_code
0,a99c6c63-aa70-4aec-ba42-370f7261e857,1998,чоловіча,Запорізька область,Мелітопольський район,с.Терпіння,Випускник української школи поточного року,"Терпіннівський колегіум ""Джерело"" Мелітопольсь...",колегіум,Запорізька область,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Випускник української школи поточного року,23
1,c3136421-569e-422e-ae8f-41c4c931fd70,1998,жіноча,Хмельницька область,Красилівський район,м.Красилів,Випускник української школи поточного року,Красилівська загальноосвітня школа I-III ступе...,середня загальноосвітня школа,Хмельницька область,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Випускник української школи поточного року,68
2,fbd0e280-4b77-4f34-942d-00bc850c2992,1995,жіноча,Дніпропетровська область,Петропавлівський район,с.Дмитрівка,Випускник минулих років,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Випускник минулих років,12
3,30de395e-7a74-452a-8370-6856d240fbfb,1999,чоловіча,Чернівецька область,м.Чернівці,Шевченківський район міста,Випускник української школи поточного року,Чернівецька спеціалізована школа І-ІІІ ступені...,спеціалізована школа,Чернівецька область,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Випускник української школи поточного року,73
4,52a40c74-374e-4744-bd6f-938ab7a4a641,1997,чоловіча,Миколаївська область,Врадіївський район,с.Кумарі,Учень коледжу закладу професійної (професійно-...,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,48

In [15]:
eie_orig_new[['regname', 'region_code']].value_counts()

regname                    region_code
м.Київ                     80             188894
Дніпропетровська область   12             180166
Львівська область          46             154590
Одеська область            51             136992
Харківська область         63             136857
Київська область           32              94108
Вінницька область          05              93678
Запорізька область         23              92818
Донецька область           14              89858
Івано-Франківська область  26              83696
Рівненська область         56              82740
Полтавська область         53              77373
Закарпатська область       21              75725
Житомирська область        18              74800
Хмельницька область        68              73114
Волинська область          07              70305
Тернопільська область      61              62269
Черкаська область          71              62180
Миколаївська область       48              59911
Сумська область            59              59023
Херсонська область         65              57093
Чернігівська область       74              55417
Чернівецька область        73              55073
Кіровоградська область     35              50958
Луганська область          44              33479
Name: count, dtype: int64

# Matching areas

In [16]:
eie_orig_new['areaname_new'] = eie_orig_new['areaname']

In [17]:
len(eie_orig_new['areaname_new'].unique())

603

In [18]:
eie_orig_new['areaname_new'] = eie_orig_new.apply(lambda row: row['tername'] if ('область' in row['areaname_new'] or 'м.Київ' in row['areaname_new']) else row['areaname_new'], axis=1)

In [19]:
len(eie_orig_new['areaname_new'].unique())

656

In [20]:
dct = {}
for code in code2020.region_code.unique():
    troubles = set(eie_orig_new[(eie_orig_new.region_code == code)&(eie_orig_new.year != 2022)].areaname_new.str.lower())-set(code2020[(code2020.region_code == code)&(code2020.area_code != '000')&(code2020.local_code == '00000')].reg_name.str.lower())
    if troubles:
        dct[code] = troubles
print(dct)

{'12': {'м.дніпро', 'м.дніпродзержинськ', "м.кам'янське", 'м.дніпропетровськ', 'дніпропетровський район', 'м.кривий ріг', 'м.орджонікідзе'}, '14': {'м.димитров', 'м.маріуполь', 'красноармійський район', 'м.красний лиман', 'м.артемівськ', 'володарський район', 'артемівський район', 'першотравневий район', 'м.дзержинськ', 'м.красноармійськ'}, '18': {'м.житомир', 'володарськ-волинський район', 'червоноармійський район'}, '21': {'м.мукачеве'}, '23': {'м.запоріжжя', 'куйбишевський район'}, '32': {'м.переяслав-хмельницький'}, '35': {'м.кропивницький', 'кіровоградський район', 'ульяновський район', 'м.кіровоград'}, '46': {'м.львів'}, '48': {'м.миколаїв', 'жовтневий район'}, '51': {'комінтернівський район', 'м.одеса', 'красноокнянський район', 'котовський район', 'м.котовськ', 'м.іллічівськ', 'фрунзівський район'}, '53': {'м.полтава', 'м.кременчук', 'м.комсомольськ'}, '56': {'м.кузнецовськ'}, '59': {'м.суми'}, '63': {'м.харків'}, '65': {'м.херсон', 'цюрупинський район'}, '71': {'м.черкаси'}, '74': {'щорський район', 'м.чернігів'}, '80': {'голосіївський район міста', 'деснянський район міста', "солом'янський район міста", 'печерський район міста', 'оболонський район міста', 'дніпровський район міста', 'святошинський район міста', 'подільський район міста', 'шевченківський район міста', 'дарницький район міста'}}

In [21]:
for code in renam.dct_rename_area:
    for name in renam.dct_rename_area[code]:
        eie_orig_new.loc[(eie_orig_new.region_code == code) & (eie_orig_new['areaname_new'] == name), 'areaname_new'] = renam.dct_rename_area[code][name]

In [25]:
len(eie_orig_new['areaname_new'].unique())

625

In [23]:
for city in renam.dct_cities:
    code2020.loc[(code2020['local_code'] == '00000') & (code2020['reg_name'].str.lower() == city), 'reg_name'] = renam.dct_cities[city]

In [24]:
for ray in renam.kyiv_dict:
    eie_orig_new.loc[(eie_orig_new.regname == 'м.Київ') & (eie_orig_new.areaname_new.str.lower() == ray), 'areaname_new'] = renam.kyiv_dict[ray]

In [26]:
dct = {}
for code in code2020.region_code.unique():
    troubles = set(eie_orig_new[(eie_orig_new.region_code == code)&(eie_orig_new.year != 2022)].areaname_new.str.lower())-set(code2020[(code2020.region_code == code)&(code2020.area_code != '000')&(code2020.local_code == '00000')].reg_name.str.lower())
    if troubles:
        dct[code] = troubles
print(dct)

{}

In [27]:
eie_orig_new_2 = eie_orig_new.merge(code2020[['area_code']], left_on=[eie_orig_new['region_code'], eie_orig_new['areaname_new'].str.lower()], right_on=[code2020['region_code'], code2020['reg_name'].str.lower()], how='left')
eie_orig_new_2 = eie_orig_new_2.drop(columns = ['key_0', 'key_1'], axis=1)
eie_orig_new_2.head()

,outid,birth,sextypename,regname,areaname,tername,regtypename,eoname,eotypename,eoregname,...,ukrlangptname,ukrlangptregname,ukrlangptareaname,ukrlangpttername,mathdpalevel,testdate,regtypename_detailed,region_code,areaname_new,area_code
0,a99c6c63-aa70-4aec-ba42-370f7261e857,1998,чоловіча,Запорізька область,Мелітопольський район,с.Терпіння,Випускник української школи поточного року,"Терпіннівський колегіум ""Джерело"" Мелітопольсь...",колегіум,Запорізька область,...,NaN,NaN,NaN,NaN,NaN,NaN,Випускник української школи поточного року,23,Мелітопольський район,230
1,c3136421-569e-422e-ae8f-41c4c931fd70,1998,жіноча,Хмельницька область,Красилівський район,м.Красилів,Випускник української школи поточного року,Красилівська загальноосвітня школа I-III ступе...,середня загальноосвітня школа,Хмельницька область,...,NaN,NaN,NaN,NaN,NaN,NaN,Випускник української школи поточного року,68,Красилівський район,227
2,fbd0e280-4b77-4f34-942d-00bc850c2992,1995,жіноча,Дніпропетровська область,Петропавлівський район,с.Дмитрівка,Випускник минулих років,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Випускник минулих років,12,Петропавлівський район,238
3,30de395e-7a74-452a-8370-6856d240fbfb,1999,чоловіча,Чернівецька область,м.Чернівці,Шевченківський район міста,Випускник української школи поточного року,Чернівецька спеціалізована школа І-ІІІ ступені...,спеціалізована школа,Чернівецька область,...,NaN,NaN,NaN,NaN,NaN,NaN,Випускник української школи поточного року,73,м.Чернівці,101
4,52a40c74-374e-4744-bd6f-938ab7a4a641,1997,чоловіча,Миколаївська область,Врадіївський район,с.Кумарі,Учень коледжу закладу професійної (професійно-...,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,48,Врадіївський район,223

# Tername. Renaming

In [28]:
eie_orig_new_2['tername_new'] = eie_orig_new_2['tername']
eie_orig_new_2['tername_new'] = eie_orig_new_2['tername_new'].str.replace(r'\(.*\)', '', regex = True).str.strip()
eie_orig_new_2['tername_new'] = eie_orig_new_2['tername_new'].str.replace(' район міста','')
eie_orig_new_2['tername_new']

0              с.Терпіння
1              м.Красилів
2             с.Дмитрівка
3          Шевченківський
4                с.Кумарі
                ...
2201112       с.Заболотці
2201113       с.Заболотці
2201114       с.Заболотці
2201115       с.Заболотці
2201116        с.Павлівка
Name: tername_new, Length: 2201117, dtype: object

In [29]:
eie_orig_new_2['code'] = eie_orig_new_2['region_code']+eie_orig_new_2['area_code']
code2020['code'] = code2020['region_code']+code2020['area_code']

In [30]:
renaming = pd.read_csv('Renaming.csv')
renaming

,New,Old,areaname,regname,year
0,с.Азовське,с.Луначарське,Бердянський район,Запорізька область,2016
1,с.Армашівка,с.Орджонікідзе,Ширяївський район,Одеська область,2016
2,с.Високе,с.Артемівка,Кегичівський район,Харківська область,2016
3,с.Вишневе,с.Жовтневе,Калинівський район,Вінницька область,2016
4,с.Єрмішкове,с.Дзержинське,Великомихайлівський район,Одеська область,2016
...,...,...,...,...,...
1536,м.Яремче,м.Яремча,м.Яремче,Івано-Франківська область,2006
1537,с.Яромель,с.Йосипівка,Ківерцівський район,Волинська область,1989
1538,с.Ясинівка,с.Ясенівка,Дубенський район,Рівненська область,2013
1539,с.Ятвяги,с.Прибілля,Жидачівський район,Львівська область,2015
1540,с.Яшники,с.Ячники,Лохвицький район,Полтавська область,1995

In [31]:
set(code2020[code2020.area_code == '000'].reg_name.str.lower())^set(renaming.regname.str.lower())

{'м.київ'}

In [32]:
renam_code = renaming.merge(code2020[['region_code']], left_on=renaming['regname'].str.lower(), right_on=code2020['reg_name'].str.lower(), how='left')
renam_code = renam_code.drop('key_0', axis=1)
renam_code

,New,Old,areaname,regname,year,region_code
0,с.Азовське,с.Луначарське,Бердянський район,Запорізька область,2016,23
1,с.Армашівка,с.Орджонікідзе,Ширяївський район,Одеська область,2016,51
2,с.Високе,с.Артемівка,Кегичівський район,Харківська область,2016,63
3,с.Вишневе,с.Жовтневе,Калинівський район,Вінницька область,2016,05
4,с.Єрмішкове,с.Дзержинське,Великомихайлівський район,Одеська область,2016,51
...,...,...,...,...,...,...
1536,м.Яремче,м.Яремча,м.Яремче,Івано-Франківська область,2006,26
1537,с.Яромель,с.Йосипівка,Ківерцівський район,Волинська область,1989,07
1538,с.Ясинівка,с.Ясенівка,Дубенський район,Рівненська область,2013,56
1539,с.Ятвяги,с.Прибілля,Жидачівський район,Львівська область,2015,46
1540,с.Яшники,с.Ячники,Лохвицький район,Полтавська область,1995,53

In [33]:
dct = {}
for code in code2020.region_code.unique():
    troubles = set(renam_code[(renam_code.region_code == code)].areaname.str.lower())-set(code2020[(code2020.region_code == code)&(code2020.area_code != '000')&(code2020.local_code == '00000')].reg_name.str.lower())
    if troubles:
        dct[code] = troubles
print(dct)

{}

In [34]:
renam_code = renam_code.merge(code2020[['area_code']], left_on=[renam_code['region_code'], renam_code['areaname'].str.lower()], right_on=[code2020['region_code'], code2020['reg_name'].str.lower()], how='left')
renam_code = renam_code.drop(columns = ['key_0', 'key_1'], axis=1)
renam_code

,New,Old,areaname,regname,year,region_code,area_code
0,с.Азовське,с.Луначарське,Бердянський район,Запорізька область,2016,23,206
1,с.Армашівка,с.Орджонікідзе,Ширяївський район,Одеська область,2016,51,254
2,с.Високе,с.Артемівка,Кегичівський район,Харківська область,2016,63,231
3,с.Вишневе,с.Жовтневе,Калинівський район,Вінницька область,2016,05,216
4,с.Єрмішкове,с.Дзержинське,Великомихайлівський район,Одеська область,2016,51,216
...,...,...,...,...,...,...,...
1536,м.Яремче,м.Яремча,м.Яремче,Івано-Франківська область,2006,26,110
1537,с.Яромель,с.Йосипівка,Ківерцівський район,Волинська область,1989,07,218
1538,с.Ясинівка,с.Ясенівка,Дубенський район,Рівненська область,2013,56,216
1539,с.Ятвяги,с.Прибілля,Жидачівський район,Львівська область,2015,46,215
1540,с.Яшники,с.Ячники,Лохвицький район,Полтавська область,1995,53,226

In [35]:
renam_code['code'] = renam_code['region_code']+renam_code['area_code']
renam_code

,New,Old,areaname,regname,year,region_code,area_code,code
0,с.Азовське,с.Луначарське,Бердянський район,Запорізька область,2016,23,206,23206
1,с.Армашівка,с.Орджонікідзе,Ширяївський район,Одеська область,2016,51,254,51254
2,с.Високе,с.Артемівка,Кегичівський район,Харківська область,2016,63,231,63231
3,с.Вишневе,с.Жовтневе,Калинівський район,Вінницька область,2016,05,216,05216
4,с.Єрмішкове,с.Дзержинське,Великомихайлівський район,Одеська область,2016,51,216,51216
...,...,...,...,...,...,...,...,...
1536,м.Яремче,м.Яремча,м.Яремче,Івано-Франківська область,2006,26,110,26110
1537,с.Яромель,с.Йосипівка,Ківерцівський район,Волинська область,1989,07,218,07218
1538,с.Ясинівка,с.Ясенівка,Дубенський район,Рівненська область,2013,56,216,56216
1539,с.Ятвяги,с.Прибілля,Жидачівський район,Львівська область,2015,46,215,46215
1540,с.Яшники,с.Ячники,Лохвицький район,Полтавська область,1995,53,226,53226

In [36]:
mapping_dict = {(row['Old'], row['code']): row['New'] for _, row in renam_code.iterrows()}
eie_orig_new_2['tername_new'] = eie_orig_new_2.apply(lambda row: mapping_dict.get((row['tername_new'], row['code']), row['tername_new']), axis=1)

# Reciprocal direction

In [34]:
# importlib.reload(renam)

In [37]:
for code in renam.dct_replace:
    for place in renam.dct_replace[code]:
        eie_orig_new_2.loc[(eie_orig_new_2.code == code) & (eie_orig_new_2['tername_new'] == place), 'tername_new'] = renam.dct_replace[code][place]

In [38]:
code2020

,TE,NP,NU,region_code,area_code,local_code,reg_name,code
0,0500000000,NaN,ВІННИЦЬКА ОБЛАСТЬ/М.ВІННИЦЯ,05,000,00000,Вінницька область,05000
1,0510100000,М,ВІННИЦЯ,05,101,00000,м.Вінниця,05101
2,0510141000,Т,ДЕСНА,05,101,41000,смт Десна,05101
3,0510300000,М,ЖМЕРИНКА,05,103,00000,м.Жмеринка,05103
4,0510390001,С,ЖУКІВЦІ,05,103,90001,с.Жуківці,05103
...,...,...,...,...,...,...,...,...
36847,8038200000,Р,ПЕЧЕРСЬКИЙ,80,382,00000,Печерський,80382
36848,8038500000,Р,ПОДІЛЬСЬКИЙ,80,385,00000,Подільський,80385
36849,8038600000,Р,СВЯТОШИНСЬКИЙ,80,386,00000,Святошинський,80386
36850,8038900000,Р,СОЛОМ'ЯНСЬКИЙ,80,389,00000,Солом'янський,80389
36851,8039100000,Р,ШЕВЧЕНКІВСЬКИЙ,80,391,00000,Шевченківський,80391

In [39]:
def change_area_code(old_code, place, code, dataset):
    dataset.loc[(dataset.code == old_code)&(dataset['tername_new'] == place), 'area_code'] = code[2:]
    dataset.loc[(dataset.code == old_code)&(dataset['tername_new'] == place), 'code'] = code
    values = code2020.loc[(code2020.code == code)&(code2020.local_code == '00000'), 'reg_name'].unique()
    if len(values) == 1:
        dataset.loc[(dataset.code == code)&(dataset['tername_new'] == place), 'areaname_new'] = values[0]
    else:
        raise Exception(f'More than one value:{old_code}, {place}, {code}, {values}')

In [40]:
for item in renam.place_change:
    change_area_code(item[0], item[1], item[2], eie_orig_new_2)

In [41]:
for cod in eie_orig_new_2.code.unique():
    troubles = set(eie_orig_new_2[(eie_orig_new_2.code == cod)&(eie_orig_new_2.year != 2022)].tername_new.str.lower())-set(code2020[code2020.code == cod].reg_name.str.lower())
    if troubles:
        print(f'{repr(cod)}:{troubles},')

'51105':{'с-ще повстанське'},

In [42]:
for code in renam.dct_replace:
    for place in renam.dct_replace[code]:
        eie_orig_new_2.loc[(eie_orig_new_2.code == code) & (eie_orig_new_2['tername_new'] == place), 'tername_new'] = renam.dct_replace[code][place]

# Create full codifier for 2016-2021

In [43]:
eie_orig_new_3 = eie_orig_new_2.merge(code2020[['local_code']], left_on=[eie_orig_new_2['region_code'], eie_orig_new_2['area_code'], eie_orig_new_2['tername_new'].str.lower()], right_on=[code2020['region_code'], code2020['area_code'], code2020['reg_name'].str.lower()], how='left')
eie_orig_new_3 = eie_orig_new_3.drop(columns = ['key_0', 'key_1', 'key_2'], axis=1)
eie_orig_new_3.head()

,outid,birth,sextypename,regname,areaname,tername,regtypename,eoname,eotypename,eoregname,...,ukrlangpttername,mathdpalevel,testdate,regtypename_detailed,region_code,areaname_new,area_code,tername_new,code,local_code
0,a99c6c63-aa70-4aec-ba42-370f7261e857,1998,чоловіча,Запорізька область,Мелітопольський район,с.Терпіння,Випускник української школи поточного року,"Терпіннівський колегіум ""Джерело"" Мелітопольсь...",колегіум,Запорізька область,...,NaN,NaN,NaN,Випускник української школи поточного року,23,Мелітопольський район,230,с.Терпіння,23230,85101
1,c3136421-569e-422e-ae8f-41c4c931fd70,1998,жіноча,Хмельницька область,Красилівський район,м.Красилів,Випускник української школи поточного року,Красилівська загальноосвітня школа I-III ступе...,середня загальноосвітня школа,Хмельницька область,...,NaN,NaN,NaN,Випускник української школи поточного року,68,Красилівський район,227,м.Красилів,68227,10100
2,fbd0e280-4b77-4f34-942d-00bc850c2992,1995,жіноча,Дніпропетровська область,Петропавлівський район,с.Дмитрівка,Випускник минулих років,NaN,NaN,NaN,...,NaN,NaN,NaN,Випускник минулих років,12,Петропавлівський район,238,с.Дмитрівка,12238,81501
3,30de395e-7a74-452a-8370-6856d240fbfb,1999,чоловіча,Чернівецька область,м.Чернівці,Шевченківський район міста,Випускник української школи поточного року,Чернівецька спеціалізована школа І-ІІІ ступені...,спеціалізована школа,Чернівецька область,...,NaN,NaN,NaN,Випускник української школи поточного року,73,м.Чернівці,101,м.Чернівці,73101,00000
4,52a40c74-374e-4744-bd6f-938ab7a4a641,1997,чоловіча,Миколаївська область,Врадіївський район,с.Кумарі,Учень коледжу закладу професійної (професійно-...,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,48,Врадіївський район,223,с.Кумарі,48223,83001

In [44]:
eie_orig_new_3['KOATUU_2020'] = eie_orig_new_3['region_code']+eie_orig_new_3['area_code']+eie_orig_new_3['local_code']
eie_orig_new_3.head()

,outid,birth,sextypename,regname,areaname,tername,regtypename,eoname,eotypename,eoregname,...,mathdpalevel,testdate,regtypename_detailed,region_code,areaname_new,area_code,tername_new,code,local_code,KOATUU_2020
0,a99c6c63-aa70-4aec-ba42-370f7261e857,1998,чоловіча,Запорізька область,Мелітопольський район,с.Терпіння,Випускник української школи поточного року,"Терпіннівський колегіум ""Джерело"" Мелітопольсь...",колегіум,Запорізька область,...,NaN,NaN,Випускник української школи поточного року,23,Мелітопольський район,230,с.Терпіння,23230,85101,2323085101
1,c3136421-569e-422e-ae8f-41c4c931fd70,1998,жіноча,Хмельницька область,Красилівський район,м.Красилів,Випускник української школи поточного року,Красилівська загальноосвітня школа I-III ступе...,середня загальноосвітня школа,Хмельницька область,...,NaN,NaN,Випускник української школи поточного року,68,Красилівський район,227,м.Красилів,68227,10100,6822710100
2,fbd0e280-4b77-4f34-942d-00bc850c2992,1995,жіноча,Дніпропетровська область,Петропавлівський район,с.Дмитрівка,Випускник минулих років,NaN,NaN,NaN,...,NaN,NaN,Випускник минулих років,12,Петропавлівський район,238,с.Дмитрівка,12238,81501,1223881501
3,30de395e-7a74-452a-8370-6856d240fbfb,1999,чоловіча,Чернівецька область,м.Чернівці,Шевченківський район міста,Випускник української школи поточного року,Чернівецька спеціалізована школа І-ІІІ ступені...,спеціалізована школа,Чернівецька область,...,NaN,NaN,Випускник української школи поточного року,73,м.Чернівці,101,м.Чернівці,73101,00000,7310100000
4,52a40c74-374e-4744-bd6f-938ab7a4a641,1997,чоловіча,Миколаївська область,Врадіївський район,с.Кумарі,Учень коледжу закладу професійної (професійно-...,NaN,NaN,NaN,...,NaN,NaN,NaN,48,Врадіївський район,223,с.Кумарі,48223,83001,4822383001

check na

In [45]:
sum(eie_orig_new_3[eie_orig_new_3.year !=2022].KOATUU_2020.isna())

0

https://zakon.rada.gov.ua/laws/show/1037-19#Text

# Match with the new system of code2020

load comparison table

In [46]:
comparison = pd.read_excel('Comparison table.xlsx',  dtype=str, skiprows=2)
comparison

,Кодифікатор,Код об'єкта КОАТУУ,Категорія об’єкта,Назва об’єкта
0,UA01000000000013043,0100000000,О,Автономна Республіка Крим
1,UA01020000000022387,0120400000,Р,Бахчисарайський
2,UA01020010000048857,8536990200,Н,Андріївська
3,UA01020010010075540,8536990201,С,Андріївка
4,UA01020010020030666,8536990203,Х,Сонячний
...,...,...,...,...
31753,UA85000000000065278,8500000000,К,Севастополь
31754,UA85000000000155841,8536300000,В,Балаклавський
31755,UA85000000000259923,8536400000,В,Гагарінський
31756,UA85000000000334608,8536600000,В,Ленінський
31757,UA85000000000449437,8536900000,В,Нахімовський

In [47]:
comparison.rename(columns = {'Кодифікатор':'KATOTTG_2023',"Код об'єкта КОАТУУ ":'KOATUU_2020','Категорія об’єкта':'category', 'Назва об’єкта':'name'}, inplace=True)
comparison

              KATOTTG_2023 KOATUU_2020 category                       name
0      UA01000000000013043  0100000000        О  Автономна Республіка Крим
1      UA01020000000022387  0120400000        Р            Бахчисарайський
2      UA01020010000048857  8536990200        Н               Андріївська
3      UA01020010010075540  8536990201        С                  Андріївка
4      UA01020010020030666  8536990203        Х                   Сонячний
...                    ...         ...      ...                        ...
31753  UA85000000000065278  8500000000        К                Севастополь
31754  UA85000000000155841  8536300000        В              Балаклавський
31755  UA85000000000259923  8536400000        В               Гагарінський
31756  UA85000000000334608  8536600000        В                 Ленінський
31757  UA85000000000449437  8536900000        В               Нахімовський

[31758 rows x 4 columns]

In [48]:
comparison_loc = comparison[comparison.category.isin(['С', 'М', 'В', 'Т', 'Х'])]

In [49]:
eie_orig_new_3.loc[(eie_orig_new_3.KOATUU_2020 == '5120280501'), 'local_code'] = '80401'
eie_orig_new_3.loc[(eie_orig_new_3.KOATUU_2020 == '5120280501'), 'KOATUU_2020'] = '5120280401'

In [50]:
eie_orig_new_4 = eie_orig_new_3.merge(comparison_loc[['KATOTTG_2023']], left_on=[eie_orig_new_3['KOATUU_2020']], right_on=[comparison_loc['KOATUU_2020']], how='left')
eie_orig_new_4 = eie_orig_new_4.drop(columns = ['key_0'], axis=1)
eie_orig_new_4.head()

,outid,birth,sextypename,regname,areaname,tername,regtypename,eoname,eotypename,eoregname,...,testdate,regtypename_detailed,region_code,areaname_new,area_code,tername_new,code,local_code,KOATUU_2020,KATOTTG_2023
0,a99c6c63-aa70-4aec-ba42-370f7261e857,1998,чоловіча,Запорізька область,Мелітопольський район,с.Терпіння,Випускник української школи поточного року,"Терпіннівський колегіум ""Джерело"" Мелітопольсь...",колегіум,Запорізька область,...,NaN,Випускник української школи поточного року,23,Мелітопольський район,230,с.Терпіння,23230,85101,2323085101,UA23080270010078454
1,c3136421-569e-422e-ae8f-41c4c931fd70,1998,жіноча,Хмельницька область,Красилівський район,м.Красилів,Випускник української школи поточного року,Красилівська загальноосвітня школа I-III ступе...,середня загальноосвітня школа,Хмельницька область,...,NaN,Випускник української школи поточного року,68,Красилівський район,227,м.Красилів,68227,10100,6822710100,UA68040210010032567
2,fbd0e280-4b77-4f34-942d-00bc850c2992,1995,жіноча,Дніпропетровська область,Петропавлівський район,с.Дмитрівка,Випускник минулих років,NaN,NaN,NaN,...,NaN,Випускник минулих років,12,Петропавлівський район,238,с.Дмитрівка,12238,81501,1223881501,UA12140170040016918
3,30de395e-7a74-452a-8370-6856d240fbfb,1999,чоловіча,Чернівецька область,м.Чернівці,Шевченківський район міста,Випускник української школи поточного року,Чернівецька спеціалізована школа І-ІІІ ступені...,спеціалізована школа,Чернівецька область,...,NaN,Випускник української школи поточного року,73,м.Чернівці,101,м.Чернівці,73101,00000,7310100000,UA73060610010033137
4,52a40c74-374e-4744-bd6f-938ab7a4a641,1997,чоловіча,Миколаївська область,Врадіївський район,с.Кумарі,Учень коледжу закладу професійної (професійно-...,NaN,NaN,NaN,...,NaN,NaN,48,Врадіївський район,223,с.Кумарі,48223,83001,4822383001,UA48080050190079797

In [51]:
eie_orig_new_4[(eie_orig_new_4.year !=2022)&(eie_orig_new_4.KATOTTG_2023.isna())].KOATUU_2020.unique()

array([], dtype=object)

In [52]:
eie_orig_new_4 = eie_orig_new_4.merge(comparison_loc[['category']],left_on=[eie_orig_new_4['KATOTTG_2023']], right_on=[comparison_loc['KATOTTG_2023']], how='left')
eie_orig_new_4 = eie_orig_new_4.drop(columns = ['key_0'], axis=1)
eie_orig_new_4.head()

,outid,birth,sextypename,regname,areaname,tername,regtypename,eoname,eotypename,eoregname,...,regtypename_detailed,region_code,areaname_new,area_code,tername_new,code,local_code,KOATUU_2020,KATOTTG_2023,category
0,a99c6c63-aa70-4aec-ba42-370f7261e857,1998,чоловіча,Запорізька область,Мелітопольський район,с.Терпіння,Випускник української школи поточного року,"Терпіннівський колегіум ""Джерело"" Мелітопольсь...",колегіум,Запорізька область,...,Випускник української школи поточного року,23,Мелітопольський район,230,с.Терпіння,23230,85101,2323085101,UA23080270010078454,С
1,c3136421-569e-422e-ae8f-41c4c931fd70,1998,жіноча,Хмельницька область,Красилівський район,м.Красилів,Випускник української школи поточного року,Красилівська загальноосвітня школа I-III ступе...,середня загальноосвітня школа,Хмельницька область,...,Випускник української школи поточного року,68,Красилівський район,227,м.Красилів,68227,10100,6822710100,UA68040210010032567,М
2,fbd0e280-4b77-4f34-942d-00bc850c2992,1995,жіноча,Дніпропетровська область,Петропавлівський район,с.Дмитрівка,Випускник минулих років,NaN,NaN,NaN,...,Випускник минулих років,12,Петропавлівський район,238,с.Дмитрівка,12238,81501,1223881501,UA12140170040016918,С
3,30de395e-7a74-452a-8370-6856d240fbfb,1999,чоловіча,Чернівецька область,м.Чернівці,Шевченківський район міста,Випускник української школи поточного року,Чернівецька спеціалізована школа І-ІІІ ступені...,спеціалізована школа,Чернівецька область,...,Випускник української школи поточного року,73,м.Чернівці,101,м.Чернівці,73101,00000,7310100000,UA73060610010033137,М
4,52a40c74-374e-4744-bd6f-938ab7a4a641,1997,чоловіча,Миколаївська область,Врадіївський район,с.Кумарі,Учень коледжу закладу професійної (професійно-...,NaN,NaN,NaN,...,NaN,48,Врадіївський район,223,с.Кумарі,48223,83001,4822383001,UA48080050190079797,С

In [53]:
eie_orig_new_4[(eie_orig_new_4.year !=2022)].category.unique()

array(['С', 'М', 'В', 'Т', 'Х'], dtype=object)

«М» – міста;

«Т» – селища міського типу;

«С» – села; 

«Х» – селища; 

«В» – райони в містах.

In [54]:
cat_map = {'С':'small village', 'М':'city', 'В':'district in city', 'Т':'urban-type settlement', 'Х':'large village'}
eie_orig_new_4['category'].replace(cat_map, inplace= True)

In [55]:
eie_orig_new_4[(eie_orig_new_4.year !=2022)].category.unique()

array(['small village', 'city', 'district in city',
       'urban-type settlement', 'large village'], dtype=object)

In [57]:
eie_orig_new_4.to_csv('eie_2016_2021_preprocessed.csv', index=False)

# 2022

In [2]:
eie_orig_new_4 = pd.read_csv('eie_2016_2021_preprocessed.csv')

/var/folders/cz/wq9d8j_11fx3b8pjjbk7z8br0000gn/T/ipykernel_2174/945775215.py:1: DtypeWarning: Columns (7,8,9,10,11,12,13,14,17,18,19,20,22,26,31,35,39,40,41,43,44,45,46,47,48,49,51,52,53,54,55,56,57,59,60,61,62,63,64,65,67,68,69,70,71,72,74,75,76,77,78,79,81,82,83,84,85,86,88,89,90,91,92,93,95,96,97,98,99,100,102,103,104,105,110,111,128,130,132,134,137,138,143,144,145,146,147,148) have mixed types. Specify dtype option on import or set low_memory=False.
  eie_orig_new_4 = pd.read_csv('eie_2016_2021_preprocessed.csv')

In [3]:
eie_orig_new_4

,outid,birth,sextypename,regname,areaname,tername,regtypename,eoname,eotypename,eoregname,...,regtypename_detailed,region_code,areaname_new,area_code,tername_new,code,local_code,KOATUU_2020,KATOTTG_2023,category
0,a99c6c63-aa70-4aec-ba42-370f7261e857,1998,чоловіча,Запорізька область,Мелітопольський район,с.Терпіння,Випускник української школи поточного року,"Терпіннівський колегіум ""Джерело"" Мелітопольсь...",колегіум,Запорізька область,...,Випускник української школи поточного року,23,Мелітопольський район,230.0,с.Терпіння,23230.0,85101.0,2.323085e+09,UA23080270010078454,small village
1,c3136421-569e-422e-ae8f-41c4c931fd70,1998,жіноча,Хмельницька область,Красилівський район,м.Красилів,Випускник української школи поточного року,Красилівська загальноосвітня школа I-III ступе...,середня загальноосвітня школа,Хмельницька область,...,Випускник української школи поточного року,68,Красилівський район,227.0,м.Красилів,68227.0,10100.0,6.822710e+09,UA68040210010032567,city
2,fbd0e280-4b77-4f34-942d-00bc850c2992,1995,жіноча,Дніпропетровська область,Петропавлівський район,с.Дмитрівка,Випускник минулих років,NaN,NaN,NaN,...,Випускник минулих років,12,Петропавлівський район,238.0,с.Дмитрівка,12238.0,81501.0,1.223882e+09,UA12140170040016918,small village
3,30de395e-7a74-452a-8370-6856d240fbfb,1999,чоловіча,Чернівецька область,м.Чернівці,Шевченківський район міста,Випускник української школи поточного року,Чернівецька спеціалізована школа І-ІІІ ступені...,спеціалізована школа,Чернівецька область,...,Випускник української школи поточного року,73,м.Чернівці,101.0,м.Чернівці,73101.0,0.0,7.310100e+09,UA73060610010033137,city
4,52a40c74-374e-4744-bd6f-938ab7a4a641,1997,чоловіча,Миколаївська область,Врадіївський район,с.Кумарі,Учень коледжу закладу професійної (професійно-...,NaN,NaN,NaN,...,NaN,48,Врадіївський район,223.0,с.Кумарі,48223.0,83001.0,4.822383e+09,UA48080050190079797,small village
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2202411,6cbe3454-80f0-42b5-8d6d-c2ead687d804,2005,чоловіча,Волинська область,Володимирський район,с.Заболотці,Випускник української школи поточного року,Заболотцівський ліцей Литовезької сільської ра...,середня загальноосвітня школа,Волинська область,...,Випускник української школи поточного року,7,Володимирський район,NaN,с.Заболотці,NaN,NaN,NaN,NaN,NaN
2202412,b897557b-c01b-49d4-8624-b351aaafe5ff,2005,жіноча,Волинська область,Володимирський район,с.Заболотці,Випускник української школи поточного року,Заболотцівський ліцей Литовезької сільської ра...,середня загальноосвітня школа,Волинська область,...,Випускник української школи поточного року,7,Володимирський район,NaN,с.Заболотці,NaN,NaN,NaN,NaN,NaN
2202413,dcec644b-dcec-47ee-9971-6beebd1a929b,2005,чоловіча,Волинська область,Володимирський район,с.Заболотці,Випускник української школи поточного року,Заболотцівський ліцей Литовезької сільської ра...,середня загальноосвітня школа,Волинська область,...,Випускник української школи поточного року,7,Володимирський район,NaN,с.Заболотці,NaN,NaN,NaN,NaN,NaN
2202414,cb4156bb-a624-4274-9d38-28be3096f6b9,2004,жіноча,Волинська область,Володимирський район,с.Заболотці,Випускник української школи поточного року,Заболотцівський ліцей Литовезької сільської ра...,середня загальноосвітня школа,Волинська область,...,Випускник української школи поточного року,7,Володимирський район,NaN,с.Заболотці,NaN,NaN,NaN,NaN,NaN
2202415,7514327a-0831-4adc-8277-41d74e543884,2005,жіноча,Херсонська область,Каховський район,с.Павлівка (Присиваська),Випускник української школи поточного року,Павлівська загальноосвітня школа I-III ступені...,середня загальноосвітня школа,Херсонська область,...,Випускник української школи поточного року,65,Каховський район,235.0,с.Павлівка,65235.0,NaN,NaN,NaN,NaN

In [4]:
cols = ['region_code', 'area_code','code','local_code',	'KOATUU_2020', 'KATOTTG_2023', 'category']

for item in cols:
    eie_orig_new_4.loc[(eie_orig_new_4.year == 2022), item] = None

In [5]:
eie_orig_new_4[(eie_orig_new_4.year ==2022)].KOATUU_2020.unique()

array([nan])

In [6]:
code2022 = pd.read_excel('Codifiers2022.xlsx',  dtype=str, skiprows=2,skipfooter=3)
code2022

,Перший рівень,Другий рівень,Третій рівень,Четвертий рівень,Додатковий рівень,Категорія об’єкта,Назва об’єкта
0,UA01000000000013043,NaN,NaN,NaN,NaN,O,Автономна Республіка Крим
1,UA01000000000013043,UA01020000000022387,NaN,NaN,NaN,P,Бахчисарайський
2,UA01000000000013043,UA01020000000022387,UA01020010000048857,NaN,NaN,H,Андріївська
3,UA01000000000013043,UA01020000000022387,UA01020010000048857,UA01020010010075540,NaN,C,Андріївка
4,UA01000000000013043,UA01020000000022387,UA01020010000048857,UA01020010020030666,NaN,X,Сонячний
...,...,...,...,...,...,...,...
31746,UA85000000000065278,NaN,NaN,NaN,NaN,K,Севастополь
31747,UA85000000000065278,UA85000000000065278,UA85000000000065278,UA85000000000065278,UA85000000000155841,B,Балаклавський
31748,UA85000000000065278,UA85000000000065278,UA85000000000065278,UA85000000000065278,UA85000000000259923,B,Гагарінський
31749,UA85000000000065278,UA85000000000065278,UA85000000000065278,UA85000000000065278,UA85000000000334608,B,Ленінський
31750,UA85000000000065278,UA85000000000065278,UA85000000000065278,UA85000000000065278,UA85000000000449437,B,Нахімовський

In [7]:
code2022.columns

Index(['Перший рівень', 'Другий рівень', 'Третій рівень', 'Четвертий рівень',
       'Додатковий рівень', 'Категорія об’єкта', 'Назва об’єкта'],
      dtype='object')

In [8]:
code2022.rename(columns = {'Перший рівень':'first_level','Другий рівень':'second_level','Третій рівень':'third_level', 'Четвертий рівень':'fourth_level',
       'Додатковий рівень':'additional_level', 'Категорія об’єкта':'category','Назва об’єкта':'name'}, inplace=True)
code2022

,first_level,second_level,third_level,fourth_level,additional_level,category,name
0,UA01000000000013043,NaN,NaN,NaN,NaN,O,Автономна Республіка Крим
1,UA01000000000013043,UA01020000000022387,NaN,NaN,NaN,P,Бахчисарайський
2,UA01000000000013043,UA01020000000022387,UA01020010000048857,NaN,NaN,H,Андріївська
3,UA01000000000013043,UA01020000000022387,UA01020010000048857,UA01020010010075540,NaN,C,Андріївка
4,UA01000000000013043,UA01020000000022387,UA01020010000048857,UA01020010020030666,NaN,X,Сонячний
...,...,...,...,...,...,...,...
31746,UA85000000000065278,NaN,NaN,NaN,NaN,K,Севастополь
31747,UA85000000000065278,UA85000000000065278,UA85000000000065278,UA85000000000065278,UA85000000000155841,B,Балаклавський
31748,UA85000000000065278,UA85000000000065278,UA85000000000065278,UA85000000000065278,UA85000000000259923,B,Гагарінський
31749,UA85000000000065278,UA85000000000065278,UA85000000000065278,UA85000000000065278,UA85000000000334608,B,Ленінський
31750,UA85000000000065278,UA85000000000065278,UA85000000000065278,UA85000000000065278,UA85000000000449437,B,Нахімовський

In [9]:
code2022['name'] = code2022['name'].str.replace('’', "'")

##  Matching regions 2022

In [10]:
code2022['reg_name']= code2022['name'] 
code2022['reg_name']= code2022['reg_name'].str.strip()
code2022

,first_level,second_level,third_level,fourth_level,additional_level,category,name,reg_name
0,UA01000000000013043,NaN,NaN,NaN,NaN,O,Автономна Республіка Крим,Автономна Республіка Крим
1,UA01000000000013043,UA01020000000022387,NaN,NaN,NaN,P,Бахчисарайський,Бахчисарайський
2,UA01000000000013043,UA01020000000022387,UA01020010000048857,NaN,NaN,H,Андріївська,Андріївська
3,UA01000000000013043,UA01020000000022387,UA01020010000048857,UA01020010010075540,NaN,C,Андріївка,Андріївка
4,UA01000000000013043,UA01020000000022387,UA01020010000048857,UA01020010020030666,NaN,X,Сонячний,Сонячний
...,...,...,...,...,...,...,...,...
31746,UA85000000000065278,NaN,NaN,NaN,NaN,K,Севастополь,Севастополь
31747,UA85000000000065278,UA85000000000065278,UA85000000000065278,UA85000000000065278,UA85000000000155841,B,Балаклавський,Балаклавський
31748,UA85000000000065278,UA85000000000065278,UA85000000000065278,UA85000000000065278,UA85000000000259923,B,Гагарінський,Гагарінський
31749,UA85000000000065278,UA85000000000065278,UA85000000000065278,UA85000000000065278,UA85000000000334608,B,Ленінський,Ленінський
31750,UA85000000000065278,UA85000000000065278,UA85000000000065278,UA85000000000065278,UA85000000000449437,B,Нахімовський,Нахімовський

In [11]:
code2022 = code2022[~code2022['first_level'].str.startswith(('UA01', 'UA85'))]

In [12]:
len(code2022.first_level.unique())

25

In [13]:
code2022.category.unique()

array(['O', 'P', 'H', 'C', 'M', 'T', 'X', 'B', 'K'], dtype=object)

In [14]:
code2022.loc[code2022['category'] == 'O', 'reg_name'] = code2022.loc[code2022['category'] == 'O', 'reg_name']+' область'
code2022.loc[code2022['category'] == 'P', 'reg_name'] = code2022.loc[code2022['category'] =='P', 'reg_name']+' район'
code2022.loc[code2022['category'] == 'C', 'reg_name'] = 'с.' + code2022.loc[code2022['category'] == 'C', 'reg_name']
code2022.loc[code2022['category'] == 'X', 'reg_name'] = 'с-ще ' + code2022.loc[code2022['category'] == 'X', 'reg_name']
code2022.loc[code2022['category'] == 'M', 'reg_name'] = 'м.' + code2022.loc[code2022['category'] == 'M', 'reg_name']
code2022.loc[code2022['category'] == 'T', 'reg_name'] = 'смт ' + code2022.loc[code2022['category'] == 'T', 'reg_name']
code2022.loc[code2022['category'] == 'K', 'reg_name'] = 'м.'  + code2022.loc[code2022['category'] == 'K', 'reg_name']

In [15]:
set(code2022[code2022.category.isin(['O','K'])].reg_name.str.lower())^set(eie_orig_new_4.regname.str.lower())

set()

In [117]:
eie_orig_new_5 = eie_orig_new_4

In [118]:
eie_orig_new_5['region_code_2023'] = np.nan

In [119]:
for reg in code2022[code2022.category.isin(['O','K'])].reg_name.str.lower().unique():
    values = code2022.loc[code2022.reg_name.str.lower() == reg, 'first_level'].unique()
    if len(values) == 1:
        eie_orig_new_5.loc[(eie_orig_new_5.regname.str.lower()==reg), 'region_code_2023'] = values[0]
    else:
        raise Exception(f'More than one value:{reg}, {values}')

In [120]:
eie_orig_new_5

,outid,birth,sextypename,regname,areaname,tername,regtypename,eoname,eotypename,eoregname,...,tername_new,code,local_code,KOATUU_2020,KATOTTG_2023,category,region_code_2023,area_code_2023,third_level,third_level_code
0,a99c6c63-aa70-4aec-ba42-370f7261e857,1998,чоловіча,Запорізька область,Мелітопольський район,с.Терпіння,Випускник української школи поточного року,"Терпіннівський колегіум ""Джерело"" Мелітопольсь...",колегіум,Запорізька область,...,с.Терпіння,23230.0,85101.0,2.323085e+09,UA23080270010078454,small village,UA23000000000064947,NaN,NaN,-1
1,c3136421-569e-422e-ae8f-41c4c931fd70,1998,жіноча,Хмельницька область,Красилівський район,м.Красилів,Випускник української школи поточного року,Красилівська загальноосвітня школа I-III ступе...,середня загальноосвітня школа,Хмельницька область,...,м.Красилів,68227.0,10100.0,6.822710e+09,UA68040210010032567,city,UA68000000000099709,NaN,NaN,-1
2,fbd0e280-4b77-4f34-942d-00bc850c2992,1995,жіноча,Дніпропетровська область,Петропавлівський район,с.Дмитрівка,Випускник минулих років,NaN,NaN,NaN,...,с.Дмитрівка,12238.0,81501.0,1.223882e+09,UA12140170040016918,small village,UA12000000000090473,NaN,NaN,-1
3,30de395e-7a74-452a-8370-6856d240fbfb,1999,чоловіча,Чернівецька область,м.Чернівці,Шевченківський район міста,Випускник української школи поточного року,Чернівецька спеціалізована школа І-ІІІ ступені...,спеціалізована школа,Чернівецька область,...,м.Чернівці,73101.0,0.0,7.310100e+09,UA73060610010033137,city,UA73000000000044923,NaN,NaN,-1
4,52a40c74-374e-4744-bd6f-938ab7a4a641,1997,чоловіча,Миколаївська область,Врадіївський район,с.Кумарі,Учень коледжу закладу професійної (професійно-...,NaN,NaN,NaN,...,с.Кумарі,48223.0,83001.0,4.822383e+09,UA48080050190079797,small village,UA48000000000039575,NaN,NaN,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2202411,6cbe3454-80f0-42b5-8d6d-c2ead687d804,2005,чоловіча,Волинська область,Володимирський район,с.Заболотці,Випускник української школи поточного року,Заболотцівський ліцей Литовезької сільської ра...,середня загальноосвітня школа,Волинська область,...,с.Заболотці,NaN,NaN,NaN,UA07020090030023102,None,UA07000000000024379,UA07020000000048211,NaN,-1
2202412,b897557b-c01b-49d4-8624-b351aaafe5ff,2005,жіноча,Волинська область,Володимирський район,с.Заболотці,Випускник української школи поточного року,Заболотцівський ліцей Литовезької сільської ра...,середня загальноосвітня школа,Волинська область,...,с.Заболотці,NaN,NaN,NaN,UA07020090030023102,None,UA07000000000024379,UA07020000000048211,NaN,-1
2202413,dcec644b-dcec-47ee-9971-6beebd1a929b,2005,чоловіча,Волинська область,Володимирський район,с.Заболотці,Випускник української школи поточного року,Заболотцівський ліцей Литовезької сільської ра...,середня загальноосвітня школа,Волинська область,...,с.Заболотці,NaN,NaN,NaN,UA07020090030023102,None,UA07000000000024379,UA07020000000048211,NaN,-1
2202414,cb4156bb-a624-4274-9d38-28be3096f6b9,2004,жіноча,Волинська область,Володимирський район,с.Заболотці,Випускник української школи поточного року,Заболотцівський ліцей Литовезької сільської ра...,середня загальноосвітня школа,Волинська область,...,с.Заболотці,NaN,NaN,NaN,UA07020090030023102,None,UA07000000000024379,UA07020000000048211,NaN,-1
2202415,7514327a-0831-4adc-8277-41d74e543884,2005,жіноча,Херсонська область,Каховський район,с.Павлівка (Присиваська),Випускник української школи поточного року,Павлівська загальноосвітня школа I-III ступені...,середня загальноосвітня школа,Херсонська область,...,с.Павлівка,NaN,NaN,NaN,UA65060050150037522,None,UA65000000000030969,UA65060000000061947,Присиваська,UA65060190000091058

In [121]:
eie_orig_new_5[eie_orig_new_5.year == 2022].regname.unique()

array(['Львівська область', 'Івано-Франківська область',
       'Волинська область', 'Одеська область', 'Кіровоградська область',
       'Рівненська область', 'Миколаївська область', 'Київська область',
       'Закарпатська область', 'Вінницька область', 'м.Київ',
       'Донецька область', 'Херсонська область', 'Житомирська область',
       'Запорізька область', 'Дніпропетровська область',
       'Тернопільська область', 'Чернівецька область',
       'Чернігівська область', 'Полтавська область', 'Черкаська область',
       'Харківська область', 'Луганська область', 'Сумська область',
       'Хмельницька область'], dtype=object)

In [122]:
len(eie_orig_new_5[eie_orig_new_5.year == 2022].region_code_2023.unique())

25

## Matching areas 2022

In [123]:
troubles = {}
for reg in eie_orig_new_5[eie_orig_new_5.year == 2022].region_code_2023.unique():
    trouble = set(eie_orig_new_5[(eie_orig_new_5.region_code_2023 == reg)&(eie_orig_new_5.year == 2022)].areaname_new.str.lower())-set(code2022[(code2022.first_level == reg)&(code2022.category.isin(['P','B']))].reg_name.str.lower())
    if trouble:
        troubles[reg] = trouble
troubles

{}

In [282]:
# importlib.reload(renam)

In [124]:
for code in renam.dct_rename_area_2022:
    for name in renam.dct_rename_area_2022[code]:
        eie_orig_new_5.loc[(eie_orig_new_5.region_code_2023 == code) & (eie_orig_new_5['areaname_new'].str.lower() == name.lower())&(eie_orig_new_5.year == 2022), 'areaname_new'] = renam.dct_rename_area_2022[code][name]

In [125]:
for reg in eie_orig_new_5[eie_orig_new_5.year == 2022].region_code_2023.unique():
    for area in eie_orig_new_5[(eie_orig_new_5.region_code_2023 == reg)&(eie_orig_new_5.year == 2022)].areaname_new.str.lower().unique():
        values = code2022.loc[(code2022.first_level == reg)&(code2022.reg_name.str.lower() == area), 'category'].unique()
        if reg == 'UA80000000000093317':
            eie_orig_new_5.loc[(eie_orig_new_5.region_code_2023 == reg)&(eie_orig_new_5.year == 2022)&(eie_orig_new_5.areaname_new.str.lower()==area), 'area_code_2023'] = reg
        elif len(values) == 1:
            if values[0] == 'P':
                value2 = code2022.loc[(code2022.first_level == reg)&(code2022.reg_name.str.lower() == area), 'second_level'].unique()
                if len(value2) == 1:
                    eie_orig_new_5.loc[(eie_orig_new_5.region_code_2023 == reg)&(eie_orig_new_5.year == 2022)&(eie_orig_new_5.areaname_new.str.lower()==area), 'area_code_2023'] = value2[0]
                else:
                    raise Exception(f'More than one value: {reg}, {area}, {value2}')
            if values[0] == 'B':
                value_add = code2022.loc[(code2022.first_level == reg)&(code2022.reg_name.str.lower() == area), 'additional_level'].unique()
                if len(value_add) == 1:
                    eie_orig_new_5.loc[(eie_orig_new_5.region_code_2023 == reg)&(eie_orig_new_5.year == 2022)&(eie_orig_new_5.areaname_new.str.lower()==area), 'area_code_2023'] = value_add[0]
                else:
                    raise Exception(f'More than one value: {reg}, {area}, {value_add}')
        else:
            raise Exception(f'More than one value: {reg}, {area}, {values}')

In [126]:
sum(eie_orig_new_5[eie_orig_new_5.year ==2022].area_code_2023.isna())

0

In [127]:
eie_orig_new_5

,outid,birth,sextypename,regname,areaname,tername,regtypename,eoname,eotypename,eoregname,...,tername_new,code,local_code,KOATUU_2020,KATOTTG_2023,category,region_code_2023,area_code_2023,third_level,third_level_code
0,a99c6c63-aa70-4aec-ba42-370f7261e857,1998,чоловіча,Запорізька область,Мелітопольський район,с.Терпіння,Випускник української школи поточного року,"Терпіннівський колегіум ""Джерело"" Мелітопольсь...",колегіум,Запорізька область,...,с.Терпіння,23230.0,85101.0,2.323085e+09,UA23080270010078454,small village,UA23000000000064947,NaN,NaN,-1
1,c3136421-569e-422e-ae8f-41c4c931fd70,1998,жіноча,Хмельницька область,Красилівський район,м.Красилів,Випускник української школи поточного року,Красилівська загальноосвітня школа I-III ступе...,середня загальноосвітня школа,Хмельницька область,...,м.Красилів,68227.0,10100.0,6.822710e+09,UA68040210010032567,city,UA68000000000099709,NaN,NaN,-1
2,fbd0e280-4b77-4f34-942d-00bc850c2992,1995,жіноча,Дніпропетровська область,Петропавлівський район,с.Дмитрівка,Випускник минулих років,NaN,NaN,NaN,...,с.Дмитрівка,12238.0,81501.0,1.223882e+09,UA12140170040016918,small village,UA12000000000090473,NaN,NaN,-1
3,30de395e-7a74-452a-8370-6856d240fbfb,1999,чоловіча,Чернівецька область,м.Чернівці,Шевченківський район міста,Випускник української школи поточного року,Чернівецька спеціалізована школа І-ІІІ ступені...,спеціалізована школа,Чернівецька область,...,м.Чернівці,73101.0,0.0,7.310100e+09,UA73060610010033137,city,UA73000000000044923,NaN,NaN,-1
4,52a40c74-374e-4744-bd6f-938ab7a4a641,1997,чоловіча,Миколаївська область,Врадіївський район,с.Кумарі,Учень коледжу закладу професійної (професійно-...,NaN,NaN,NaN,...,с.Кумарі,48223.0,83001.0,4.822383e+09,UA48080050190079797,small village,UA48000000000039575,NaN,NaN,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2202411,6cbe3454-80f0-42b5-8d6d-c2ead687d804,2005,чоловіча,Волинська область,Володимирський район,с.Заболотці,Випускник української школи поточного року,Заболотцівський ліцей Литовезької сільської ра...,середня загальноосвітня школа,Волинська область,...,с.Заболотці,NaN,NaN,NaN,UA07020090030023102,None,UA07000000000024379,UA07020000000048211,NaN,-1
2202412,b897557b-c01b-49d4-8624-b351aaafe5ff,2005,жіноча,Волинська область,Володимирський район,с.Заболотці,Випускник української школи поточного року,Заболотцівський ліцей Литовезької сільської ра...,середня загальноосвітня школа,Волинська область,...,с.Заболотці,NaN,NaN,NaN,UA07020090030023102,None,UA07000000000024379,UA07020000000048211,NaN,-1
2202413,dcec644b-dcec-47ee-9971-6beebd1a929b,2005,чоловіча,Волинська область,Володимирський район,с.Заболотці,Випускник української школи поточного року,Заболотцівський ліцей Литовезької сільської ра...,середня загальноосвітня школа,Волинська область,...,с.Заболотці,NaN,NaN,NaN,UA07020090030023102,None,UA07000000000024379,UA07020000000048211,NaN,-1
2202414,cb4156bb-a624-4274-9d38-28be3096f6b9,2004,жіноча,Волинська область,Володимирський район,с.Заболотці,Випускник української школи поточного року,Заболотцівський ліцей Литовезької сільської ра...,середня загальноосвітня школа,Волинська область,...,с.Заболотці,NaN,NaN,NaN,UA07020090030023102,None,UA07000000000024379,UA07020000000048211,NaN,-1
2202415,7514327a-0831-4adc-8277-41d74e543884,2005,жіноча,Херсонська область,Каховський район,с.Павлівка (Присиваська),Випускник української школи поточного року,Павлівська загальноосвітня школа I-III ступені...,середня загальноосвітня школа,Херсонська область,...,с.Павлівка,NaN,NaN,NaN,UA65060050150037522,None,UA65000000000030969,UA65060000000061947,Присиваська,UA65060190000091058

## Matching ternames 2022

In [128]:
for reg in eie_orig_new_5[eie_orig_new_5.year == 2022].region_code_2023.unique():
    troubles = {}
    for area in eie_orig_new_5[(eie_orig_new_5.year == 2022)&(eie_orig_new_5.region_code_2023 == reg)].area_code_2023.unique():
        trouble = set(eie_orig_new_5[(eie_orig_new_5.region_code_2023 == reg)&(eie_orig_new_5.year == 2022)&(eie_orig_new_5.area_code_2023 == area)].tername_new.str.lower())-set(code2022[(code2022.first_level == reg)&((code2022.second_level == area)|(code2022.additional_level == area))&(code2022.category.isin(['C', 'M', 'T', 'X', 'B']))].reg_name.str.lower())
        if trouble:
            troubles[area] = trouble
    if troubles:
        print(f'{repr(reg)}:{troubles},')

In [129]:
eie_orig_new_5.loc[(eie_orig_new_5.year == 2022)&(eie_orig_new_5.region_code_2023 == 'UA51000000000030770')&(eie_orig_new_5.area_code_2023 == 'UA51100000000095786')&(eie_orig_new_5.tername_new.str.lower() == 'малиновський'), 'tername_new']='Хаджибейський'
eie_orig_new_5.loc[(eie_orig_new_5.year == 2022)&(eie_orig_new_5.region_code_2023 == 'UA51000000000030770')&(eie_orig_new_5.area_code_2023 == 'UA51100000000095786')&(eie_orig_new_5.tername_new.str.lower() == 'суворовський'), 'tername_new']='Пересипський'
eie_orig_new_5.loc[(eie_orig_new_5.year == 2022)&(eie_orig_new_5.region_code_2023 == 'UA05000000000010236')&(eie_orig_new_5.area_code_2023 == 'UA05040000000050292')&(eie_orig_new_5.tername_new.str.lower() == 'с-ще северинівка'), 'tername_new']='с.Северинівка'
eie_orig_new_5.loc[(eie_orig_new_5.year == 2022)&(eie_orig_new_5.region_code_2023 == 'UA18000000000041385')&(eie_orig_new_5.area_code_2023 == 'UA18080000000016657')&(eie_orig_new_5.tername_new.str.lower() == 'м.новоград-волинський'), 'tername_new']='м.Звягель'

In [130]:
eie_orig_new_5['third_level'] = eie_orig_new_5.loc[eie_orig_new_5['year'] == 2022, 'tername'].str.extract(r'\((.*?)\)')

In [131]:
eie_orig_new_5[(eie_orig_new_5.year == 2022)&(eie_orig_new_5.region_code_2023 == 'UA46000000000026241')&(eie_orig_new_5.area_code_2023 == 'UA46060000000042587')&(eie_orig_new_5.tername_new.str.lower() == 'с.волиця')].head()

,outid,birth,sextypename,regname,areaname,tername,regtypename,eoname,eotypename,eoregname,...,tername_new,code,local_code,KOATUU_2020,KATOTTG_2023,category,region_code_2023,area_code_2023,third_level,third_level_code
2013827,481681b1-3220-49fe-8f39-6ab83d39de5d,2005,жіноча,Львівська область,Львівський район,с.Волиця (Рава-Руська),Випускник української школи поточного року,Волицький заклад загальної середньої освіти І-...,середня загальноосвітня школа,Львівська область,...,с.Волиця,NaN,NaN,NaN,UA46060090060018341,None,UA46000000000026241,UA46060000000042587,Рава-Руська,UA46060390000035967
2013828,430856d7-af4f-467f-8570-eff5d53824ae,2004,жіноча,Львівська область,Львівський район,с.Волиця (Рава-Руська),Випускник української школи поточного року,Волицький заклад загальної середньої освіти І-...,середня загальноосвітня школа,Львівська область,...,с.Волиця,NaN,NaN,NaN,UA46060090060018341,None,UA46000000000026241,UA46060000000042587,Рава-Руська,UA46060390000035967
2013844,afb07c32-5f5b-421d-a551-b3f75fac5f8f,2005,жіноча,Львівська область,Львівський район,с.Волиця (Рава-Руська),Випускник української школи поточного року,Волицький заклад загальної середньої освіти І-...,середня загальноосвітня школа,Львівська область,...,с.Волиця,NaN,NaN,NaN,UA46060090060018341,None,UA46000000000026241,UA46060000000042587,Рава-Руська,UA46060390000035967
2013989,dfba96ec-8dcd-4dd5-b76f-62aab32e6b77,2005,чоловіча,Львівська область,Львівський район,с.Волиця (Рава-Руська),Випускник української школи поточного року,Волицький заклад загальної середньої освіти І-...,середня загальноосвітня школа,Львівська область,...,с.Волиця,NaN,NaN,NaN,UA46060090060018341,None,UA46000000000026241,UA46060000000042587,Рава-Руська,UA46060390000035967
2013990,fd9179cf-1830-48a8-962f-ab2a633e9bd8,2006,жіноча,Львівська область,Львівський район,с.Волиця (Рава-Руська),Випускник української школи поточного року,Волицький заклад загальної середньої освіти І-...,середня загальноосвітня школа,Львівська область,...,с.Волиця,NaN,NaN,NaN,UA46060090060018341,None,UA46000000000026241,UA46060000000042587,Рава-Руська,UA46060390000035967

In [132]:
eie_orig_new_5['third_level_code'] = eie_orig_new_5['third_level']

In [133]:
for reg in eie_orig_new_5[eie_orig_new_5.year == 2022].region_code_2023.unique():
    for area in eie_orig_new_5[(eie_orig_new_5.year == 2022)&(eie_orig_new_5.region_code_2023 == reg)].area_code_2023.unique():
        for name in eie_orig_new_5[(eie_orig_new_5.year == 2022)&(eie_orig_new_5.region_code_2023 == reg)&(eie_orig_new_5.area_code_2023 == area)].third_level.str.lower().unique():
            values = code2022.loc[(code2022.first_level == reg)&(code2022.second_level == area)&(code2022.reg_name.str.lower() == name)&(code2022.category.isin(['H', 'B'])), 'third_level'].unique()
            if len(values) == 1:
                eie_orig_new_5.loc[(eie_orig_new_5.year == 2022)&(eie_orig_new_5.region_code_2023 == reg)&(eie_orig_new_5.area_code_2023 == area)&(eie_orig_new_5.third_level.str.lower() == name), 'third_level_code'] = values[0]
            elif len(values)>1:
                print(f'More than one value:{reg}, {area}, {name}, {values}')
            elif len(values)==0 and isinstance(name, str):
                print(f'no values:{reg}, {area}, {name}, {values}')

More than one value:UA59000000000057109, UA59080000000057897, миколаївська, ['UA59080130000022249' 'UA59080150000013842']

In [134]:
eie_orig_new_5[(eie_orig_new_5.year == 2022)&(eie_orig_new_5.region_code_2023 == 'UA59000000000057109')&(eie_orig_new_5.area_code_2023 == 'UA59080000000057897')&(eie_orig_new_5.third_level.str.lower() == 'миколаївська')].head()

,outid,birth,sextypename,regname,areaname,tername,regtypename,eoname,eotypename,eoregname,...,tername_new,code,local_code,KOATUU_2020,KATOTTG_2023,category,region_code_2023,area_code_2023,third_level,third_level_code
2178704,29c61acb-3186-4405-af2f-17dafea418cc,1999,чоловіча,Сумська область,Сумський район,с.Веселе (Миколаївська),Випускник минулих років,NaN,NaN,NaN,...,с.Веселе,NaN,NaN,NaN,UA59080090050088967,None,UA59000000000057109,UA59080000000057897,Миколаївська,Миколаївська
2178968,b67b8858-46b2-41a0-9877-7505c970ab5d,2003,чоловіча,Сумська область,Сумський район,с.Софіївка (Миколаївська),Випускник минулих років,NaN,NaN,NaN,...,с.Софіївка,NaN,NaN,NaN,UA59080110980095523,None,UA59000000000057109,UA59080000000057897,Миколаївська,Миколаївська

In [135]:
eie_orig_new_5.loc[(eie_orig_new_5.year == 2022)&(eie_orig_new_5.region_code_2023 == 'UA59000000000057109')&(eie_orig_new_5.area_code_2023 == 'UA59080000000057897')&(eie_orig_new_5.third_level.str.lower() == 'миколаївська')&(eie_orig_new_5.tername_new.str.lower() == 'с.веселе'), 'third_level_code']='UA59080130000022249'
eie_orig_new_5.loc[(eie_orig_new_5.year == 2022)&(eie_orig_new_5.region_code_2023 == 'UA59000000000057109')&(eie_orig_new_5.area_code_2023 == 'UA59080000000057897')&(eie_orig_new_5.third_level.str.lower() == 'миколаївська')&(eie_orig_new_5.tername_new.str.lower() == 'с.софіївка'), 'third_level_code']='UA59080150000013842'

In [136]:
eie_orig_new_5[(eie_orig_new_5.year == 2022)]['third_level_code'].unique()

array([nan, 'UA23080310000097001', 'UA14120110000031497',
       'UA05040010000022470', 'UA05040030000050131',
       'UA61060050000068464', 'UA56080090000098391',
       'UA48040190000026236', 'UA23100270000073418',
       'UA12020090000044548', 'UA71080250000099725',
       'UA63020090000096294', 'UA48060290000080246',
       'UA23100150000023366', 'UA65020210000085773',
       'UA23080290000096336', 'UA35040110000055821',
       'UA56060050000010769', 'UA35040270000084621',
       'UA12140270000072109', 'UA68040210000089917',
       'UA51060170000068967', 'UA18080210000038722',
       'UA23080150000073640', 'UA12040170000019083',
       'UA61060390000013361', 'UA05020110000052014',
       'UA74100150000090847', 'UA71080110000055395',
       'UA63100070000048302', 'UA68040290000010822',
       'UA35040170000065192', 'UA12140110000060935',
       'UA63060090000041888', 'UA46100070000076013',
       'UA18040330000027310', 'UA63060010000015783',
       'UA73060350000057190', 'UA18080030000019784',
       'UA63140110000087562', 'UA32120030000030458',
       'UA48020050000023194', 'UA18040030000089649',
       'UA32120090000034281', 'UA71080030000050121',
       'UA35040310000035890', 'UA51040290000011852',
       'UA48040210000049987', 'UA61060070000098188',
       'UA12140030000091432', 'UA53080150000085889',
       'UA35080110000063919', 'UA35040150000097644',
       'UA74040190000070909', 'UA48060050000074873',
       'UA23040070000097076', 'UA63040010000010092',
       'UA12140010000024967', 'UA63060110000043554',
       'UA46100150000087495', 'UA71040190000080571',
       'UA12040050000057182', 'UA74040050000013413',
       'UA26080030000014307', 'UA61020050000098539',
       'UA05020230000029909', 'UA61040210000084270',
       'UA12060010000090992', 'UA46100030000016064',
       'UA35060210000019042', 'UA32060010000086043',
       'UA73060470000040033', 'UA44100010000048313',
       'UA61020010000028670', 'UA05120170000013778',
       'UA14040050000064688', 'UA18080130000032098',
       'UA46060390000035967', 'UA48060010000061913',
       'UA56080150000069525', 'UA46120130000026331',
       'UA53080410000094938', 'UA53080290000024637',
       'UA68040470000053519', 'UA23020090000069977',
       'UA35060170000071056', 'UA32140030000074165',
       'UA18040290000063354', 'UA61040150000098181',
       'UA53080110000062015', 'UA12140170000037152',
       'UA65040070000086673', 'UA65040010000061104',
       'UA53080450000087891', 'UA05020030000031457',
       'UA12040190000056469', 'UA48020110000020969',
       'UA48040150000011861', 'UA32020190000084133',
       'UA73060590000095243', 'UA56060450000083945',
       'UA46100050000053848', 'UA35040130000021732',
       'UA59080290000021284', 'UA53080090000014431',
       'UA07060450000051170', 'UA14160170000023385',
       'UA48080050000053070', 'UA14160190000059231',
       'UA46060090000017373', 'UA18040210000044466',
       'UA18060190000071101', 'UA68040510000019366',
       'UA12020190000075117', 'UA53020230000086353',
       'UA46120110000062257', 'UA53080330000062155',
       'UA12140370000059352', 'UA53080210000072644',
       'UA48020230000095751', 'UA71020050000074004',
       'UA51060030000044366', 'UA12060150000015198',
       'UA48020190000083597', 'UA12140150000054570',
       'UA53080190000081150', 'UA12060030000081794',
       'UA35060010000018331', 'UA48080110000010732',
       'UA18020010000059904', 'UA35060130000087718',
       'UA56060030000057923', 'UA63020050000045982',
       'UA48060350000011218', 'UA61020110000084342',
       'UA59020130000060377', 'UA56080130000056682',
       'UA14120030000057882', 'UA63140150000093944',
       'UA05120130000014261', 'UA48020030000061219',
       'UA35060250000057436', 'UA61020150000036935',
       'UA23100230000021603', 'UA14120170000011133',
       'UA63100030000050119', 'UA18040470000074046',
       'UA63080030000019649', 'UA61040370000060170',
       'UA32060070000092009', 'UA53080390000027656',
       'UA51060010000033212', 'UA51100330000051757',
       'UA51120110000047677', 'UA44140110000056578',
       'UA48060250000061313', 'UA35060110000056063',
       'UA48060370000016130', 'UA18040510000013419',
       'UA65080170000067222', 'UA18040490000014752',
       'UA18040250000068141', 'UA73060430000042676',
       'UA14160070000097326', 'UA05120150000069474',
       'UA71040050000016509', 'UA48080070000061107',
       'UA44140090000072167', 'UA14160250000075646',
       'UA53060230000098362', 'UA68040030000027335',
       'UA51140090000048720', 'UA05020270000044358',
       'UA05060050000058111', 'UA48080030000050927',
       'UA12060270000017282', 'UA23100290000069212',
       'UA68040330000086970', 'UA63100050000079487',
       'UA63060070000031032', 'UA68040150000077185',
       'UA68020190000052031', 'UA63100010000016136',
       'UA53040050000091161', 'UA12020250000010438',
       'UA63040030000052515', 'UA48020090000069919',
       'UA63060030000041642', 'UA56060410000055190',
       'UA68040390000011141', 'UA05040050000080930',
       'UA12140250000015858', 'UA61040050000096355',
       'UA12140050000051356', 'UA23080190000065134',
       'UA32020210000064694', 'UA48020130000080862',
       'UA68040050000052367', 'UA51040090000096249',
       'UA51060070000052726', 'UA18040070000059677',
       'UA12040230000099388', 'UA12020050000026654',
       'UA05040090000093950', 'UA35080130000048304',
       'UA44140050000026566', 'UA18020130000096761',
       'UA59080010000078468', 'UA12060190000043514',
       'UA18060230000071114', 'UA05020070000010139',
       'UA51140070000052649', 'UA53080270000062586',
       'UA65060210000049771', 'UA14120230000038918',
       'UA32020170000020698', 'UA48060090000097375',
       'UA18020110000026941', 'UA32140170000038368',
       'UA59020050000012539', 'UA46100230000047305',
       'UA48020010000091496', 'UA32140050000046018',
       'UA71060090000088339', 'UA51020310000020019',
       'UA07080290000088287', 'UA12060070000012840',
       'UA07040090000043197', 'UA63020030000094096',
       'UA18040590000064402', 'UA61060290000038953',
       'UA12040210000039759', 'UA74100270000049748',
       'UA14160130000011561', 'UA07080170000013585',
       'UA63140030000091352', 'UA14040070000032181',
       'UA68040430000052699', 'UA46140110000063568',
       'UA61040350000078247', 'UA07080230000046097',
       'UA53080130000014699', 'UA68040130000024471',
       'UA23100170000031289', 'UA51100090000094901',
       'UA12060250000064393', 'UA61040230000060213',
       'UA65080150000042499', 'UA51020230000068053',
       'UA05080030000089348', 'UA48060070000087404',
       'UA53060290000047345', 'UA65060170000032937',
       'UA48040030000013036', 'UA48020070000050731',
       'UA12140070000025486', 'UA05020090000067118',
       'UA05020130000056031', 'UA05040130000025322',
       'UA05060010000053179', 'UA05020210000033427',
       'UA05080090000089922', 'UA05100150000050790',
       'UA07020110000037373', 'UA07080150000089103',
       'UA12020270000063450', 'UA14160050000083011',
       'UA18020070000083539', 'UA07080250000053335',
       'UA12020230000085693', 'UA18040570000099817',
       'UA14120190000021407', 'UA12060110000015305',
       'UA18040130000075048', 'UA12040070000083117',
       'UA23060270000087706', 'UA26080110000076323',
       'UA12080130000071360', 'UA14120050000033910',
       'UA12140090000053443', 'UA12060210000077302',
       'UA23100190000020018', 'UA12140330000063909',
       'UA35020070000018243', 'UA18040010000031446',
       'UA14160110000031920', 'UA18040390000055900',
       'UA18040610000049084', 'UA18080190000029932',
       'UA18040430000080827', 'UA18040270000050167',
       'UA18060130000061781', 'UA14140050000020560',
       'UA26040070000065724', 'UA35060230000086264',
       'UA35060030000099117', 'UA46040070000032075',
       'UA14160270000099007', 'UA23060330000027462',
       'UA46120090000051307', 'UA46080110000050484',
       'UA46060450000037997', 'UA18060110000061631',
       'UA18080010000090720', 'UA35040330000014430',
       'UA26060170000091466', 'UA26040190000081578',
       'UA26060070000011203', 'UA26080150000032640',
       'UA51120030000075494', 'UA51140010000090773',
       'UA53080010000088479', 'UA48040090000070960',
       'UA48060330000083035', 'UA46040130000035029',
       'UA32020010000093088', 'UA48060310000084930',
       'UA51020270000068435', 'UA32060130000095223',
       'UA32080030000070006', 'UA32080130000056481',
       'UA48040170000057262', 'UA26040330000019235',
       'UA26040270000047749', 'UA48060230000098265',
       'UA53060250000043118', 'UA53080050000011754',
       'UA53080370000025447', 'UA48040010000016403',
       'UA35040190000012514', 'UA35040230000015609',
       'UA53040110000034949', 'UA51120130000064324',
       'UA46040030000058332', 'UA46040010000033885',
       'UA35080010000032386', 'UA51120150000080138',
       'UA53040030000088898', 'UA71080150000071745',
       'UA74100030000076377', 'UA68020030000032574',
       'UA68020010000017180', 'UA63120170000093573',
       'UA61040430000018305', 'UA61040170000086062',
       'UA61060170000051011', 'UA68020250000080044',
       'UA68040450000097735', 'UA68060030000077318',
       'UA68060310000022172', 'UA59080070000062635',
       'UA59060030000069916', 'UA59100010000064812',
       'UA51020170000041393', 'UA61040070000079091',
       'UA63120110000043456', 'UA51020150000090298',
       'UA53060210000044776', 'UA53040010000091190',
       'UA63080150000094794', 'UA61060370000081851',
       'UA65060130000026961', 'UA59080130000022249',
       'UA59080150000013842', 'UA59080110000034361',
       'UA71020090000047211', 'UA61060150000032895',
       'UA61040310000059301', 'UA51100230000045500',
       'UA68040530000044109', 'UA68040090000087566',
       'UA71020330000027449', 'UA61040110000010646',
       'UA61020090000020422', 'UA53020070000049284',
       'UA32020030000029575', 'UA61040470000038207',
       'UA74040290000072674', 'UA63140010000049419',
       'UA56040190000045841', 'UA35060090000091976',
       'UA68020150000089666', 'UA68040170000061140',
       'UA74040010000076097', 'UA56060490000031684',
       'UA61040250000021345', 'UA59080270000073662',
       'UA61060130000045755', 'UA63020010000079018',
       'UA68040310000052042', 'UA56060390000090915',
       'UA56080070000040721', 'UA59020090000085438',
       'UA46100270000094052', 'UA46100130000048262',
       'UA71060230000095772', 'UA51040110000040346',
       'UA61020070000092368', 'UA61040130000085402',
       'UA71020290000032540', 'UA71040210000024694',
       'UA61060310000061998', 'UA61040270000064661',
       'UA12060050000031212', 'UA14040150000099558',
       'UA65040050000029613', 'UA35020010000028961',
       'UA05080070000010150', 'UA14160210000011148',
       'UA71040170000034734', 'UA35040290000046019',
       'UA32020230000012716', 'UA48040250000044166',
       'UA68020050000040518', 'UA14120150000071686',
       'UA65060190000091058'], dtype=object)

In [137]:
eie_orig_new_6 =eie_orig_new_5

In [138]:
eie_orig_new_6['third_level_code'].fillna(-1, inplace=True)

In [139]:
eie_orig_new_6

,outid,birth,sextypename,regname,areaname,tername,regtypename,eoname,eotypename,eoregname,...,tername_new,code,local_code,KOATUU_2020,KATOTTG_2023,category,region_code_2023,area_code_2023,third_level,third_level_code
0,a99c6c63-aa70-4aec-ba42-370f7261e857,1998,чоловіча,Запорізька область,Мелітопольський район,с.Терпіння,Випускник української школи поточного року,"Терпіннівський колегіум ""Джерело"" Мелітопольсь...",колегіум,Запорізька область,...,с.Терпіння,23230.0,85101.0,2.323085e+09,UA23080270010078454,small village,UA23000000000064947,NaN,NaN,-1
1,c3136421-569e-422e-ae8f-41c4c931fd70,1998,жіноча,Хмельницька область,Красилівський район,м.Красилів,Випускник української школи поточного року,Красилівська загальноосвітня школа I-III ступе...,середня загальноосвітня школа,Хмельницька область,...,м.Красилів,68227.0,10100.0,6.822710e+09,UA68040210010032567,city,UA68000000000099709,NaN,NaN,-1
2,fbd0e280-4b77-4f34-942d-00bc850c2992,1995,жіноча,Дніпропетровська область,Петропавлівський район,с.Дмитрівка,Випускник минулих років,NaN,NaN,NaN,...,с.Дмитрівка,12238.0,81501.0,1.223882e+09,UA12140170040016918,small village,UA12000000000090473,NaN,NaN,-1
3,30de395e-7a74-452a-8370-6856d240fbfb,1999,чоловіча,Чернівецька область,м.Чернівці,Шевченківський район міста,Випускник української школи поточного року,Чернівецька спеціалізована школа І-ІІІ ступені...,спеціалізована школа,Чернівецька область,...,м.Чернівці,73101.0,0.0,7.310100e+09,UA73060610010033137,city,UA73000000000044923,NaN,NaN,-1
4,52a40c74-374e-4744-bd6f-938ab7a4a641,1997,чоловіча,Миколаївська область,Врадіївський район,с.Кумарі,Учень коледжу закладу професійної (професійно-...,NaN,NaN,NaN,...,с.Кумарі,48223.0,83001.0,4.822383e+09,UA48080050190079797,small village,UA48000000000039575,NaN,NaN,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2202411,6cbe3454-80f0-42b5-8d6d-c2ead687d804,2005,чоловіча,Волинська область,Володимирський район,с.Заболотці,Випускник української школи поточного року,Заболотцівський ліцей Литовезької сільської ра...,середня загальноосвітня школа,Волинська область,...,с.Заболотці,NaN,NaN,NaN,UA07020090030023102,None,UA07000000000024379,UA07020000000048211,NaN,-1
2202412,b897557b-c01b-49d4-8624-b351aaafe5ff,2005,жіноча,Волинська область,Володимирський район,с.Заболотці,Випускник української школи поточного року,Заболотцівський ліцей Литовезької сільської ра...,середня загальноосвітня школа,Волинська область,...,с.Заболотці,NaN,NaN,NaN,UA07020090030023102,None,UA07000000000024379,UA07020000000048211,NaN,-1
2202413,dcec644b-dcec-47ee-9971-6beebd1a929b,2005,чоловіча,Волинська область,Володимирський район,с.Заболотці,Випускник української школи поточного року,Заболотцівський ліцей Литовезької сільської ра...,середня загальноосвітня школа,Волинська область,...,с.Заболотці,NaN,NaN,NaN,UA07020090030023102,None,UA07000000000024379,UA07020000000048211,NaN,-1
2202414,cb4156bb-a624-4274-9d38-28be3096f6b9,2004,жіноча,Волинська область,Володимирський район,с.Заболотці,Випускник української школи поточного року,Заболотцівський ліцей Литовезької сільської ра...,середня загальноосвітня школа,Волинська область,...,с.Заболотці,NaN,NaN,NaN,UA07020090030023102,None,UA07000000000024379,UA07020000000048211,NaN,-1
2202415,7514327a-0831-4adc-8277-41d74e543884,2005,жіноча,Херсонська область,Каховський район,с.Павлівка (Присиваська),Випускник української школи поточного року,Павлівська загальноосвітня школа I-III ступені...,середня загальноосвітня школа,Херсонська область,...,с.Павлівка,NaN,NaN,NaN,UA65060050150037522,None,UA65000000000030969,UA65060000000061947,Присиваська,UA65060190000091058

In [146]:
# Filter the relevant rows from eie_orig_new_5 for the year 2022
filtered_eie = eie_orig_new_6[eie_orig_new_6['year'] == 2022]

# Group by the required columns to minimize iterations
grouped_eie = filtered_eie.groupby(['region_code_2023', 'area_code_2023', 'third_level_code', 'tername_new'])

# Iterate over the groups and process them
for (reg, area, third_lev, name), group in grouped_eie:
    lower_name = name.lower()
    if isinstance(third_lev, str):
        values = code2022.loc[
            (code2022['first_level'] == reg) &
            (code2022['second_level'] == area) &
            (code2022['third_level'] == third_lev) &
            (code2022['reg_name'].str.lower() == lower_name) &
            (code2022['category'].isin(['C', 'M', 'T', 'X'])), 'fourth_level'
        ].unique()
        values_add = code2022.loc[
            (code2022['first_level'] == reg) &
            (code2022['second_level'] == area) &
            (code2022['third_level'] == third_lev) &
            (code2022['reg_name'].str.lower() == lower_name) &
            (code2022['category'] == 'B'), 'additional_level'
        ].unique()
    
    else:
        values = code2022.loc[
            (code2022['first_level'] == reg) &
            (code2022['second_level'] == area) &
            (code2022['reg_name'].str.lower() == lower_name) &
            (code2022['category'].isin(['C', 'M', 'T', 'X'])), 'fourth_level'
        ].unique()
        values_add = code2022.loc[
            (code2022['first_level'] == reg) &
            (code2022['second_level'] == area) &
            (code2022['reg_name'].str.lower() == lower_name) &
            (code2022['category'] == 'B'), 'additional_level'
        ].unique()

    if len(values) >= 1:
        eie_orig_new_6.loc[group.index, 'KATOTTG_2023'] = values[0]
    elif len(values_add) == 1:
        eie_orig_new_6.loc[group.index, 'KATOTTG_2023'] = values_add[0]
    else:
        print(reg, area, third_lev, name, values, values_add)

In [144]:
filtered_eie = eie_orig_new_6[eie_orig_new_6['year'] == 2022]

In [ ]:
reg='UA65000000000030969'
area = 'UA65060000000061947'
third_lev = 'UA65060190000091058'
name='с.Павлівка'
group= filtered_eie[(filtered_eie.region_code_2023 == reg)&(filtered_eie.area_code_2023 == area) & (filtered_eie.third_lev == third_lev]
    lower_name = name.lower()
    values = code2022.loc[
        (code2022['first_level'] == reg) &
        (code2022['second_level'] == area) &
        (code2022['reg_name'].str.lower() == lower_name) &
        (code2022['category'].isin(['C', 'M', 'T', 'X'])), 'fourth_level'
    ].unique()
    values_add = code2022.loc[
        (code2022['first_level'] == reg) &
        (code2022['second_level'] == area) &
        (code2022['reg_name'].str.lower() == lower_name) &
        (code2022['category'] == 'B'), 'additional_level'
    ].unique()

In [142]:
eie_orig_new_6[(eie_orig_new_6.KATOTTG_2023.isna())]

Empty DataFrame
Columns: [outid, birth, sextypename, regname, areaname, tername, regtypename, eoname, eotypename, eoregname, eoareaname, eotername, eoparent, ukrtest, ukrteststatus, ukrball100, ukrball12, ukrptname, ukrptregname, ukrptareaname, ukrpttername, histtest, histlang, histteststatus, histball100, histball12, histptname, histptregname, histptareaname, histpttername, mathtest, mathlang, mathteststatus, mathball100, mathball12, mathptname, mathptregname, mathptareaname, mathpttername, phystest, physlang, physteststatus, physball100, physptname, physptregname, physptareaname, physpttername, chemtest, chemlang, chemteststatus, chemball100, chemptname, chemptregname, chemptareaname, chempttername, biotest, biolang, bioteststatus, bioball100, bioptname, bioptregname, bioptareaname, biopttername, geotest, geolang, geoteststatus, geoball100, geoptname, geoptregname, geoptareaname, geopttername, engtest, engteststatus, engball100, engptname, engptregname, engptareaname, engpttername, fratest, frateststatus, fraball100, fraptname, fraptregname, fraptareaname, frapttername, deutest, deuteststatus, deuball100, deuptname, deuptregname, deuptareaname, deupttername, spatest, spateststatus, spaball100, spaptname, spaptregname, spaptareaname, spapttername, rustest, ...]
Index: []

[0 rows x 163 columns]

In [147]:
eie_orig_new_6

,outid,birth,sextypename,regname,areaname,tername,regtypename,eoname,eotypename,eoregname,...,tername_new,code,local_code,KOATUU_2020,KATOTTG_2023,category,region_code_2023,area_code_2023,third_level,third_level_code
0,a99c6c63-aa70-4aec-ba42-370f7261e857,1998,чоловіча,Запорізька область,Мелітопольський район,с.Терпіння,Випускник української школи поточного року,"Терпіннівський колегіум ""Джерело"" Мелітопольсь...",колегіум,Запорізька область,...,с.Терпіння,23230.0,85101.0,2.323085e+09,UA23080270010078454,small village,UA23000000000064947,NaN,NaN,-1
1,c3136421-569e-422e-ae8f-41c4c931fd70,1998,жіноча,Хмельницька область,Красилівський район,м.Красилів,Випускник української школи поточного року,Красилівська загальноосвітня школа I-III ступе...,середня загальноосвітня школа,Хмельницька область,...,м.Красилів,68227.0,10100.0,6.822710e+09,UA68040210010032567,city,UA68000000000099709,NaN,NaN,-1
2,fbd0e280-4b77-4f34-942d-00bc850c2992,1995,жіноча,Дніпропетровська область,Петропавлівський район,с.Дмитрівка,Випускник минулих років,NaN,NaN,NaN,...,с.Дмитрівка,12238.0,81501.0,1.223882e+09,UA12140170040016918,small village,UA12000000000090473,NaN,NaN,-1
3,30de395e-7a74-452a-8370-6856d240fbfb,1999,чоловіча,Чернівецька область,м.Чернівці,Шевченківський район міста,Випускник української школи поточного року,Чернівецька спеціалізована школа І-ІІІ ступені...,спеціалізована школа,Чернівецька область,...,м.Чернівці,73101.0,0.0,7.310100e+09,UA73060610010033137,city,UA73000000000044923,NaN,NaN,-1
4,52a40c74-374e-4744-bd6f-938ab7a4a641,1997,чоловіча,Миколаївська область,Врадіївський район,с.Кумарі,Учень коледжу закладу професійної (професійно-...,NaN,NaN,NaN,...,с.Кумарі,48223.0,83001.0,4.822383e+09,UA48080050190079797,small village,UA48000000000039575,NaN,NaN,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2202411,6cbe3454-80f0-42b5-8d6d-c2ead687d804,2005,чоловіча,Волинська область,Володимирський район,с.Заболотці,Випускник української школи поточного року,Заболотцівський ліцей Литовезької сільської ра...,середня загальноосвітня школа,Волинська область,...,с.Заболотці,NaN,NaN,NaN,UA07020090030023102,None,UA07000000000024379,UA07020000000048211,NaN,-1
2202412,b897557b-c01b-49d4-8624-b351aaafe5ff,2005,жіноча,Волинська область,Володимирський район,с.Заболотці,Випускник української школи поточного року,Заболотцівський ліцей Литовезької сільської ра...,середня загальноосвітня школа,Волинська область,...,с.Заболотці,NaN,NaN,NaN,UA07020090030023102,None,UA07000000000024379,UA07020000000048211,NaN,-1
2202413,dcec644b-dcec-47ee-9971-6beebd1a929b,2005,чоловіча,Волинська область,Володимирський район,с.Заболотці,Випускник української школи поточного року,Заболотцівський ліцей Литовезької сільської ра...,середня загальноосвітня школа,Волинська область,...,с.Заболотці,NaN,NaN,NaN,UA07020090030023102,None,UA07000000000024379,UA07020000000048211,NaN,-1
2202414,cb4156bb-a624-4274-9d38-28be3096f6b9,2004,жіноча,Волинська область,Володимирський район,с.Заболотці,Випускник української школи поточного року,Заболотцівський ліцей Литовезької сільської ра...,середня загальноосвітня школа,Волинська область,...,с.Заболотці,NaN,NaN,NaN,UA07020090030023102,None,UA07000000000024379,UA07020000000048211,NaN,-1
2202415,7514327a-0831-4adc-8277-41d74e543884,2005,жіноча,Херсонська область,Каховський район,с.Павлівка (Присиваська),Випускник української школи поточного року,Павлівська загальноосвітня школа I-III ступені...,середня загальноосвітня школа,Херсонська область,...,с.Павлівка,NaN,NaN,NaN,UA65060050150037522,None,UA65000000000030969,UA65060000000061947,Присиваська,UA65060190000091058

In [108]:
for reg in eie_orig_new_5[eie_orig_new_5.year == 2022].region_code_2023.unique():
    for area in eie_orig_new_5[(eie_orig_new_5.year == 2022)&(eie_orig_new_5.region_code_2023 == reg)].area_code_2023.unique():
        for third_lev in eie_orig_new_5[(eie_orig_new_5.year == 2022)&(eie_orig_new_5.region_code_2023 == reg)&(eie_orig_new_5.area_code_2023 == area)].third_level_code.unique():
            if isinstance(third_lev, str):
                for name in eie_orig_new_5[(eie_orig_new_5.year == 2022)&(eie_orig_new_5.region_code_2023 == reg)&(eie_orig_new_5.area_code_2023 == area)&(eie_orig_new_5.third_level_code == third_lev)].tername_new.str.lower().unique():
                    values = code2022.loc[(code2022.first_level == reg)&(code2022.second_level == area)&(code2022.third_level == third_lev)&(code2022.category.isin(['C', 'M', 'T', 'X']))&(code2022.reg_name.str.lower() == name), 'fourth_level'].unique()
                    if len(values) >= 1:
                        eie_orig_new_5.loc[(eie_orig_new_5.year == 2022)&(eie_orig_new_5.region_code_2023 == reg)&(eie_orig_new_5.area_code_2023 == area)&(eie_orig_new_5.third_level_code == third_lev)&(eie_orig_new_5.tername_new.str.lower()==name), 'KATOTTG_2023'] = values[0]
                    else:
                        print(reg, area, third_lev, name, values, values_add)
                continue
            for name in eie_orig_new_5[(eie_orig_new_5.year == 2022)&(eie_orig_new_5.region_code_2023 == reg)&(eie_orig_new_5.area_code_2023 == area)].tername_new.str.lower().unique():
                values = code2022.loc[(code2022.first_level == reg)&(code2022.second_level == area)&(code2022.category.isin(['C', 'M', 'T', 'X']))&(code2022.reg_name.str.lower() == name), 'fourth_level'].unique()
                values_add = code2022.loc[(code2022.first_level == reg)&(code2022.second_level == area)&(code2022.category.isin(['B']))&(code2022.reg_name.str.lower() == name), 'additional_level'].unique()
                #if more than 1 we,unfortunately, could not identify the location, so take the first code
                if len(values) >= 1:
                    eie_orig_new_5.loc[(eie_orig_new_5.year == 2022)&(eie_orig_new_5.region_code_2023 == reg)&(eie_orig_new_5.area_code_2023 == area)&(eie_orig_new_5.tername_new.str.lower()==name), 'KATOTTG_2023'] = values[0]
                elif len(values_add) == 1:
                    eie_orig_new_5.loc[(eie_orig_new_5.year == 2022)&(eie_orig_new_5.region_code_2023 == reg)&(eie_orig_new_5.area_code_2023 == area)&(eie_orig_new_5.tername_new.str.lower()==name), 'KATOTTG_2023'] = values_add[0]
                else:
                    print(reg, area, name, values, values_add)

KeyboardInterrupt:

In [348]:
eie_orig_new_5.loc[(eie_orig_new_5.year == 2022)&(eie_orig_new_5.region_code == 'UA63000000000041885')&(eie_orig_new_5.area_code == 'UA63080000000032022')&(eie_orig_new_5.tername_new.str.lower() == 'с.осиново'), 'KATOTTG_2023']='UA63080090060022231'
eie_orig_new_5.loc[(eie_orig_new_5.year == 2022)&(eie_orig_new_5.region_code == 'UA59000000000057109')&(eie_orig_new_5.area_code == 'UA59080000000057897')&(eie_orig_new_5.tername_new.str.lower() == 'с.старе село'), 'KATOTTG_2023']='UA59080190050096368'

In [355]:
eie_orig_new_5[eie_orig_new_5.KATOTTG_2023.isna()][['region_code', 'area_code', 'third_level_code', 'tername_new']]

,region_code,area_code,third_level_code,tername_new
1968881,UA80000000000093317,UA80000000000479391,NaN,Дніпровський
1968882,UA80000000000093317,UA80000000000479391,NaN,Дніпровський
1968883,UA80000000000093317,UA80000000000479391,NaN,Дніпровський
1968884,UA80000000000093317,UA80000000000479391,NaN,Дніпровський
1968885,UA80000000000093317,UA80000000000479391,NaN,Дніпровський
...,...,...,...,...
2200641,UA80000000000093317,UA80000000001078669,NaN,Шевченківський
2200642,UA80000000000093317,UA80000000001078669,NaN,Шевченківський
2200643,UA80000000000093317,UA80000000001078669,NaN,Шевченківський
2200644,UA80000000000093317,UA80000000001078669,NaN,Шевченківський
2200645,UA80000000000093317,UA80000000001078669,NaN,Шевченківський

In [339]:
values = code2022.loc[(code2022.first_level == 'UA26000000000069363')&(code2022.second_level == 'UA26120000000036058')&(code2022.category.isin(['C', 'M', 'T', 'X']))&(code2022.reg_name.str.lower() == 'с.гвізд'), 'fourth_level'].unique()
values

array(['UA26120070030065363'], dtype=object)

In [338]:
code2022[(code2022.first_level == 'UA26000000000069363')&(code2022.second_level == 'UA26120000000036058')&(code2022.category.isin(['C', 'M', 'T', 'X']))&(code2022.reg_name.str.lower() == 'с.гвізд')]

,first_level,second_level,third_level,fourth_level,additional_level,category,name,reg_name
11375,UA26000000000069363,UA26120000000036058,UA26120070000067596,UA26120070030065363,NaN,C,Гвізд,с.Гвізд